### PR TITLE
Reflection_Engine: shorten the params input description if longer than a max value

### LINKED ISSUE #1171: BHoM sub-menu are disappearing to the next screen when method text is too long
#### Description:
See title and this:

image

#### How to replicate:
Add a `CreateObject` component to the canvas and, in the contextual menu, go to `Climate.EnvironmentCondition`

#### Expected behaviour:
The Menu should stay on the same screen

I would recommend simply limiting the size of the string representing the method to a given value. Will have to figure what a good value is though. We have 3 places where the text need to be truncated: Ctrl-Shift-B menu, search in the component menu and component menu itself. If there are multiple places where `ToText()` is called, refactor so that it is done inside a method that also limit the size.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #1171 

### Test files
image

image

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
Starting by just commenting that using those examples in the image from the Climate part of the Environments Engine is truly showing the speed of development and change on BHoM, as both of those were only merged into the engine this morning (https://github.com/BHoM/BHoM_Engine/pull/1167)

Truly amazing! I'll do a proper review now! :smile:

**Comment by al-fisher** [comment]
Totally agree @FraserGreenroyd  🚀🚀🚀🚀

**Comment by FraserGreenroyd** [comment]
image

Some issues with this @alelom as discussed just now - will await for you to push the toggle change and retest :smile:

**Comment by alelom** [comment]
Also going to add a check for maximum number of characters to make it more robust.

**Comment by alelom** [comment]
Thanks for that, now it should be working fine.

**Comment by FraserGreenroyd** [comment]
Cheers @alelom I'll take a look!

**Comment by alelom** [comment]
Thanks! 😄

**Comment by FraserGreenroyd** [comment]
Discussed with @alelom and am merging based on the approving review to ensure ability to continue with further changes for Reflection_Engine as part of 2.4 and this current 2-week sprint :smile:

**Pull request merged**
