### PR TITLE
Remove invalid unit test dataset

### LINKED ISSUE #3057: Architecture Unit Tests
Following https://github.com/BHoM/BHoM_Engine/pull/3056 it is identified that there are issues with the Architecture Unit Tests containing invalid data. These should be fixed or removed.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #3057

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: installer, dataset-compliance, ready-to-merge

**Review by CKBoulter — APPROVED** [review]
Dataset removed as required/explained by @FraserGreenroyd

**Pull request merged**
