### PR TITLE
Security_Engine: Camera Field of View angle fix

### LINKED ISSUE #3098: Security_Engine: Camera Field of View incorrect angle
#### Description:

Angle of the camera field of view is incorrect.

### PR DESCRIPTION
**Pull request by michal-pekacki**
### Issues addressed by this PR

Closes #3098 

Corrected angle calculation for `Camera Field of View`.

### Test files

[Rhino and GH files](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Security_Engine/%232888-CameraFieldOfView?csf=1&web=1&e=rWkaoD)

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by pawelbaran — APPROVED** [review]
Tested, works as expected

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@FraserGreenroyd looks like the unit test check is failing without reporting - would be nice if you could have a look at some point (but no big rush from what I reckon)

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 14635662271

**Pull request merged**
