### PR TITLE
Serialiser_Engine: colour serialisation bug fixed

### LINKED ISSUE #2501: Serialiser_Engine: System.Drawing.Color fails to deserialise correctly when not being a property of type Color
#### Description:

As in the title, `System.Drawing.Color` gets serialised and deserialised correctly only if it is wrapped in a property of same type. In other circumstances it seems to fail - see the test file.

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FSerialiser%5FEngine%2F%232501%2DColourSerialisationBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #2501

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FSerialiser%5FEngine%2F%232501%2DColourSerialisationBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@FraserGreenroyd I would not mind ignoring the compliance taken that it is a minor bugfix that does not interfere with the method signatures at all.

**Comment by adecler** [comment]
> @FraserGreenroyd I would not mind ignoring the compliance taken that it is a minor bugfix that does not interfere with the method signatures at all.

This is not a static method so there shouldn't be a test on it related to extension methods.

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Review by adecler — APPROVED** [review]
Tested and works fine
- both when Color is a top object and a property
- both on old version and new

Glad to see that the verification on serialization is also happy

**Pull request merged**
