### PR TITLE
Spatial_Engine: Remove unnecessary area methods

### LINKED ISSUE #2086: Spatial_Engine: There should be no Area method for IElement1D and IElement0D
#### Broken rules:

We have methods for calculating the Area for an `IElement1D` and `IElement0D`. This has been shown to cause issues such as 

https://github.com/BHoM/BHoM_Engine/issues/2081
https://github.com/BHoM/BHoM_Engine/issues/2085

Unless we have a clear need to have an area method that works for any `IElement` I suggest we simply remove the methods for `IElement1D`, `IElement0D` as well as the interface method for `IElement` as it is royally confusing to call Area method as it stands in the Spatial_Engine, which is one of the core places we want to deal with geometry.

#### Suggestions to restore compliance:

Remove the `Area` methods for `IElement1D`, `IElement0D` as well as the interface method for `IElement`

Any objections to why this should not be done? @pawelbaran @al-fisher @LMarkowski @FraserGreenroyd @michaelhoehn

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #2086

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by Tom-Kingstone — APPROVED** [review]
On code review, approving as this covers points set out in original issue(s).

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
