### PR TITLE
Diffing_Engine: fix `NumericalDifferenceInclusion()` that did not trigger check on `IsNumerical()` correctly

### LINKED ISSUE #2807: Diffing_Engine: `NumericalDifferenceInclusion()` does not trigger check on `IsNumerical()` correctly (missing parenthesis)
#### Description:

As title. There's a missing parenthesis here:

https://github.com/BHoM/BHoM_Engine/blob/2ced9d53c640cdcc38e596ba44da3a965dbe1323/Diffing_Engine/Query/NumericalDifferenceInclusion.cs#L74-L76

The last two checks that call `IsNumeric()` are never invoked, because the checks before are not wrapped in parentheses.

#### Steps to reproduce:

Invoke the RevitDiffing tests in [DiffingTests_Prototypes ](https://github.com/BHoM/DiffingTests_Prototypes) when the NumericTolerance is set to a value different than the default, like in this PR: https://github.com/BHoM/Revit_Toolkit/pull/1200. The tests on the RevitParameters will fail because Double.Parse will be invoked on inputs that are not numbers.

#### Expected behaviour:

As above.

#### Test file(s):

As above.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #2807

### Test files

Run [DiffingTests_Prototypes](https://github.com/BHoM/DiffingTests_Prototypes). The tests on RevitParameters should work (with the latest commit https://github.com/BHoM/DiffingTests_Prototypes/commit/74934df94a913c053d5c5393c74f6f9d4a766aa6, all tests should work).

### CODE REVIEW

**Review by pawelbaran — APPROVED** [review]
Happy to approve, change makes sense to me and tests are passing.

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 6225065297

**Pull request merged**
