### PR TITLE
Structure_Engine: Replace calls to GetShallowClone with ShallowClone

### LINKED ISSUE #2201: Structure_Engine: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone
#### Broken rules:
See https://github.com/BHoM/admin/issues/9

#### Suggestions to restore compliance:
https://github.com/BHoM/admin/issues/9#issuecomment-709032648

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2201

See BHoM/admin#9

### Test files

Just compliance, should mean no functional change

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check all

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by al-fisher — APPROVED** [review]
This LGTM

**Pull request merged**
