### PR TITLE
Geometry_Engine: Add PointAtParameter for ellipse

### LINKED ISSUE #2936: Geometry_Engine: Add missing PointAtParameter for ellipse
#### Description:

Method is currently missing and quite straight forward to implement if parameter is seen as normalised angle domain. To be added

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2936

Add implementation of PointAtParameter for ellipse.

Implementation added does not correspond to normalised length along the curve but rather normalised angle along the curve, which for the case of an ellipse imo is a more sensical way of dealing with it.

Also adding Descriptions and null checking for all methods

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/ErnhG5n6ug5LkVRjjCCMZdkBKOiY6hE7Sz0UEKsxwgIUAw?e=Efi4Rd

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check unit-tests
@BHoMBot check null-handling

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check unit-tests
@BHoMBot check null-handling

**Review by pawelbaran — APPROVED** [review]
Happy to approve after code review and testing 👍

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check ready-to-merge

**Pull request merged**
