### PR TITLE
Humans_Engine: Compliance Updates

### LINKED ISSUE #1515: Humans_Engine - Compliance issues
This report has been generated as part of a close out for the 3.1 milestone compliance and outlines all of the compliance issues currently highlighted by the CI team. I will be undertaking this issue to resolve all compliance issues which do not impact scripts or versioning, with the remainder being moved to the 3.2 milestone for further discussion and resolution.

The following compliance issues have been found for this project. Please see the checklist below.
##### Incorrect Engine class name based on file path
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\Audience.cs at line 31, column 32 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\AvalueAnalysis.cs at line 40, column 32 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\AvalueSettings.cs at line 28, column 32 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\CvalueAnalysis.cs at line 35, column 32 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\CvalueFocalMethodEnum.cs at line 28, column 32 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\CvalueSettings.cs at line 31, column 32 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\EvalueAnalysis.cs at line 35, column 32 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\EvalueSettings.cs at line 31, column 32 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\EvalueViewEnum.cs at line 28, column 32 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\EyePositionParameters.cs at line 31, column 32 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\Spectator.cs at line 34, column 32 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\ViewCone.cs at line 34, column 32 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\ViewConeEnum.cs at line 28, column 32 

##### Input parameter should start with a lowercase letter
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\AvalueAnalysis.cs at line 188, column 126 

##### Input attribute should start with a lowercase letter
 - [ ] in BHoM_Engine\Humans_Engine\Create\PairOfEyes.cs at line 35, column 33 

##### Input attribute does not match any of the given parameters
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\AvalueAnalysis.cs at line 47, column 15 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\AvalueAnalysis.cs at line 57, column 15 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\CvalueFocalMethodEnum.cs at line 34, column 15 

##### Method name must match file name
 - [x] in BHoM_Engine\Humans_Engine\Query\Skeleton.cs at line 36, column 47 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\CvalueFocalMethodEnum.cs at line 36, column 44 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\EvalueViewEnum.cs at line 35, column 37 
 - [ ] in BHoM_Engine\Humans_Engine\ViewQuality\Spectator.cs at line 66, column 31 
 - [x] in BHoM_Engine\Humans_Engine\ViewQuality\ViewConeEnum.cs at line 35, column 35

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #1515 

### Test files
N/A

### Additional comments
The issue will be resolved by the changes made. Outstanding issues will be raised in 3.2 compliance reports as discussed.

Humans_Engine has a couple of outstanding compliance issues, with sub-methods and incorrect classes which will need addressing as part of a 3.2 discussion as there may be script breakages as a result.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
The compliance report has failed on punctuation which is deemed as acceptable for this current work and this PR can be merged, following successful review, with that problem on the report.

**Comment by IsakNaslundBh** [comment]
@rolyhudson would you please be able to review this, as this is only affecting your methods.

**Pull request merged**
