### PR TITLE
Facade_Engine: Create Facade Engine With Base Create Methods

### LINKED ISSUE #1950: Facade_Engine: Create Facade Engine
#### Description:
Facade engine is needed to work with Facade_oM, with a focus on methods related to Curtain Walls and Window Opening objects. This will include methods to add/modify mullion profiles, compute sections from facade objects for sectional analysis (ie THERM), etc.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #1950 

Added initial facade engine.

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check installer

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
Reasonable initial set up, LGTM.

**Pull request merged**
