### PR TITLE
Aligning with changes in BHoMAdapter Refactoring Level 04

### LINKED ISSUE #1374: Implement changes needed for Adapter refactoring Level04
#### Description:

- Add a `HashComparer` that can be used by the Adapter if no other Comparer is found.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #1374

### Changelog

- Added a `HashComparer` that can be used by the Adapter if no other Comparer is found.
- Tidy up of the Diffing_Engine as prompted by the addition of the HashComparer.

### CODE REVIEW

**Comment by alelom** [comment]
> Noticed while testing other parts of the refactoring that the error messaging was a bit off (not working).
You're right @kThorsager , this being due https://github.com/BHoM/BHoM_Engine/issues/1375 having been targeted separately. I'll now revert my changes related to that issue here.

**Comment by FraserGreenroyd** [comment]
This PR is being closed and manually fixed to allow merge party to go ahead. This PR is never to be merged (and thankfully won't be by GitHub). New PR coming.

**Comment by alelom** [comment]
New PR: https://github.com/BHoM/BHoM_Engine/pull/1430

**Pull request closed without merging**
