### PR TITLE
Update Copyright Header to 2021

### LINKED ISSUE #2252: Compliance of BHoM file Copyright Headers
All BHoM `.cs` files need to contain the current [BHoM copyright statement](https://github.com/BHoM/BHoM/blob/master/COPYRIGHT_HEADER.txt) as their header.

For more information see [Code Compliance - HasValidCopyright](https://github.com/BHoM/documentation/wiki/HasValidCopyright)

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #2252

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Review by FraserGreenroyd — DISMISSED** [review]
LGTM, would be good for at least one other review if possible.

**Review by adecler — CHANGES_REQUESTED** [review]
Tested programmatically with [this script](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/05_CI%20CD/TestCopyright.gh?csf=1&web=1&e=CLWa9r). Two files need fixing:

```
C:\Users\adecler\OneDrive - BuroHappold\Documents\GitHub\BHoM_Engine\Spatial_Engine\Compute\MapDomain.cs
C:\Users\adecler\OneDrive - BuroHappold\Documents\GitHub\BHoM_Engine\Spatial_Engine\Modify\MapPositionDomain.cs

```

Both have a double copyright header.


Also worth mentioning that the following file has been flagged up for having a double copyright:

```
C:\Users\adecler\OneDrive - BuroHappold\Documents\GitHub\BHoM_Engine\Serialiser_Engine\Objects\MemberMapConventions\ImmutableBHoMCreatorMapConvention.cs
```

One is ours, one is MongoDB Inc since this is a file we copied from them. So might be better not to add our copyright on that one.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Review by adecler — APPROVED** [review]
I reran the test and all looks good now

**Review by FraserGreenroyd — APPROVED** [review]
I have reviewed the test @adecler has been using and it looks robust so will give this PR another couple of hours for other reviews and then will merge by 12PM UTC.

**Pull request merged**
