### PR TITLE
Remove PreviousVersion attributes for previous milestones

### LINKED ISSUE #2429: Removal of PreviousVersion attributes
`PreviousVersion` attributes have been detected in this repo and should be removed for the start of the new milestone.

The following files have been identified to have outdated `PreviousVersion` attributes:

 - Data_Engine\Query\Requests.cs
 - Environment_Engine\Compute\ExtrudeToVolume.cs
 - Geometry_Engine\Compute\BooleanIntersection.cs
 - Geometry_Engine\Create\SettingOut\Grid.cs
 - Geometry_Engine\Query\LineIntersections.cs
 - Humans_Engine\Query\CvalueAnalysis.cs
 - Spatial_Engine\Compute\OrientationAngleLinear.cs
 - Spatial_Engine\Modify\RoundCoordinates.cs
 - Spatial_Engine\Query\IsPlanar.cs

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #2429

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed from a CI/CD perspective. Will await further reviews before merging.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by adecler — APPROVED** [review]
Looks good to me

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2248787785

**Pull request merged**
