### PR TITLE
Structure_Engine: NullReferenceException on transform of a bar with null nodes fixed

### LINKED ISSUE #3029: Structure_Engine: NullReferenceException on transform of a bar with null nodes
#### Description:

As in the title, issue identified while working on https://github.com/BHoM/Revit_Toolkit/pull/1328, with the following sequence of actions:
1. Convert a Revit Element to Bar without nodes (due to location extraction issue)
2. Call `Transform` to account for host <=> link shift
3. `Bar.Transform` calls `Node.Transform` to throw `NullReferenceException`

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3029

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FStructure%5FEngine%2F%233030%2DBarTransformBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### CODE REVIEW

**Review by IsakNaslundBh — APPROVED** [review]
Happy to approve.

Null handling and messages makes sense.

Happy for this to be merged to be included in 6.1 beta as a really low-risk PR only adding null-checking. Not required for 6.1 release, though, so can wait until 6.2 milestone if that is preferred by DevOps. @FraserGreenroyd

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
