### PR TITLE
Library_Engine: Handle nulls

### LINKED ISSUE #2483: Library Engine - handle nulls
For the following method:

 - [x] BH.Engine.Library.Convert.ToText(Source source)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2483

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check dataset-compliance

**Review by IsakNaslundBh — APPROVED** [review]
Reviewed on github. Code looks fine. SourceAndDisclaimer method calling this method is already filtering out nulls, so should not give any new unexpected error messages when that method is called.

Have not tested running on my machine, but feel this should be safe. Approved.

**Pull request merged**
