### PR TITLE
Matter_Engine: Make sure no hash fragments are stored in AggregateMaterialComposition

### LINKED ISSUE #3335: Matter_Engine: AggregateMaterialComposition is leaving hashes on materials
#### Description:

https://github.com/BHoM/BHoM_Engine/blob/57f9eb731191d3ed7ff07946b27148634601e449/Matter_Engine/Compute/AggregateMaterialComposition.cs#L104

is not functioning fully as intended, as the method is deep cloning the incoming object, and hence leaving the hash. Need to set the returned obejct to the list rather than just looping through the list.

#### Steps to reproduce:

Run method with any two material compositions.

#### Expected behaviour:

For no has to be present on the output materials in the material composition.

### LINKED ISSUE #3336: Matter_Engine: Aggregate methods to ignore BHoM_Guid by default when comparing materials
#### Description:

The Base comparison config used to ignore the BHoM_Guid by default. This was however changed back in https://github.com/BHoM/BHoM/pull/1330 . Was unaware of the change then, but should make sure that this behaviour is reset, as currently a lot of duplicate materials are added to the compositions and takeoffs where only the Guid is the difference.

#### Steps to reproduce:

Run an Aggregate method for any takeoff/composition where there are any duplicate materials that are identical but created separately (giving them different BHoM_Guids.

#### Expected behaviour:

For BHoM_Guid to be ignored by default. A user could input a comparison config to change the behaviour. For this, also should include the config as input for the AggregateMaterialComposition method.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #3335 

Change the way the AggregateMaterialComposition method works to align with the counterparts for the takeoffs.

Previous version led to revision fragments being stuck on the material, causing issues later on. It for example lead to continuous calls to other aggregation method to give different hashes.

### Test files

[here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Matter_Engine/%233337-DefaultToIgnoreBHoM_GuidForAggregateMethods?csf=1&web=1&e=s2jqGl)

### CODE REVIEW

**Review by alelom — APPROVED** [review]
Code changes make sense, test script works.

image

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
Dispensating UTs as non of the failing ones are related to this PR

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
