### PR TITLE
Analytical_Engine + Graphics_Engine: Project graph to dependency diagram.

### LINKED ISSUE #2144: Analytic_Engine: add methods to support work flows for non-spatial views of Graphs
#### Description:
See https://github.com/BHoM/BHoM/issues/1079 for description of non-spatial views of graphs.

Add methods required to handle layout generation as described in the issue above.
Add functionality to the existing `GraphView` method to filter entities and relations with `ProcessViewFragments` (remove entities without that fragment and any dependent relation).

### PR DESCRIPTION
**Pull request by rolyhudson**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1109

   
### Issues addressed by this PR

Closes #2144 

### Test files
Require MSBuild_Toolkit
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FAnalytical%5FEngine%2FIssues%2F%231079NonSpatialGraph&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4

### CODE REVIEW

**Comment by rolyhudson** [comment]
@al-fisher + @alelom just to note that the stuff we looked at this morning is here. @al-fisher the file IElementDependencies.gh is now in the SS folder of the test files folder in case it is needed for reference.

**Comment by al-fisher** [comment]
Thanks @rolyhudson

**Review by al-fisher — COMMENTED** [review]
This is looking really good. Can see this scaling well.

I do have a couple of thoughts around conventions and the precise flow of information.
Namely the role/split of responsibility between the `View`, the `Projection` and the act of `Projecting` method.

image

What is the requirement of the intermediate layer of the `GraphicalProjection` - could `Views` or similar not be fed directly into the `IProjectGraph` method itself. Is this to help manage dependency between `Analytical` and `Graphical` ?
There are multiple layers of terminology here which will be nice to clarify and even simplify if we can.

Functionality wise - I do really like the way it is working - along with the various `RepresentationFragments`.

**Review by al-fisher — APPROVED** [review]
As discussed @rolyhudson - raised issue here https://github.com/BHoM/BHoM/issues/1120

Very happy this PR creates the functionality we need to continue to prototype out and start using. Any potential name changes can be actioned at later date.

Happy to approve to merge and continue experimentation

**Review by al-fisher — APPROVED** [review]
Reapproving inline with https://github.com/BHoM/BHoM/pull/1109
LGTM

**Pull request merged**
