### PR TITLE
Physical_Engine: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone

### LINKED ISSUE #2167: Physical_Engine: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone
#### Broken rules:
See https://github.com/BHoM/admin/issues/9

#### Suggestions to restore compliance:
https://github.com/BHoM/admin/issues/9#issuecomment-709032648

### PR DESCRIPTION
**Pull request by al-fisher**
### Issues addressed by this PR

Closes #2167

See BHoM/admin#9

### CODE REVIEW

**Comment by al-fisher** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by al-fisher** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by al-fisher** [comment]
@BHoMBot check compliance

**Comment by al-fisher** [comment]
@BHoMBot fix documentation punctuation ref. 1413606268

**Review by adecler — APPROVED** [review]
LGTM

**Pull request merged**
