### PR TITLE
Matter_Engine: Improve Density Management for Physical materials

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1443
   
### Issues addressed by this PR

- Align with Density added to Material
- Add methods for extracting Density from a set of IDensityProviders
- Add method to set density to a material based on its Properties
- Update Material Create methods to scan Properties used to create for Density

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Eg7Y5NfGykJKr5Bc1wfki6ABOXhTCqmW-pr3oNrYvFzKYA?e=tJxtni

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check null-handling
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
Have investigated the failing UTs for VolumetricMaterialTakeoff and MaterialComposition and both boils down to the same reason for the failure. Both failing cases are that the density is set to 7850 when run on this branch, while on main the non-existing value returned is 0:

image

Creating a composition or takeoff straight from a structural material it is valid to pass the density to the physical material, hence the change in behaviour is expected and an improvement.

Will for those reasons regenerate those UTs to what is returned on this branch.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core

**Review by al-fisher — APPROVED** [review]
Approving based on review and commentary in oM PR - see https://github.com/BHoM/BHoM/pull/1443

**Comment by al-fisher** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
