### PR TITLE
Geometry_Engine: Addition of Query.Volume methods for ISolids

### LINKED ISSUE #2046: Geometry_Engine: Addition of Query.Volume() methods for ISolids
#### Description:

Following https://github.com/BHoM/BHoM/issues/1016 - this can be exposed additonally here, but along with new methods or all other `BH.oM.Geometry.ISolids` based on analytical solutions

### PR DESCRIPTION
**Pull request by al-fisher**
### Issues addressed by this PR

Closes #2046 

### Test files

See test file here:
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometryEngine%2D%232046%2DVolumeQueryForISolids&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4

### Changelog

- Volume for BoundaryRepresentation is a straight exposure of the Get only Volume Property stored on the object and set at conversion
- All other ISolid volumes are derived from the analytical formulae comprised from defining properties.

### CODE REVIEW

**Comment by al-fisher** [comment]
@michaelhoehn FYI - this completes, I think, the geometrical foundations for your latest LCA work. 
Speak later on all things related in any case 😄

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
Have not tested, but formulas look correct!

Some small things I might comment on:

1. I have generally been putting the interface method at the bottom of the file. This is not consistent across all engine files, but I think it is the most common place for them. Would not block for this, but think we need to agree on a consistent convention for this.
2. We should add a fallbackmethod, a private method `Volume(ISolid solid)` that raises an error message and returns double.NaN. Similar to what has been done to the `Length` methods for curves in this engine. This I think we should get in!

**Comment by al-fisher** [comment]
Thanks @IsakNaslundBh 
Both good comments - will address 

On this
> I have generally been putting the interface method at the bottom of the file. 

Agree actually - think this is the better convention. 👍

**Review by michaelhoehn — APPROVED** [review]
Tested and works great!

**Review by IsakNaslundBh — APPROVED** [review]
Code now looks good, and relying on @michaelhoehn s test of functionality!

**Pull request merged**
