### PR TITLE
Spatial_Engine: Add option to centre FreeFormProfiles

### LINKED ISSUE #2209: Spatial_Engine: Add option to create free form profiles without centering the profile
#### Description:
Currently, profiles are automatically centered around the origin, prohibiting eccentric profile creation which is required for some workflows.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2209

Add option to control if the freeform profiles should be centre or not. Important for Facade workflows.

### Test files

Please test any script using freefrom profiles @enarhi

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Review by enarhi — APPROVED** [review]
LGTM!

**Review by pawelbaran — APPROVED** [review]
Tested and looked through the code, LGTM 👍

**Pull request merged**
