### PR TITLE
Geometry_Engine: BooleanDifference secured against single-dimensional regions

### LINKED ISSUE #3368: Geometry_Engine: BooleanDifference fails if one of the curves is singular
#### Description:

If one of curves involved in `BooleanDifference` is singular in regards to plane creation (i.e. all points are collinear), the method fails with `NullReferenceException` due to the fact that plane can't be created.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3368

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%233369%2DNullReferenceInBooleanOperations).

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Review by peterjamesnugent — APPROVED** [review]
No longer causing the error reported in the issue. Unit tests are passing (based on script - bot is still running).

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
Using similar approach as in https://github.com/BHoM/BHoM_Engine/pull/3364, I can confirm that result of `unit-tests` check in this PR [here](https://github.com/BHoM/BHoM_Engine/pull/3369/checks?check_run_id=27077776498) are the same as in other branches (e.g. [here](https://github.com/BHoM/BHoM_Engine/pull/3364/checks?check_run_id=26892311972)), so by deduction, this PR does not introduce any UT failures.

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 27077776498

**Comment by pawelbaran** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
