### PR TITLE
Ground_Engine, BHoM_Engine: Add UnitTests for ConsolidateStrata, remove UTs for GeometryHash

### LINKED ISSUE #3382: BHoM_Engine: Remove defunct unit tests
#### Broken rules:

[Remove unit tests for `GeometryHash as those methods have been completely reworked.](https://github.com/BHoM/BHoM_Engine/pull/3356/checks?check_run_id=26098905537)

#### Suggestions to restore compliance:

Remove unit tests for `GeometryHash as those methods have been completely reworked.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #3377 
Closes #3382 

### Test files

https://burohappold.sharepoint.com/:u:/s/BHoM/EfuNrrGbo51BoKd5CUBw1agBW86KkaYx17ZTBNp2-V3Beg?e=rMcf8E

### Changelog

- Added unit tests for `ConsolidateStrata` method;
- Removed unit tests for `GeometryHash` as the method was completey reworked;.

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Review by pawelbaran — APPROVED** [review]
Approving on the basis of the following:
- tests for `ConsolidateStrata` are greenfield
- `GeometryHash` method has been reworked and is well covered in https://github.com/BHoM/DiffingTests_Prototypes, as discussed with @alelom

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 27950483319

**Comment by pawelbaran** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
