### PR TITLE
Serialiser_Engine: Get all UI components to create and copy without error

### LINKED ISSUE #2293: Serialiser_Engine: Make sure all UI components can be create from global menu and copied/pasted without error
#### Broken rules:
Some UI components fail to create themselves from the global menu or become invalid once copy/pasted (or saved/reloaded)

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #2293 

This PR fixes the components that 
- were not creating correctly when selected from the global menu (they would usually appear without inputs nor outputs)
- would be invalid once copy/pasted (usually they would give a warning about needing to select an item)

There are a few components that still not working but this is due to non-compliant code. I have raised separate issues for those:
- https://github.com/BuroHappoldEngineering/SharePoint_Toolkit/issues/102
- https://github.com/BHoM/BHoM_Adapter/issues/284

### Test files
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Serialiser_Engine/%232293-AllComponentsCreateAndCopiedWithoutError?csf=1&web=1&e=Tdhk0w

### Additional comments
@FraserGreenroyd , the XML components failing to copy/paste correctly were due to a missing default value for the `FragmentSet` property of `EnergyPlusObject`. See [here](https://github.com/BHoM/XML_Toolkit/blob/98e2e7caa6f122a74ef5228fe1ccfa5b18492cb6/XML_oM/EnergyPlus/EnergyPlusObject.cs).

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check installer

**Review by rolyhudson — APPROVED** [review]
Reviewed and approved based on running of test script with expected outcomes. 
Components showing as problematic after running script are already noted in the issues below.
- https://github.com/BuroHappoldEngineering/SharePoint_Toolkit/issues/102
- https://github.com/BHoM/BHoM_Adapter/issues/284

**Pull request merged**
