### PR TITLE
Environment_Engine: Fix bug in Tidy Panels duplicating floor/ceiling panels

### LINKED ISSUE #2916: Environment_Engine: Tidy Panels duplicates floors and ceilings
#### Description:

When using `TidyPanels` with the toggle option of `autoFixPanelOrientations` set to true (as is the default) floor and ceiling panels become duplicated in the output. This causes issues with pushing to environmental software such as IES Toolkit.

#### Steps to reproduce:

 - Create a single space of panels (easiest done by polyline of a simple rectangle in plan -> space perimeter -> extrude to volume, get 6 panels for the space)
 - Plug panels into `TidyPanels` - ensure `autoFixPanelOrientations` is set to true
 - See that 8 panels are returned - only 6 should be

#### Expected behaviour:

Ceiling and floor panels should not be duplicated. For the example above, only 6 panels should be returned.

#### Test file(s):

[TidyPanelsBug.zip](https://github.com/BHoM/BHoM_Engine/files/9660005/TidyPanelsBug.zip)

FYI: @rboulton-BH @charliebrookerBH @MarthaVoul

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2916 

### Test files
See issue

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by kprusicka — APPROVED** [review]

**Review by EKAdebo — APPROVED** [review]
I approve it's all good here. I looked at this very very closely.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: dataset-compliance

**Pull request merged**
