### PR TITLE
Structure_Engine: rename DOF f to o

### LINKED ISSUE #2610: Free constraints from Robot tyranny
#### Description:

in the description for DOF fixity, we use robot terminology of 'f' = free and 'x' = fixed, however this is not universal among FE softwares, and is, in my opinion, somewhat un-intuitive as both fixed and free begin with 'f'. Rather, we should use 'x' and 'o'; these two have a number of possible mnemonics, in that they look like checkboxes, that x is fiXed and o is Open, etc. Side benefit, all our constraints will appear very affectionate.

xoxo,
Joe

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #2610

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by IsakNaslundBh — APPROVED** [review]
I like this, think it helps with the ambiguity of the "f"! 

- [ ] o
- [x] x

**Review by al-fisher — COMMENTED** [review]
Agreed - is neat I think

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
