### PR TITLE
Structure_Engine: Updating FramingELementProperties to handle non-linebased centreliens

### LINKED ISSUE #802: Structure_Engine: Update AnalyticalBar method for framing element to handle non-Linebased obejcts
Align with changes made in:

https://github.com/BHoM/BHoM/issues/331

Additional method need to be added for non-linebased elements such as arc.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #802 

- Adding new Create method for FramingELement accepting ICurve isntead of just Line
- Deprecating old Create method for FramingElement
- Adding description for Create method for ConstantFramingElementProperty and taking name from SectionProperty if no name is provided
- Updating AnalyticalBars method to handle non-linear elements

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Structure_Engine/Structure_Engine-Issue802-UpdateFramingElementMethods?csf=1&e=CfEsTr

### CODE REVIEW

**Comment by alelom** [comment]
Tested here as well, works. 
Regarding the intentional error message here:
image

what do you think of adding something more to the error, to be more explicative? Something like "split the nurbs curve and use a polyline instead".

**Comment by IsakNaslundBh** [comment]
Comment updated. This is now not compiling to master BHoM as the Env_Engine has been updated, but should be fine to get it merged on top as does. I have tested it on an old local branch I had on my computer.

image


Message updated to:

"1. The analytical bars method is currently not supported for NurbsCurves. Please use another method to split up the nurbs to polylines that can be used to construct the bars."

Are any of the two of you fine with approving this?

**Comment by IsakNaslundBh** [comment]
Also, @FraserGreenroyd would you mind having a 2min glance to make sure this is not interfering with any changes you have made in the engine (it should not)

**Comment by FraserGreenroyd** [comment]
@IsakNaslundBh I've looked at the files you've changed - all based on Structure_Engine 3 files changed so happy that this does not interfere with what I've previously done :smile: hope that helps!

**Comment by alelom** [comment]
Looks good, much clearer now. Thanks!

**Comment by al-fisher** [comment]
Thanks @IsakNaslundBh @alelom

**Pull request merged**
