### PR TITLE
Geometry_Engine: UTs refreshed and Boolean operations bugfixed

### LINKED ISSUE #3277: Geometry_Engine: Update unit tests for methods modified in 7.1
#### Broken rules:

Unit tests need updating for the methods modified in this PR:
https://github.com/BHoM/BHoM_Engine/pull/3275

#### Suggestions to restore compliance:

Create unit tests

### LINKED ISSUE #3318: Geometry_Engine: BooleanDifference yields wrong results for disjoint, collinear lines
#### Description:

As in the title, found while refreshing the UTs following the recent changes.

### LINKED ISSUE #3320: Geometry_Engine: BooleanDifference(List<Line>, List<Line>) and BooleanIntersection(List<Line>, List<Line>) modify input collections
#### Description:

As in the title, happens due to `refLines` being processed instead of `refLeft`:

https://github.com/BHoM/BHoM_Engine/blob/5bcc6bb1f991e2f004f43bff40c7f5fe86399297/Geometry_Engine/Compute/BooleanIntersection.cs#L111-L121

https://github.com/BHoM/BHoM_Engine/blob/5bcc6bb1f991e2f004f43bff40c7f5fe86399297/Geometry_Engine/Compute/BooleanDifference.cs#L66-L74

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3277
Closes #3318
Closes #3320

### Test files

All tests serialised in this PR are scripted in GH and uploaded [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&isAscending=false&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%233319%2DGeometryUTs&sortField=LinkFilename&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b)

### Additional comments

UTs cover the following PRs from 7.1:
https://github.com/BHoM/BHoM_Engine/pull/3275
https://github.com/BHoM/BHoM_Engine/pull/3280
https://github.com/BHoM/BHoM_Engine/pull/3283
https://github.com/BHoM/BHoM_Engine/pull/3290
https://github.com/BHoM/BHoM_Engine/pull/3292
https://github.com/BHoM/BHoM_Engine/pull/3293
https://github.com/BHoM/BHoM_Engine/pull/3298

### CODE REVIEW

**Review by peterjamesnugent — APPROVED** [review]
Happy that none of the unit tests (existing and newly added) are failing using `FilterByCheckStatus`. 

Happy that the bug for colinear lines are fixed for `BooleanDifference` and modification of inputs is fixed for `BooleanDifference` and `BooleanIntersection`.

I did notice in the description the use of underscores, could remove that in a seperate PR or this one:
https://github.com/BHoM/BHoM_Engine/blob/5bcc6bb1f991e2f004f43bff40c7f5fe86399297/Geometry_Engine/Compute/BooleanDifference.cs#L40

**Comment by pawelbaran** [comment]
Thanks @peterjamesnugent - I tweaked the descriptions now as the bot checks have not been run yet 👍

**Review by peterjamesnugent — APPROVED** [review]
Only changes to the descriptions, functionality not affected (and therefore previous review still valid).

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: dataset-compliance

**Pull request merged**
