### PR TITLE
Analytical_Engine: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone

### LINKED ISSUE #2167: Physical_Engine: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone
#### Broken rules:
See https://github.com/BHoM/admin/issues/9

#### Suggestions to restore compliance:
https://github.com/BHoM/admin/issues/9#issuecomment-709032648

### PR DESCRIPTION
**Pull request by al-fisher**
### Issues addressed by this PR

Closes #2167

See BHoM/admin#9

### Changelog

Note that the behaviour of `SetGeometry` and `SetOutlineElements1D` has now been updated to no longer update Guid in line with compliance and our strategy for persistency of the BHoM_Guids 

### Additional comments

Noting @rolyhudson - your PR on Analytical Engine here https://github.com/BHoM/BHoM_Engine/pull/2145 - but touching different files.

### CODE REVIEW

**Comment by al-fisher** [comment]
@BHoMBot check all

**Review by adecler — COMMENTED** [review]
I wonder if we shouldn't stop requesting a change of Guid (bool input set to true) already in this PR.

**Comment by al-fisher** [comment]
Thanks @adecler - you are right! I missed that

We will naturally be removing the option from the method signature in the base method right?

``` C#
BH.Engine.Base.Query.ShallowClone<T>(this T obj, bool newGuid = false) 

```

Worth checking others have not missed that as I have in the quick clean up!

**Comment by adecler** [comment]
> We will naturally be removing the option from the method signature in the base method right?

Yes

> Worth checking others have not missed that as I have in the quick clean up!

I had checked the other PR you did this morning but will have a look at the other ones

**Comment by adecler** [comment]
I have now checked all the PRs that have been merged already. Only two are still using the bool input:
- https://github.com/BHoM/BHoM_Engine/pull/2130
- https://github.com/BHoM/BHoM_Engine/pull/2131

Conveniently both from @FraserGreenroyd 😄

**Comment by al-fisher** [comment]
Thanks @adecler

**Review by FraserGreenroyd — APPROVED** [review]
Code changes LGTM :smile:

**Comment by al-fisher** [comment]
Thanks @FraserGreenroyd

**Pull request merged**
