### PR TITLE
Geometry Engine: Fix method name spelling

### LINKED ISSUE #3164: Geometry_Engine: SignedAngle method name incorrect
#### Description:

https://github.com/BHoM/BHoM_Engine/blob/f301ec1d496b6411b0a874dec29ea4812c5c9d37/Geometry_Engine/Query/Angle.cs#L110

#### Steps to reproduce:

See above.

#### Expected behaviour:

Rename method to `SignedAngle.`

### PR DESCRIPTION
**Pull request by albinber**
### Issues addressed by this PR

Closes #3164

### CODE REVIEW

**Comment by albinber** [comment]
@bhombot check compliance
@bhombot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 16413622442

**Review by FraserGreenroyd — APPROVED** [review]
Spelling is updated, great work @albinber 😄

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests, ready-to-merge

**Pull request merged**
