### PR TITLE
Structure_Engine: Align with removal of deprecated reinforcement objects

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1581

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check installer
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling

**Review by Tom-Kingstone — APPROVED** [review]
Approving based off linked PR, as `Reinforcement` objects have been removed (deprecated since 3.2)

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Review by peterjamesnugent — APPROVED** [review]
Happy that checks have passed and no other repos are affected. All methods being removed are either deprecated or no longer required due to objects removed from the oM.

**Pull request merged**
