### PR TITLE
Humans_Engine: Fix CValue variable use

### LINKED ISSUE #2878: Humans_Engine: Correct CValue output
https://github.com/BHoM/BHoM_Engine/blob/bdde55560efd5460930a858b4a5c1c9392f893e0/Humans_Engine/Query/CvalueAnalysis.cs#L155

The change to this code means that using a default CValue does not work, because the variable being assigned to the result is the input `cvalue` rather than the calculated (via if statement) `cValue` - the variable we should use has a capital V in it but the one being used doesn't.

FYI @IsakNaslundBh

### PR DESCRIPTION
**Pull request by agneslindblom**
### Issues addressed by this PR
Fixes #2878

### CODE REVIEW

**Comment by agneslindblom** [comment]
@BHoMBot check required

**Comment by agneslindblom** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Review by FraserGreenroyd — APPROVED** [review]
Code change is logical based on history of changes to this file. Reviewed/tested through with @agneslindblom on their project.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Pull request merged**
