### PR TITLE
Environment_Engine: Add opening creation from configuration options

### LINKED ISSUE #2362: Environment_Engine: Openings from design options
Implement functionality referenced [here](https://github.com/BHoM/BHoM/issues/1210)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1213

   
### Issues addressed by this PR
Fixes #2362 

### Test files
[Available here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Environment_oM/%231213-OpeningConfigurations/OpeningConfigurations.gh?csf=1&web=1&e=IUp0Gv)

Unit tests added based on this test file.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by michaelhoehn — APPROVED** [review]
Tested and LGTM!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Pull request merged**
