### PR TITLE
Geometry_Engine: Add unit tests based on method usage analytics

### LINKED ISSUE #2413: Geometry_Engine: Unit tests based on usage analytics.
#### Definition of the test :
Create the next batch of Geometry Engine unit tests based on the usage based priority list [here](https://github.com/BHoM/BHoM/discussions/1148#discussioncomment-359855). Focusing on Query, Modify, Compute methods first.

### PR DESCRIPTION
**Pull request by rolyhudson**
### Issues addressed by this PR
More Geometry unit tests
Note this is a redo of the stale and closed #2414. No changes have been made to the datasets.
Closes #2413 

### Test files
Creation scripts [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Geometry_Engine/%232414-UnitTestsFromUsage?csf=1&web=1&e=ieyDPf)

### CODE REVIEW

**Comment by rolyhudson** [comment]
@FraserGreenroyd added you only for continuity of the stale previous version of this. No review of the creation scripts is expected from you 😄

**Comment by rolyhudson** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed per previous PR that could not rebase.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
