### PR TITLE
Serialiser_Engine: fix for MessageForDeleted to be picked up for properties of types that have multiple matching types

### LINKED ISSUE #3370: Serialiser_Engine: MessageForDeleted is not picked up for properties of types that have multiple matching types
#### Description:

Edge case of an edge case reported under https://github.com/BHoM/BHoM_Engine/issues/3343 - if a property is removed with `MessageForDeleted`, its parent type will version correctly only if there is exactly one matching type for it.

However, it may happen that there is more than one assembly containing that particular type (which currently happens only with Revit stuff, where we have version-specific assemblies), and then the type is not found, leading to the object being deserialised to `CustomObject`.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3370

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by adecler — COMMENTED** [review]
Thanks @pawelbaran ,

The change makes sense. As discussed, I would just add a warning message for the case where multiple matching types where found to still provide good traceability: 
image

**Comment by pawelbaran** [comment]
Thanks @adecler for the review, I have now addressed the comment 👍

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by adecler — APPROVED** [review]
The corrections are matching the request change so happy to approve.

As a side note, the if-else sequence is a bit weird here. After ruling out `count == 1`, there is still a check for `count > 1` but only when `takeFirstIfMultiple` is true. The final case, will just assume there is more than one type. This is correct since the access to the `BHoMTypeDictionary` would have returned false if not types were found. So no bug or error and it was like that before this PR, just a little confusing. So still happy to approve.

**Comment by pawelbaran** [comment]
@BHoMBot check code-compliance
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
I will dispensate the failing unit test check on the basis of the fact that it has been failing consistently for a longer period of time, as can be seen [here](https://github.com/BHoM/BHoM_Engine/pull/3364/checks?check_run_id=26892311972) or [here](https://github.com/BHoM/BHoM_Engine/pull/3369/checks?check_run_id=27077776498) - each time the failure message is exactly the same.

**Pull request merged**
