### PR TITLE
 Facade_Engine: Added Methods to calculate UValues on elements based on new U and Psi fragments 

### LINKED ISSUE #2508: Facade_Engine: Calculation Methods to translate section-specific U-Values to Effective Area U-Values
#### Description:
These methods are a critical step in the thermal analysis process as we translate singular section studies (THERM, BISCO, etc) to effective facade thermal performance over distinct areas. The methods will include:

- Calculation of tributary areas for each FrameEdge representing the area that its U-Value applies to the opening it is on
- Compositing of all frame edges and their tributary areas into effective ratios that each frame edge U-Value contributes to the overall Opening U-Value
- Translation of multiple element U-Values across a selected area / collection of elements into a single overall U-Value
- Pulling of result data from database for a specified frame edge with adjacency, ie "Kawneer 1600 W/ Triple IGU...."

### PR DESCRIPTION
**Pull request by enarhi**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1251
   
### Issues addressed by this PR

Closes #2508 

This PR adds methods for calculating effective UValue of one or many openings based on their constituent frame and glazing U values using two common methods: Single Assessment Method and Component Assessment Method.

### Test files
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%232508-UValueCalculationMethods?csf=1&web=1&e=D8xviw

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check compliance
check null-handling

**Comment by enarhi** [comment]
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check ready-to-merge

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check null-handling

**Comment by enarhi** [comment]
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check serialisation

**Comment by enarhi** [comment]
@FraserGreenroyd regarding null-handling I have confirmed the increases in errors in unrelated to this branch (no errors returned for any methods in the BH.Engine.Facade namespace) and results from later merged pr's that reduce null handling errors.

**Comment by enarhi** [comment]
@BHoMBot check versioning

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check ready-to-merge

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Review by michaelhoehn — APPROVED** [review]
Approved from a functionality standpoint. All methods and fragments work as expected as proven in the sample file. LGTM!

**Comment by enarhi** [comment]
@BHoMBot  check ready-to-merge

**Comment by enarhi** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2805928334

**Pull request merged**
