### PR TITLE
Environment_Engine: Changing note wording

### LINKED ISSUE #2789: Environment_Engine: AssignGenericConstructions note wording
At the moment, AssignGenericConstrucitons(Opening opening) assigns a generic_window construction for any opening without an OpeningConstruction. Given the range of OpeningTypes this can be applied to (e.g. Doors, which are arguably more likely to be considered to be made of timber in the generic case) it may not always be obvious that the generic construction applied will always be one of a double-glazed window. 

#### Broken rules:
Currently, the generic message returned is `"The construction for the opening with GUID {0} was automatically assigned a generic construction"`

#### Suggestions to restore compliance:
This message should be updated to `"The construction for the opening with GUID {0} was automatically assigned a generic window construction."`

In the longer term, the database of generic opening constructions should be expanded, but this is beyond the scope of this issue.

### PR DESCRIPTION
**Pull request by albinber**
### Issues addressed by this PR

Closes #2789

### CODE REVIEW

**Comment by albinber** [comment]
@bhombot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
Wording updated per issue, happy to approve on code review.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Pull request merged**
