### PR TITLE
Geometry_Engine: nurbs curve and surface parameter normalized

### LINKED ISSUE #2228: Geometry_Engine: xxAtParameter methods for NurbsCurve use global parameter instead of a normalized one
#### Description:

As in the title - it is inconsistent compared to other curve types (all working on normalized parameter), good to unify before the Beta release as it is a new feature.

@al-fisher @IsakNaslundBh @LMarkowski FYI

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #2228

### Test files

Original files from #2028 uploaded on SharePoint:
- [curve](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%232228%2DNurbsCurveParam%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine)
- [surface](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%232228%2DNurbsSurfaceParam%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine)

### Changelog

- input for nurbs curve query methods changed from global parameter value to normalized one
- input for nurbs surface query methods changed from global parameter value to normalized one
- descriptions updated to reflect the change

### CODE REVIEW

**Comment by pawelbaran** [comment]
WIP label added after @IsakNaslundBh's fair comment on the surface queries being affected by this PR too.

**Comment by pawelbaran** [comment]
I have updated the PR to cover nurbs surfaces too, all `xxAtParameter` queries should work with normalised parameter value (between 0 and 1) now, the PR is ready for review. As discussed with @IsakNaslundBh, in the next milestone it could be worth adding a `bool` method parameter allowing to switch between global and normalised param value.

**Review by LMarkowski — DISMISSED** [review]
I like the taken approach and adding the boolean argument later. Methods work fine and code looks good to me. 👍 

It also seems to me like a good occasion to add the cases for nurbs to the regular test files for changed methods if we are willing to keep those tests.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Would like the compliance issues (only 2 of them) resolved for this PR please. Happy to merge after that based on @LMarkowski review

**Comment by pawelbaran** [comment]
I would argue whether the compliance report is right in this case @FraserGreenroyd (please see the code changes), but the fix has been pushed.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
LGTM now, thanks @pawelbaran

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Pull request merged**
