### PR TITLE
BHoM_Engine: fix for `Hash()` not dealing correctly with Enum types 

### LINKED ISSUE #2714: BHoM_Engine: `Hash()` not dealing correctly with Enum types
#### Description:

When Hash() receives an enum, if the ComparisonConfig had some numeric setting set, then it triggers approximation functions, which should not happen.

#### Steps to reproduce:

Feed an object containing an enum type, and `ComparisonConfig` with some numeric setting set (e.g. a NumericTolerance different from the default value),to Hash(). An exception will be thrown.

#### Expected behaviour:

Approximation functions should not be called, exception should not be thrown.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #2714

### Test files

@FraserGreenroyd can you fill this in with your script?

Edit from @FraserGreenroyd :
@jamesramsden-bh and myself will be using the `XML_Toolkit_Push_Model.gh` file available [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FXML%5FToolkit&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b) in line with the test procedure [here](https://burohappold.sharepoint.com/:w:/r/sites/BHoM/01_Master%20File/09_QAQC/04%20-%20Testing%20Procedures/0005_Environment/0001_XML_Toolkit.docx?d=w05e62d00b2c74e24a778fbed2cf33771&csf=1&web=1&e=qRBtNJ).

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@alelom I have edited in some test script information :smile:

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by jamesramsden-bh — APPROVED** [review]
I have some issues with the XML toolkit, captured in the testing report. However, none of these appear to be related to diffing, so I am happy for the diffing fix to be merged.

**Review by FraserGreenroyd — APPROVED** [review]
This worked fine on my tests so happy to merge in for more general testing.

**Pull request merged**
