### PR TITLE
Facade_Engine: Add MaterialCompostion and SolidVolumes functionality

### LINKED ISSUE #2303: Facade_Engine: Add SolidVolume and MaterialComposition methods
#### Description:
These methods will be critical to facades workflows, and will allow us to extract material quantities of many materials across a mullion extrusion and glazing construction.

### PR DESCRIPTION
**Pull request by enarhi**
Depends on BHoM/BHoM/pull/1205 for full functionality, but non-breaking for build etc.

### Issues addressed by this PR

Closes #2303

Added the ability to get solid volumes and material compositions from facade objects to enable downstream workflows such as LCA on these objects.

### Test files
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%232303-SolidVolumesAndMaterialCompositions?csf=1&web=1&e=gq5Zjn

Bottom portion of test script covers this PR.

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check core

**Review by michaelhoehn — APPROVED** [review]
This LGTM. Tested and seems functional. Welcome to the IElementM club 😄

**Comment by enarhi** [comment]
@BHoMBot check installer

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
