### PR TITLE
Graphics_Engine: Handle nulls

### LINKED ISSUE #2479: Graphics Engine - handle nulls
For the following methods:

 - [x] BH.Engine.Graphics.Convert.ToRenderMesh(Mesh mesh)
 - [x] BH.Engine.Graphics.Convert.ToSVGString(SVGStyle svgStyle)
 - [x] BH.Engine.Graphics.Convert.ToSVGString(SVGObject svgObject)
 - [x] BH.Engine.Graphics.Convert.ToSVGString(SVGDocument svgDocument)
 - [x] BH.Engine.Graphics.Convert.ToSVGString(Point point)
 - [x] BH.Engine.Graphics.Convert.ToSVGString(Line line)
 - [x] BH.Engine.Graphics.Convert.ToSVGString(Circle circle)
 - [x] BH.Engine.Graphics.Convert.ToSVGString(Arc arc)
 - [x] BH.Engine.Graphics.Convert.ToSVGString(Ellipse ellipse)
 - [x] BH.Engine.Graphics.Convert.ToSVGString(Polyline polyline)
 - [x] BH.Engine.Graphics.Convert.ToSVGString(NurbsCurve nurbCurve)
 - [x] BH.oM.Geometry.ICurve.Marker(IMarker marker, Point end, Vector direction)
 - [x] BH.oM.Geometry.ICurve.Marker(BasicArrowMarker marker, Point end, Vector direction)
 - [x] BH.Engine.Graphics.Modify.RepresentationFragment(Boxes component, Dataset dataset, ViewConfig viewConfig)
 - [x] BH.Engine.Graphics.Modify.View(IView view, Dataset dataset)
 - [x] BH.Engine.Graphics.Modify.View(DependencyChart view, Dataset dataset)
 - [x] BH.Engine.Graphics.Query.Color(Gradient gradient, Double val)
 - [x] BH.Engine.Graphics.Query.Color(Gradient gradient, Double val, Double from, Double to)
 - [x] BH.Engine.Graphics.Query.Bounds(SVGObject svg)
 - [x] BH.Engine.Graphics.Query.Bounds(SVGDocument svg)
 - [x] BH.Engine.Graphics.Query.IsNumericType(Object o)
 - [x] BH.Engine.Graphics.Scales.Query.Scale(ScaleLinear scale, Object value)
 - [x] BH.Engine.Graphics.Scales.Query.Scale(ScaleOrdinal scale, Object value)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2479

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by michaelhoehn — APPROVED** [review]
LGTM

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2366360272

**Pull request merged**
