### PR TITLE
Library_Engine: Re-serialisation of SteelSections

### LINKED ISSUE #606: Library_Engine: Some section curves for some section properties are serialised wrong
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #606

Updating all of the Serialised section data to have section curves centralised around the origin.

Re-adding previously working Assymetric sections.

### Test files

Test file for comparing two libraries is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FLibrary%20Engine%2FIssue606-Compare%20Libraries).

**N.B. TO TEST AGAINST OLD LIBRARY, DO THIS BEFORE BUILDING TO THIS BRANCH!** To reset- switch to master and build.

To test against the old library:

1. Copy the old "SectionProperties" folder in the datasets folder in the BHoM appdata folder. and rename it to SectionProperties_OLD

image

2. Build the BHoM_Engine to this branch.

3. Run the script.

#### Fixed:
- Re-added support for assymetric sections in the UK Section Library.

### CODE REVIEW

**Comment by JosefTaylor** [comment]
Hey Isak, should I re-serialize US sections at this point, or just review UK sizes?

**Comment by IsakNaslundBh** [comment]
@JosefTaylor Think we can put the US ones in a separate PR, so only review please. Then good to get the US sections up here as well ofc!

**Comment by jdarcyBHE** [comment]
Isak did we finalise a naming convention for the section property names. I think previously the serialised sections would be as follows "RHS 200x100x10.0" this would cause issues when importing to Revit as the family name should be "RHS200x100x10" to match our Revit family libraries. I can't recall how Robot expects the section name in order to access its section library. Either we need a convention that matches all or a means of altering the name dependent on receiving push software.

**Comment by IsakNaslundBh** [comment]
@jdarcyBHE I have not modified any name of any sections in this PR. All I have really done is update all of the profiles to make sure they are centred around the origin and making sure all the asymmetric sections work to the new definitions.

I would prefer to not change the name on the BHoM side, as that would invalidate any BHoMData component set to a sections of that name as well as any script filtering by name etc.

I think string matching/standard matching needs to be done inside the toolkits, basically converting between BHoM standard and Revit standard.

BTW, I found a small bug the needs fixing in the sections. Will push up a correction.

**Comment by IsakNaslundBh** [comment]
@all, found some errors in the SteelFOrLife bluebook information used to generate these sections. Need to evaluate before pushing up new data.

**Comment by IsakNaslundBh** [comment]
Closing this, to be replaced by PR raised in DataSets

**Pull request closed without merging**
