### PR TITLE
BHoM_Engine: rounding issues fixed

### LINKED ISSUE #3426: BHoM_Engine: RoundWithTolerance method is misleading
#### Description:

As in the title, `RoundWithTolerance` is misleading because what it actually does is rounding to floor. My suggestion is to rename it to `RoundToFloor`, to make space to just `Round` and `RoundToCeiling`.

FYI @alelom @IsakNaslundBh @al-fisher

### LINKED ISSUE #3429: BHoM_Engine: RoundWithTolerance rounds to nearest instead of floor
#### Description:

Description of `RoundWithTolerance` method claims it rounds to floor (issue related to name ambiguity raised under https://github.com/BHoM/BHoM_Engine/issues/3426), and indeed it is what happens in most cases. However, line below rounds to nearest:
https://github.com/BHoM/BHoM_Engine/blob/2bb21bbee1bcf8fcec1dfcda4dd1f7cf8258bcd7/BHoM_Engine/Query/RoundWithTolerance.cs#L73

...this of course causes different behaviour than intended.

FYI @alelom 

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FBHoM%5FEngine%2F%233429%2DRoundingToFloorBug).

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3426
Closes #3429

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FBHoM%5FEngine%2F%233430%2DRoundingIssues), UTs added

### Additional comments

So far we had just one method, `RoundWithTolerance`, which did round the numbers towards the floor regardless of sign, i.e. 121 rounded to 2 would yield 120 and equally, -121 rounded to 2 would yield -120. This is potentially ambiguous on 2 levels:
- the name does not indicate the value is rounded to floor
- rounding to floor is not consistent with what general rounding does, i.e. rounding to floor should always return lower value from the 2 candidates (floor and ceiling) regardless of sign (so -121 should return -122)

As a remedy I propose 3 separate methods that follow the standard rounding conventions:
- `RoundToFloor`
- `Round`
- `RoundToCeiling`

I believe this is a right move for the general audience, although I understand you may need the current implementation for diffing @alelom - if so, I'd suggest moving it to Diffing_Engine as a private method. Let's catch up on that 👍

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check installer
@BHoMBot check versioning

**Review by alelom — APPROVED** [review]
Tested with https://github.com/BHoM/DiffingTests_Prototypes/pull/22 and agreed the change with @pawelbaran.

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests
@BHoMBot check dataset-compliance

**Comment by pawelbaran** [comment]
Dispensating documentation compliance as it is out of scope of this PR

**Comment by pawelbaran** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 32526179440

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
