### PR TITLE
BHoM_Engine: Handle nulls

### LINKED ISSUE #2475: Base Engine - handle nulls
For the following methods:

 - [x] BH.Engine.Base.Query.Geometry3D(CustomObject obj)
 - [x] BH.Engine.Base.Query.UniquenessRestrictions(Type type)
 - [x] BH.Engine.Base.Query.Hash(IObject iObj, ComparisonConfig comparisonConfig, Boolean hashFromFragment)
 - [x] BH.Engine.Base.Query.GetAllFragments(IBHoMObject iBHoMObject, Type parentType)
 - [x] BH.Engine.Base.Query.Geometry(CustomObject obj)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2475

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check dataset-compliance

**Review by adecler — APPROVED** [review]
All works fine for me

**Pull request merged**
