### PR TITLE
BHoM_Engine: Fix Analytical_Engine and Graphics_Engine CSProj

### LINKED ISSUE #1749: Compliance issue for CSProj files
The following issues have been found for BHoM_Engine\Analytical_Engine\Analytical_Engine.csproj
 - [ ] Project references for 'Dimensional_oM' should be set to NOT copy local
 - [ ] Project references for 'Geometry_oM' should be set to NOT copy local
 - [ ] Output path for all build configurations should be set to '..\Build\'

### LINKED ISSUE #1750: Compliance issue for CSProj files
The following issues have been found for BHoM_Engine\Graphics_Engine\Graphics_Engine.csproj
 - [ ] Project references for BHoM DLLs should not include Version, Culture, or Processor Architecture
 - [ ] Project references for 'Reflection_oM' should be set to NOT copy local
 - [ ] Output path for all build configurations should be set to '..\Build\'

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #1749 
Fixes #1750

### CODE REVIEW

**Comment by kThorsager** [comment]
or wait @alelom will this conflict with your PR #1717 ?

**Comment by FraserGreenroyd** [comment]
@kThorsager it might but that is a draft and we want to clean up the installer stuff to start fixing Dynamo so would need to be brought up to date before it's finished I expect anyhow. @alelom are you happy for us to merge this given that status?

**Comment by FraserGreenroyd** [comment]
According to https://github.com/BHoM/TriangleNet_Toolkit/pull/27 that PR replaces #1717 (for further info)

**Comment by kThorsager** [comment]
Yes, this does seem safe in that case, (but why is the PR still open if the code was transferred? @alelom )

**Comment by alelom** [comment]
> Yes, this does seem safe in that case, (but why is the PR still open if the code was transferred? @alelom )

Closing it now. I didn't want the branch to be deleted.

**Pull request merged**
