### PR TITLE
Upgrade to Mongo version 2.18

### LINKED ISSUE #2948: Make sure the same version of MongoDB is used across all repos
#### Broken rules:
The same version of the MongoDB dlls should be used across all repos. This is currently not the case.

#### Suggestions to restore compliance:
Update to the latest version (2.18) across all repos:
 - [x] Mongo Toolkit
 - [x] Serialiser Engine
 - [x] Versioning Engine
 - [x] Versioning Toolkit
 - [x] Socket Adapter
 - [x] File Adapter
 - [ ] ~~Karamba3D engine~~ (will be handled separately by @alelom )
 - [ ] ~~SpeckleBHoMRobot~~ (ignored as using BHoM NuGet packages)
 - [x] CI_Test
 - [x] SharePoint Adapter

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #2948

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by FraserGreenroyd — DISMISSED** [review]
I have run the test scripts that we use for our end-of-milestone beta testing on the following concepts:

 - Serialisation
 - Versioning
 - Socket
 - Mongo Toolkit

All have passed satisfactorily to allow these to go to alpha for further review by alpha users. Approving for merge.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 9573794424

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 9573786742

**Review by FraserGreenroyd — APPROVED** [review]
I have run the test scripts for the end of milestone and everything is still working happily.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 9687376834

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 9687371167

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
