### PR TITLE
Diffing_Engine: Add function to get ObjectDifferences to correctly identify modified items in non-indexed/unsorted collections

### LINKED ISSUE #2766: Diffing_Engine: add workaround to get ObjectDifferences to work for non-indexed, unsorted Collections
#### Description:

Currently, ObjectDifferences() relies on Kellerman CompareDOTNet library.

A normal, to be expected limitation of that library is that [non-indexed collections cannot be compared correctly](https://github.com/GregFinzer/Compare-Net-Objects#limitations). This is because if two collections have different length, there is little to do: their elements are compared one-by-one. There is no way to tell which item of the collection must be compared to which.

In some cases in BHoM we have collections that behave like non-indexed: looking at **_you_**, [RevitParameters](https://github.com/BHoM/Revit_Toolkit/issues/1168#issuecomment-1058233316). While this should be expected to mess up things like poor Diffing, we need a workaround that can be rapidly deployed for extreme cases like this.

#### Steps to reproduce:

See https://github.com/BHoM/Revit_Toolkit/issues/1168.

#### Expected behaviour:

See https://github.com/BHoM/Revit_Toolkit/issues/1168.

#### Test file(s):

See https://github.com/BHoM/Revit_Toolkit/issues/1168.

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1369
   
### Issues addressed by this PR

Closes #2766 

### Test files

See https://github.com/BHoM/Revit_Toolkit/issues/1168.

### CODE REVIEW

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Review by pawelbaran — APPROVED** [review]

**Comment by alelom** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 5551168258

**Pull request merged**
