### PR TITLE
Physical_Engine: Fix typo and punctuations

### LINKED ISSUE #2780: BHoM_Engine: More instances of obejct to correct
#### Broken rules:
Multiple instances of `obejct` in descriptions:
image

#### Suggestions to restore compliance:
These should be corrected to `object`. 

This would also be a good opportunity to fix the punctuation warnings from this PR: https://github.com/BHoM/BHoM_Engine/pull/2759/files

### PR DESCRIPTION
**Pull request by robinflyman**
Closes #2780

Fixed a typo and fixed the compliance warnings from https://github.com/BHoM/BHoM_Engine/pull/2759/files

### CODE REVIEW

**Review by jamesramsden-bh — APPROVED** [review]
All typos fixed by inspection. No code changed. All seems compliant.

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
Requested changes have been made.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 5990998702

**Pull request merged**
