### PR TITLE
Serialiser_Engine: Get all methods, objects, and type to serialise

### LINKED ISSUE #2289: Serialiser_Engine: All objects, types and methods should serialise correctly
As per title

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #2289

Some types, objects, and methods were still not deserialising correctly. This PR aims to fix that.

### Test files
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/BHoM_Engine/Serialiser_Engine/Serialisation_Engine.gh?csf=1&web=1&e=7g2oQo

image

### CODE REVIEW

**Comment by adecler** [comment]
Note: Those two methods don't serialise correctly on this branch but were already fixed in https://github.com/BHoM/BHoM_Engine/pull/2273:

```
BH.Engine.Base.Query.TryGetValue(FragmentSet fragmentSet, Type fragmentType, IFragment& fragment)
BH.Engine.Representation.Query.TryGetRendermesh(IBHoMObject bHoMObject, RenderMesh& renderMesh)
```

(those two are the only methods with `out` argument).

**Comment by adecler** [comment]
@BHoMBot check copyright

**Review by rolyhudson — COMMENTED** [review]
Test file not running as expected for me. 
I see the following problems:
Screenshot 2021-02-02 121928
Screenshot 2021-02-02 121948

Plus the already noted 4 exceptions of serialisation of the following methods.
```
AdapterId(IBHoMObject bHoMObject, Type adapterIdFragmentType)
AdapterId(IBHoMObject bHoMObject, Type adapterIdFragmentType)
TryGetValue(FragmentSet fragmentSet, Type fragmentType, IFragment& fragment)
TryGetRendermesh(IBHoMObject bHoMObject, RenderMesh& renderMesh)
```

**Comment by adecler** [comment]
@rolyhudson , I just retested the 3 object types you showed above with the daily installer and they all work for me. 
They were also working for @IsakNaslundBh yesterday although he didn't write his review here yet.

Are you sure that your File_Toolkit is from the installer and not a separate branch ?

**Review by rolyhudson — APPROVED** [review]
@adecler yes I was out of sync, sorry!. Now updated and rechecked. All looking good in the test script - picking up only the 4 expected method serialisations.

**Comment by adecler** [comment]
@BHoMBot check copyright

**Pull request merged**
