### PR TITLE
BHoM_Engine: null inputs enabled in TryRunExtensionMethod

### LINKED ISSUE #3393: BHoM_Engine: Compute.TryRunExtensionMethod does not support null method arguments
#### Description:

As spotted by @michal-pekacki, currently `Compute.TryRunExtensionMethod` will fail in case of any method arguments being equal to `null`, due to the following line:
https://github.com/BHoM/BHoM_Engine/blob/f56fb5f93ce94587ce5b403b9a057fdd387dd830/BHoM_Engine/Compute/TryRunExtensionMethod.cs#L155

Naturally, that makes sense because we do not know the type `null` argument is meant to represent, no way to bind.

Recently this limitation started becoming an issue (`null` method argument can sometimes be perfectly valid), so I had a think about potential improvements and came up with the following pattern:

```C#
public static bool TryRunExtensionMethod<T1>(this T1 obj, string methodName, out object result)
{
    Type[] types = new Type[] { typeof(T1) };
    Func<object[], object> method = ExtensionMethodToRun(methodName, types); // Existing method after minor tweaks
    // Call the method and return the outputs
}

public static bool TryRunExtensionMethod<T1, T2>(this object obj, string methodName, T2 parameter1, out object result)
{
    Type[] types = new Type[] { typeof(T1), typeof(T2) };
    Func<object[], object> method = ExtensionMethodToRun(methodName, types); // Existing method after minor tweaks
    // Call the method and return the outputs
}

public static bool TryRunExtensionMethod<T1, T2, T3>(this object obj, string methodName, T2 parameter1, T3 parameter2, out object result)
{
    Type[] types = new Type[] { typeof(T1), typeof(T2), typeof(T3) };
    Func<object[], object> method = ExtensionMethodToRun(methodName, types); // Existing method after minor tweaks
    // Call the method and return the outputs
}

...repeat until T1-T10
```

First question: do you see an immediate gap in the above? The objective is to maintain the current functionality while providing necessary type strength that would ensure the correctness of bindings. If not, how afraid would you be about refactoring the current code? It would require raising a long chain of PRs to align all repos that leverage the mechanism, also a breaking change in the UI I'm afraid (although that should be less of an issue, assuming the method is not called from e.g. GH). In general, please shout if you dislike the idea for any reason.

Finally, currently the method has an `out` parameter, which I could also migrate to `Output<T1, T2>` if there is such will - happy to hear your opinion on that too. Cheers!

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3393

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FBHoM%5FEngine%2F%233397%2DNullsInTryRunExtensionMethod).

To run the script, add the following snippet into any engine project that has required dependencies:
```C#
// Pass ICurve as 1st argument
// Should bind if 2nd argument != null
// Should not bind if 2nd argument == null
public static void AmbiguityTest1(this ICurve curve, Point point)
{

}

// Pass ICurve as 1st argument
// Should bind if 2nd argument != null
// Should not bind if 2nd argument == null
public static void AmbiguityTest1(this ICurve curve, Vector vector)
{

}

// Pass ICurve as 1st argument
// Should always bind
public static void AmbiguityTest1(this ICurve curve)
{

}

// Pass Wall as 1st argument
// Should bind if 2nd argument != null
// Should not bind if 2nd argument == null
public static void AmbiguityTest2(this BH.oM.Physical.Elements.ISurface obj, Point point)
{

}

// Pass Wall as 1st argument
// Should bind if 2nd argument != null
// Should not bind if 2nd argument == null
public static void AmbiguityTest2(this BHoMObject obj, Vector vector)
{

}

// Pass any BHoMObject as 1st argument
// Should always bind
public static void AmbiguityTest3(this BHoMObject obj, Vector vector = null)
{

}

// Pass any BHoMObject as 1st argument
// This one should not bind at any case
public static void AmbiguityTest3(this BHoMObject obj)
{

}
```

### Additional comments

`IsNullable` consists of 2 steps:
- check if the type is a reference type (obvious)
- check if the type is a nullable value type, following [this article](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types#how-to-identify-a-nullable-value-type)

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@IsakNaslundBh I pushed the commits that we discussed offline, the PR should be ready for review. Please note I added the snippet to paste into Engine before running the test script.

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check unit-tests
@BHoMBot check versioning

**Review by IsakNaslundBh — APPROVED** [review]
Happy with the changes made here. Have tested with the test script as well as scripts making use of the IElements that heavily relies on RunExtensionMethod - all working as expected.
Also relying some on testing performed by @pawelbaran on other parts of the code making use of the RunExtensionMethods.

Approved

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
