### PR TITLE
BHoM_Engine: documentation compliance fixed

### LINKED ISSUE #3439: BHoM_Engine: fix documentation compliance
#### Description:

Errors listed out [here](https://github.com/BHoM/BHoM_Engine/pull/3438/checks?check_run_id=34182023890)

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3439

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
