### PR TITLE
7.3 Deployment

### PR DESCRIPTION
**Pull request by BHoMBot**
#### Feature
 - [BHoM_Engine: null inputs enabled in TryRunExtensionMethod](https://github.com/BHoM/BHoM_Engine/pull/3397)
 - [Ground_Engine: Add method that returns a unique list of suite names](https://github.com/BHoM/BHoM_Engine/pull/3396)
   -  Added `DistinctSuites` which gets all the unique suites for testing from the `ContaminantSamples` on a `Borehole`;
   -  Updated `IsValid` method and outputs;
   -  Updated methods that reference `IsValid()`;
   -  Added `ContaminantProperty` method to return an `IContaminantProperty` based on `Type`;
 - [Ground_Engine: Consolidate method for a Borehole](https://github.com/BHoM/BHoM_Engine/pull/3372)
   -  Added `ConsolidateStrata` method that uses a property to combine sequential `Stratum`. For example, combining `Stratum` with the same `ObservedGeology` property. 
 - [Ground_Engine: Remove blankGeology from Stratum Create method](https://github.com/BHoM/BHoM_Engine/pull/3375)
   -  Removed `blankGeology` from the `Create` method for `Stratum` and versioned the method;
 - [Structure_Engine: Add engine methods for retaining wall classes](https://github.com/BHoM/BHoM_Engine/pull/3408)
   - Added required extension methods for implemented interfaces for new retaining wall classes.
   -  Added `Geometry()` method for `Stem` and `RetainingWall`
   -  Added `IsNull()` method for `Stem` and `RetainingWall`
   -  Added `SolidVolume()` method for `Stem` and `RetainingWall`
   -  Added `MaterialComposition()` method for `Stem` and `RetainingWall`
   -  Added `SetOutlineElements(List<IElement1D> outlineElements1D)` method for `Stem`
   -  Added `OutlineElemets1D()` method for `Stem`
   -  Added `Geometry3D()` method for `Stem` and `RetainingWall`
   -  Migrated `IsQuad`, `IsTriangular`, `IsRectangular`, `IsSquare` to the `Geometry` namespace so that it can be used on `PolyCurve`s  the methods in `BH.Engine.Analytical` are unchanged, and just reference the `Geometry` methods.
#### Bug
 - [BHoM_Engine: Additional check for assembly qualified type without version for Create EngineType](https://github.com/BHoM/BHoM_Engine/pull/3399)
 - [Geometry_Engine: BooleanDifference secured against single-dimensional regions](https://github.com/BHoM/BHoM_Engine/pull/3369)
 - [Search_Engine: Update unit tests for ExtractAll, ExtractTop, ExtractSorted and MatchScore](https://github.com/BHoM/BHoM_Engine/pull/3377)
   -  Updated `UnitTest`s for `ExtractAll`, `ExtractTop`, `ExtractSorted` and `MatchScore` to reflect the changes made in `Search_oM`.
 - [Serialiser_Engine: fix for MessageForDeleted to be picked up for properties of types that have multiple matching types](https://github.com/BHoM/BHoM_Engine/pull/3371)
 - [Structure_Engine: Fixed bug where PanelToFEMesh returned an error ](https://github.com/BHoM/BHoM_Engine/pull/3363)
   -  Fixed by bug whereby one `Edge` existed in the opposite direction to the `Panel` would caush an error for `PanelToFEMesh`;
   -  Fixed bug whereby `DiscontinuityPoints()` did not work for `PolyCurve`;
   -  Updated unit tests for `DiscontinuityPoints()` to include open `PolyCurve`s;
   -  Replaced unit tests for `FEMeshToPanel` and `PanelToFEMesh` as the data was empty.
 - [Structure_Engine: Update `PileFoundation` Geometry method](https://github.com/BHoM/BHoM_Engine/pull/3412)
   -  Updated `PileFoundation` `Geometry` method to use `IRegion` `Geometry` method for the `PileCap`.
 - [Type matching based on unqualified names enabled in Create.EngineType](https://github.com/BHoM/BHoM_Engine/pull/3389)
 - [Verifiaction: Add reference to Diffing_Engine to properly access the IsEqual method](https://github.com/BHoM/BHoM_Engine/pull/3414)
#### Compliance
 - [Ground_Engine, BHoM_Engine: Add UnitTests for ConsolidateStrata, remove UTs for GeometryHash](https://github.com/BHoM/BHoM_Engine/pull/3379)
   -  Added unit tests for `ConsolidateStrata` method;
   -  Removed unit tests for `GeometryHash` as the method was completey reworked;.
 - [Serialiser_Engine: Update NullOrEmptyCheck to just check for Null](https://github.com/BHoM/BHoM_Engine/pull/3364)
   -  Updated `NullOrEmptyCheck` in `Serialise` method for `IBHoMObject`s to just check `null` for `Name` properties;
   -  Updated unit tests for `CellularSectionFromBase` following changes to the `Serialse` method;
 - [Serialiser_Engine: Various changes to get unit-tests functional](https://github.com/BHoM/BHoM_Engine/pull/3391)
   -  Removed test in Serialiser_Engine that contained `Hashset<int>` in the `CustomData` causing it to fail.
   -  Added `ExplictType` for `Hashset<T>` to avoid failing `UnitTest`;
   -  Removed null inputs from `URL` unit test that was causing a `null` execption;
   -  Updated `URL`, `IsPrototype` and `DocumentationURL` unittests;
   -  Removed tests for `AllTypesIObject()` and `Versinoing` from Serialiser_Engine_Tests because the `[Ignore]` attribute is not working as inteded for CI;
   -  Removed serialiser test for `BitMap` as test is not functioning as intended for CI.
 - [Structure_Engine: Update UT for CellularSection](https://github.com/BHoM/BHoM_Engine/pull/3381)
   -  Updated unit tests for `CellularSectionFromBase`;
 - [Update AssemblyFileVersion to 7.3](https://github.com/BHoM/BHoM_Engine/pull/3362)

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check code-compliance

**Review by alelom — APPROVED** [review]
Approving Diffing_Engine based on the [Diffing Testing procedure](https://burohappold.sharepoint.com/:w:/s/BHoM/ETqNIAIu-2dOqX5BxgH73c4BKQmq40WqRUmziayR5m2mCw?e=R4uSdm).

**Comment by gideontamir16** [comment]
Reviewed for Facades_Engine. Script functions as expected per Facade Engine test procedure

**Comment by JohnSloane** [comment]
Reviewed for Lighting_Engine. Script functions as expected per Lighting Engine test procedure.

**Comment by vgreen-BH** [comment]
Reviewed for Facades using the 9/17 beta artefact, all is behaving as expected per the test procedure.

**Review by vgreen-BH — APPROVED** [review]
Reviewed for Facades using the 9/17 beta artefact, all is behaving as expected per the test procedure.

**Review by jamesramsden-bh — COMMENTED** [review]
Regarding Environment_Engine only: Tested as per test procedure, test results saved in 'Physics 7.3 testing plan'. No issues found in Environment_Engine that would block a merge.

**Pull request merged**
