### PR TITLE
Reflection_Engine: Create.AllTypes made more precise

### LINKED ISSUE #2694: Reflection_Engine: Create.AllTypes is not precise enough
#### Description:

As in the title, when one calls `Create.AllTypes` with `name` equal to e.g. `BH.oM.Structure.Elements.Bar`, the method returns `BH.oM.Structure.Elements.Bar` and `BarFEAType`, similar with `FEMesh` and `FEMeshType`, `Environment.Elements.Panel` and `PanelType` etc.

This, by itself is not the end of the world, but similar applies to non-BHoM types, which may cause deserialisation errors when the type name is extracted from .json, passed to `AllTypes` and then first (random) item from the return collection is taken.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #2694

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine%2F%232695%2DAllTypesMadeMorePrecise&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check code-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — COMMENTED** [review]
I cannot foresee this PR impacting bot operations negatively.

**Review by adecler — APPROVED** [review]
I am ok with this.

It is important to note that it changes slightly the functionality of the method though. For example, we cannot get all types from a namespace anymore. As it was never used that way, I am ok to approve but there is always a small risk that a script somewhere might stop working because of this PR.

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
