### PR TITLE
Serialiser_Engine: Align to forward versioning

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
Related to https://github.com/BHoM/Versioning_Toolkit/pull/133

   
### Issues addressed by this PR
See https://github.com/BHoM/Versioning_Toolkit/pull/133

Note: This code also support the injection of the `_bhomVersion` in json but has the code that add it commented out as agreed so it make this PR forward compatible with next beta.

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check copyright

**Review by FraserGreenroyd — DISMISSED** [review]
This has been tested in tandem with the associated [PR on Versioning_Toolkit](https://github.com/BHoM/Versioning_Toolkit/pull/133), a full review of the functionality is available [here](https://github.com/BHoM/Versioning_Toolkit/pull/133#issuecomment-763978563).

I have highlighted 3 changes which I think need implementing to this PR, however, I am conscious that waiting until tomorrow morning for a re-review would hold you up @adecler overnight.

Because the changes are really very minor, I am approving this PR to allow it to be merged on the following provisional conditions:

 - This PR (and Versioning) are not merged until after 1am UTC Thursday 21st January 2021 to allow the alpha to build without these changes and without merging popping up versioning windows for alpha testers
 - A subsequent PR is raised on Serialisation_Engine which addresses the highlighted changes in isolation for quick review/merge in the morning

My reasoning for doing it this way is that while I am 99% sure the change to prevent the windows popping up is the right one, I have a 1% reservation, and do not wish to make a mess of @adecler PR and potentially hold up a day of output for him incorrectly. Thus I am defaulting to a slightly safer, albeit perhaps odd way round. I feel this way round allows for flexibility of all outcomes, allows @adecler to be unblocked, and protects the alpha. I recognise this delays inclusion to the alpha for this work by a day, but that would have happened if I hadn't reviewed at all so I feel this is fair.

If however I am wrong and those lines should not be changed, then I am happy @adecler for you to merge without adhering to the above conditions :smile:

**Comment by adecler** [comment]
Thanks @FraserGreenroyd , I have commited your changes as they all make sense.

**Comment by adecler** [comment]
@BHoMBot check copyright

**Review by FraserGreenroyd — APPROVED** [review]
LGTM :smile:

**Pull request merged**
