### PR TITLE
Programming_Engine: Migrate code from constructor of NodeBlock and LoopBlock to new Create methods

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1028

   
### Issues addressed by this PR
See https://github.com/BHoM/BHoM/issues/1027 for details

### CODE REVIEW

**Review by alelom — APPROVED** [review]
Works fine, LGTM.

**Comment by adecler** [comment]
I had to do a rebase of the branch for CI to be happy, @alelom do you mind reapproving ?

**Review by alelom — APPROVED** [review]

**Pull request merged**
