### PR TITLE
Physical_Engine: Make physical surfaces return material and volume of all content

### LINKED ISSUE #2895: Physical_Engine: Consistent Volume and MaterialComposition Behavior for Elements Containing Other Elements with Volume
#### Description:
Currently, the Physical methods for `SolidVolume` and consequently `MaterialComposition` do not account for an elements openings (the method simply does element area * thickness).

As per:
image
we would like to align these so they always return volumes and compositions inclusive of their contained elements.

#### Steps to reproduce:
Create an element with nested elements with volumes, such as a wall with openings that have their own construction and resulting volume. The volume and composition returned only account for the wall itself, excluding the contained elements.

#### Expected behaviour:
The resulting volume and composition should include the volumes and materials of all contained opening elements.

#### Test file(s):
[Test File](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Physical_Engine/%232895%20-%20Volume%20and%20MatComp%20including%20Nested%20Elems?csf=1&web=1&e=bmsy3m)

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2895

Updates so that Physical ISurface objects account for inner opening type objects, such as doors and walls, for computation of SolidVolume as well as MaterialComposition.

- Add method for VolumetricMaterialTakeoff
- Make MaterialComposition method rely on new method
- Make SolidVolume rely on the new method

Important that this _is_ changing behaviour, and would impact workflows like LCA, but should be to the better. Important that people using the tools are aware of this. @enarhi when review/merged would you be able to help spread this?

Also, smaller change, is I removed all errors/warnings regarding Void type openings, as imo, it is safe to simply return 0 volume/empty material composition for this type of object, given it by definition is meant to model nothingness.

### Test files

Testfile from issue:

[Test File](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Physical_Engine/%232895%20-%20Volume%20and%20MatComp%20including%20Nested%20Elems?csf=1&web=1&e=bmsy3m)

Also good ofc if this can be tested through a few cases.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@enarhi if you want this to make the Beta, we need it reviewed kind of ASAP.

**Review by enarhi — DISMISSED** [review]
LGTM, tested test file along with a few other use cases and results are consistent and as expected per compliance with other similar calc methods.

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@enarhi had some silly description mistakes I had to fix. Do you mind re-approving?

**Review by enarhi — DISMISSED** [review]
LGTM, functionality all there as expected as per previous review.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
Last commit is minor and not sufficiently changes @enarhi review following bot reports to reapproving for merge.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
