### PR TITLE
Diffing_Engine: Toolkit-specific Diffing methods; restructured Diff; numeric Tolerance

### LINKED ISSUE #2651: Diffing_Engine: improve Toolkit-specific support backend functionality
#### Description:

After https://github.com/BHoM/BHoM_Engine/pull/2647, @pawelbaran and me identified some points that could be improved in the backend system.

In particular, we could leverage more the TryRunExtensionMethods().

Further, if we add mechanisms based on TryRunExtensionMethods(), we should be able to add a more reliable support for Toolkit-specific objects PropertiesToConsider (and Exceptions, etc.) as input separately, instead of putting all together in the `DiffingConfig.PropertiesToConsider`. Although this latter option should remain available to users (i.e. any toConsider "thing" should be insertable in the `DiffingConfig.PropertiesToConsider`, and the Diffing should be intelligent enough to dispatch as appropriate), we should also be able to have more ToolkitSpecific Diffing methods that take inputs separately.

### Proposed changes

- See how much we can ditch the delegate approach for a TryRunExtensionMethods approach instead
- Minimize the needed number of extension methods needed.
- See if we can simplify the RevitDiffing method with this.

### LINKED ISSUE #2684: BHoM_Engine: reference to System.Management.Automation is to be removed
#### Description:

`System.Management.Automation` and related nuget were added for the [WildcardPattern ](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.wildcardpattern?view=powershellsdk-7.0.0 ) feature. Here is [an example use case](https://stackoverflow.com/a/35655453/3873799).

However, the dll [is not meant to be referenced/used directly](https://stackoverflow.com/questions/66607550/system-management-automation-is-incompatible-with-net-core-3-1/66607812#66607812), and its direct support is already fading (.NET Core apps do not support it).

### Proposed changes
Remove the reference.

Add a Wildcard matching mechanism for all instances where it is needed.

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1330

   
### Issues addressed by this PR

Closes #2651
Closes https://github.com/BHoM/BHoM_Engine/issues/2664
Closes #2684

#### 1) Toolkit-specific `*Diffing()` methods
Toolkit-specific Diffing now rely on TryRunExtensionMethod and a discovery of `*Diffing()` methods that can be defined in specific namespaces. The IDiffing calls those automatically. This replaces the previous temporary solution that used delegates.

#### 2) Toolkit-specific `ComparisonInclusion()` methods
When analysing object properties, Toolkit-specific `Query.ComparisonInclusion(SomeObject object)` methods are discovered and called by the Hash/Diffing functions. These methods evaluate if/how specific properties should be included in the comparison. Implementing a `Query.ComparisonInclusion(SomeObject object)` in your specific toolkit allows for options that are specific to your Toolkit. 

See https://github.com/BHoM/Revit_Toolkit/pull/1131 for [an example of this](https://github.com/BHoM/Revit_Toolkit/pull/1131/files#diff-a6a0b416b094c093ce1500364a67d5d5d5e779c495ff09f6ff2b1807d759af18). More details below.

<details>

The `ComparisonInclusions()` extension method is called as part of the `ObjectDifferences` method:
image

The `ObjectDifferences()` method is in turn called by [one of the many diffing methods, see diagram here](https://user-images.githubusercontent.com/6352844/142921132-00bfe870-f58e-421e-a50e-f4211b3611fc.png). This is not the place to explain all of them in detail, but a wiki will soon be put in place. The only important thing to know here is that an extension method `ComparisonInclusion()` can be defined for specific objects or toolkits, and this will determine how differences for that object will be considered when diffing. The only one implemented (as part of this set of PRs) is in [the one for `RevitParameters`](https://github.com/BHoM/Revit_Toolkit/pull/1131/files#diff-a6a0b416b094c093ce1500364a67d5d5d5e779c495ff09f6ff2b1807d759af18).

A `Query.ComparisonInclusion()` function must have the following signature:

```cs 
ComparisonInclusion ComparisonInclusion(SomeObject object, string propertyFullName, BaseComparisonConfig comparisonConfig)
```

where: 
- `object`: the object whose difference/hash is being evaluated.
-  `propertyFullName`: the full name (path) of the object being evaluated.
- `comparisonConfig`: additional configurations.

It must return a `ComparisonInclusion` object populated with:
- `Include`: true if the property is to be included.
- `DisplayName`: if we want to display the name of the Difference found in this comparison with some custom name, this can be specified here. 

</details>

#### 3) Toolkit-specific `HashString()` methods
Similar to point 2), when computing the Hash for an object, if an extension method called  `HashString()` is found for the object or subproperty that is being analysed, then it is invoked. This method simply returns a unique string made of all property names and values for the object, but it allows to define toolkit-specific exceptions/inclusions/approximations/etc.

Again, the only implementation of this is [the one for RevitParameters, part of this set of PRs](https://github.com/BHoM/Revit_Toolkit/pull/1131/files#diff-ab2b756652edf1af343b281f9aa7ea7cc5a12c47d380973b93d76f9bd26f31ea).

#### 4) Alignments to the new `Diff` object structure.
The new `Diff` object has a simplified structure for the `ModifiedPropertiesPerObject` property (no more `Dictionary<Dictionary<Tuple<etc>>>`) and therefore adjustments were made for that.

#### 5) Custom numerical approximation: Numeric Tolerances/Significant Figures

We can control the approximation of numbers when considering e.g. whether a numerical Difference matters for Diffing purposes, or to determine if certain numerical fluctuations should be considered when computing a Hash. 

I introduced two separate mechanisms to control this approximation, because they both were deemed necessary after chatting with different discipline experts. We can now use the:
- [NamedNumericTolerance](https://github.com/BHoM/BHoM/pull/1306/files#diff-3b8e8a896434081af4d80d33762240fb0ccc41b8bd6e3a2d33ac91a153f883d6) object, and/or the
- [NamedSignificantFigures](https://github.com/BHoM/BHoM/pull/1306/files#diff-5fe9888cccb62f0620809629576019e2615da1c3be935fe2530f05077a8d528f) object

to calculate a custom approximation for any named property.

Both of these objects are used in the [`NumericalApproximation()` method](https://github.com/BHoM/BHoM_Engine/pull/2699/files#diff-3f9657d3b133ff1f5315a1f99e01a41ad1fc37cc1ab631e47c858e6a9abe01b8), that is called by the Hash or Diffing process when numbers are being considered.

### Conclusion

This set of PRs is the final wave of big changes done to the Diffing and related objects/functions (e.g. Hash) in this Beta, and I expect that it will more or less settle here.
Once these are approved (i.e. we like the solution), I will document the entire structure of the code, add a proper wiki, diagrams and many tutorial resources.

### Test files

See https://github.com/BHoM/Revit_Toolkit/pull/1109

### Changelog

- Toolkit-specific Diffing now rely on TryRunExtensionMethod and a discovery of `*Diffing` methods that can be defined in specific namespaces.
- Toolkit-specific `Query.ComparisonInclusion(SomeObject object)` methods are discovered and called by the Hash/Diffing functions when analysing object properties. The `ComparisonInclusion` evaluates if/how specific properties should be included in the comparison; it can be implemented in specific Toolkits to allow for options that are specific to that Toolkit.
- Alignments to the new `Diff` object structure.
- Reworked the Custom numeric tolerances per property feature.
- General tidy up and quality of life improvements.

### CODE REVIEW

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check required

**Review by pawelbaran — APPROVED** [review]
L G T M ! 🚀 🥳 🎉

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 4336522814

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by alelom** [comment]
@BHoMBot check null-handling

**Comment by alelom** [comment]
@BHoMBot check required

**Review by pawelbaran — APPROVED** [review]

**Comment by alelom** [comment]
@BHoMBot check required

**Review by pawelbaran — APPROVED** [review]

**Comment by alelom** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 4398019763

**Pull request merged**
