### PR TITLE
MEP_Engine: Update CircularEquivalentDiameter.cs

### LINKED ISSUE #2813: MEP_Engine: Modification of Circular Equivalent Diameter Method
#### Description:
Modification of Circular Equivalent Diameter to exclude the thickness of the box profile (not standard, causing error in calculated value)

### PR DESCRIPTION
**Pull request by travispotterBH**
Modified CircularEquivalentDiameter to meet standard calculation expected outputs. Original method substracted out the box wall thickness*2 from the height and width. Ducts are sized (by convention) as the free and clear inner dimensions, so wall thickness adjustments to internal flow area are not required.

### Issues addressed by this PR

Fixes issue noted in  #2813  

Closes #

Closes #2813  

### Additional comments

As a general comment on duct wall thickness: wall thickness(gauge) is typically specified in the standard specs, but almost never modeled by engineer/drafter. Wall thickness (gauge) is typically a function of specific use of duct, and the longest dimension of the duct. SMACNA is a good resource for determining what gauge metal should be used for each situation.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by travispotterBH** [comment]
@BHoMBot  check required

**Review by alexissantella — APPROVED** [review]
equation is correct and works as expected

**Comment by travispotterBH** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by travispotterBH** [comment]
> @travispotterBH it'll be because of the age of the branch. Main is now performing better than this branch is, so this branch is worse than main, so it flags. Options are to either do a rebase to the PR, do a new PR, or wait till the PR is reviewed/ready to merge and then we can go with dispensation (the last option is easiest IMO).

@FraserGreenroyd Should be good for dispensation of the null-handling check and is ready to merge, I believe. 😀

**Pull request merged**
