### PR TITLE
Diffing_Engine: Added Newtonsoft.json.dll in xcopy post build event

### LINKED ISSUE #1882: Diffing_Engine: Copy of Newtonsoft.json.dll not in post build
Post build for Diffing_Engine needs to include a copy of Newtonsoft.json.dll.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #1882

### Test files

Not needed.

### CODE REVIEW

**Comment by adecler** [comment]
Can we just get rid of Newtonsoft instead please ?

**Comment by FraserGreenroyd** [comment]
> Can we just get rid of Newtonsoft instead please ?

Seconded!

**Comment by alelom** [comment]
The short answer is no, it's complicated.

**Comment by FraserGreenroyd** [comment]
> The short answer is no, it's complicated.

😿 

What about the long answer? Maybe that is more fun?

**Comment by alelom** [comment]
> > The short answer is no, it's complicated.
> 
> 😿
> 
> What about the long answer? Maybe that is more fun?

It's not like I had not spent the development time trying to avoid adding this dependency. I remember that removing it would require some work. I'd be happier to focus on other things.

**Comment by FraserGreenroyd** [comment]
> It's not like I had not spent the development time trying to avoid adding this dependency. I remember that removing it would require some work. I'd be happier to focus on other things.

That was not more fun 😿 

Maybe we can go for a compromise for now then, we'll review/merge this PR as appropriate but we perhaps do a session with @adecler to see if we can remove this dependency over the course of this milestone? Is that ok? 🙏

**Comment by alelom** [comment]
Ok happy to do but this milestone might be already too full for me, at least its first half for sure. During the last half sounds better, or even better during the next. Will raise issue.

**Comment by alelom** [comment]
Issue here: https://github.com/BHoM/BHoM_Engine/issues/1885

**Comment by adecler** [comment]
Happy to leave the removal of Newtonsoft for later if it's more complicated than it looks from the code itself.
Let's definitely have a workshop on it this milestone though as I am keen to make sure absolutely ALL serialisation happens though the serialisation engine to guarantee consistent behaviour.

**Pull request merged**
