### PR TITLE
BHoM_Engine: replaced calls to Query.Clone() and Query.IClone() with calls to BH.Engine.Base.DeepClone()

### LINKED ISSUE #2576: Geometry_Engine: remove `Query.Clone()` and `Query.IClone()` in favour of `BH.Engine.Base.DeepClone()`
#### Broken rules:

In light of https://github.com/BHoM/admin/issues/9#issuecomment-709032648.

#### Suggestions to restore compliance:

As title. This has to be actioned after all references are removed.

### LINKED ISSUE #2577: Analytical_Engine: replace calls to `Query.Clone()` and `Query.IClone()` with calls to `BH.Engine.Base.DeepClone()`
#### Broken rules:

In light of https://github.com/BHoM/admin/issues/9#issuecomment-709032648.

#### Suggestions to restore compliance:

As title.

### LINKED ISSUE #2582: Security_Engine: replace calls to `Query.Clone()` and `Query.IClone()` with calls to `BH.Engine.Base.DeepClone()`
#### Broken rules:

In light of https://github.com/BHoM/admin/issues/9#issuecomment-709032648.

#### Suggestions to restore compliance:

As title.

### LINKED ISSUE #2583: Structure_Engine: replace calls to `Query.Clone()` and `Query.IClone()` with calls to `BH.Engine.Base.DeepClone()`
#### Broken rules:

In light of https://github.com/BHoM/admin/issues/9#issuecomment-709032648.

#### Suggestions to restore compliance:

As title.

### LINKED ISSUE #2584: Environment_Engine: replace calls to `Query.Clone()` and `Query.IClone()` with calls to `BH.Engine.Base.DeepClone()`
#### Broken rules:

In light of https://github.com/BHoM/admin/issues/9#issuecomment-709032648.

#### Suggestions to restore compliance:

As title.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #2584 
Closes #2583 
Closes #2582 
Closes #2577

Closes #2576

### CODE REVIEW

**Comment by alelom** [comment]
@BHoMBot check installer

**Comment by alelom** [comment]
@BHoMBot check installer

**Review by FraserGreenroyd — COMMENTED** [review]
For the versioning @alelom I think we should put this on the DeepClone method:
```
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Plane)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Point)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Vector)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.CoordinateSystem.Cartesian)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Arc)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Circle)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Ellipse)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Line)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.NurbsCurve)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.PolyCurve)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Polyline)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Extrusion)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Loft)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.NurbsSurface)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.PlanarSurface)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Pipe)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.PolySurface)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Mesh)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Face)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.BoundingBox)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.CompositeGeometry)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Quaternion)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.TransformMatrix)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.Basis)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.Clone(BH.oM.Geometry.SurfaceTrim)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.IClone(BH.oM.Geometry.IGeometry)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.IClone(BH.oM.Geometry.ICurve)")]
[PreviousVersion("4.3", "BH.Engine.Geometry.Query.IClone(BH.oM.Geometry.ISurface)")]
```

Just so scripts and stuff can version nicely to using `DeepClone` as well, what do you think?

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3201609309

**Review by FraserGreenroyd — APPROVED** [review]
I have tested this by doing original clones of the geometry and then deep clones and comparing the output via the diffing engine and everything came back equal, suggesting to me that the use of `DeepClone` is equal to the result of the Geometry `IClone` and the replacement is safe.

Merging once all checks on dependent PRs are completed.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
