### PR TITLE
Spatial_Engine: Add FitPlane UnitTest for Spatial elements

### PR DESCRIPTION
**Pull request by LMarkowski**
### Issues addressed by this PR

 Refers directly to #2459

 
Following the discussion on [#2445](https://github.com/BHoM/BHoM_Engine/pull/2445#issuecomment-819566692) I'm raising a dummy PR to store all the failing unit tests as long as the issue that causes the errors won't get resolved.
I think this PR could be versatile for all projects across the BHoM_Engine repo. I'm adding the first UT that I encountered in the `Spatial_Engine`, but occurrences from any other projects can be directed here as well.

 ### Test files

N/A

 ### Changelog

N/A

 ### Additional comments

I'm assigning all of you guys as all of you were at some point involved in creating foundational unit tests. Feel free to unassign or add testers from other projects if you feel so. (Or maybe I should assign you to the issue instead?)

### CODE REVIEW

**Comment by LMarkowski** [comment]
@BHoMBot check unit-tests

**Comment by rolyhudson** [comment]
Added the do-not-merge tag as this is only for the convenience of keeping toxic unit tests available for when we have time to investigate the reasons.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required
@BHoMBot check compliance

**Review by IsakNaslundBh — APPROVED** [review]
Removed the item that was failing on the remote (whilst still working on local) to be able to get this merged in. Still not sure why it was failing on the remote, but prefer that this gets merged in rather than simply closed during the PR closure cycle.

Approving on the basis that the UT is now passing

**Comment by IsakNaslundBh** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
