### PR TITLE
Structure_Engine: Fix Query.CoordinateSystem crashing on self-intersecting Panels

### LINKED ISSUE #2306: Structure_Engine: Query.CoordinateSystem() still crashes on self intersecting panels
#### Broken rules:

Despite #2109 being closed by #2149 `Query.CoordinateSystem()` can still crash if panels are self intersecting. This is due to an unchecked call of `Spatial.Query.Centroid()`.

#### Suggestions to restore compliance:

A null check must be added to the Centroid call. Centroid itself already provides an error message and returns null without crashing, but this is only for single curves. The method operating on lists of curves will still crash, so that needs to be fixed as well.

### PR DESCRIPTION
**Pull request by IsakLarbornBH**
### Issues addressed by this PR

Closes #2306

Fixes Query.CoordinateSystem crashing on every self-intersecting Panel. This is done by:

* Encasing call to Centroid in try/catch blocks (as I don't want to have conflicts with the ongoing Null Check PR #2516  and thus can't fix the actual crash occuring in Centroid)
* Substituting control point average for centroid in cases where no centroid can be calculated

This should help further improve stability during pulls, etc.

### Test files

You could probably almost make your own test file faster than downloading this, but including this in case you want it:
[CoordinateSystem and Centroid test.zip](https://github.com/BHoM/BHoM_Engine/files/6648366/CoordinateSystem.and.Centroid.test.zip)

### CODE REVIEW

**Comment by IsakLarbornBH** [comment]
@BHoMBot check required

**Comment by IsakLarbornBH** [comment]
@BHoMBot check copyright compliance

**Comment by IsakLarbornBH** [comment]
@BHoMBot check dataset-compliance

**Comment by IsakLarbornBH** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakLarbornBH** [comment]
After discussing with @IsakNaslundBh, parking this so we can fix the root bug in Centroid once null checks have been added there, instead of merging this slightly hacky fix.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Review by IsakNaslundBh — APPROVED** [review]
Approving this. To remove the try-catch as soon as proper null handling of the geometry_Engine has been figured out.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
