### PR TITLE
Architecture_Engine: Remove CleanRoom, version to use CleanRegion

### LINKED ISSUE #2849: Architecture_Engine: Remove CleanRoom method
#### Description:

The CleanRoom method is redundant as this has been superseded by [CleanRegion ](https://github.com/BHoM/BHoM_Engine/blob/main/Analytical_Engine/Modify/CleanRegion.cs)in Analytical_Engine

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2849

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Review by robinflyman — APPROVED** [review]
Looks ok

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
