### PR TITLE
Geometry_Engine: numerical solution in IsCoplanar replaced with geometrical one

### LINKED ISSUE #2423: Geometry_Engine: IsCoplanar returns different results for the same points list with or without duplicated points
#### Description:

As in header. Coplanarity of points shouldn't depend on presence of duplicates. Might be the root of #2419 

#### Steps to reproduce:

See the test file.

#### Test file(s):

[SharePoint](https://burohappold.sharepoint.com/:f:/s/BHoM/EtT0QY6Sul1Mvtda3pIqLOcBz-Q-Nykq1yOJqxtAqpr6KA?e=pcFxe4)

### LINKED ISSUE #3294: Geometry_Engine: Switch IsCoplanar from numerical solution to fitting plane and checking distance to it
#### Description:

Recently (in https://github.com/BHoM/BHoM_Engine/pull/3283), collinearity check has been changed from numerical solution to a geometrical one, i.e. instead of computing matrices of point coordinates, a line is fit in point set and then each point is checked whether it lies within tolerance from that line. This change improved precision and robustness of the method, so I believe it would make sense to do similar with IsCoplanar.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #2423
Closes #3294

### Test files

General test files for the methods changed in this PR uploaded to [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%233298%2DGeometricalIsCoplanarNew&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
Test file for https://github.com/BHoM/BHoM_Engine/issues/2423 linked in the issue

### Additional comments

This is the last PR in the current push in Geometry_Engine 🙈

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by peterjamesnugent — APPROVED** [review]
Tested using the two scripts provided and the duplicate point script. 

My one comment would be to make sure the various Geometry_Engine test scripts this milestone get incorperated into unit tests (in a seperate PR) so they don't get forgotten about.

**Comment by pawelbaran** [comment]
Thanks @peterjamesnugent for the review. Updating the UTs is on my radar, to be done in sprint 6 based on https://github.com/BHoM/BHoM_Engine/issues/3277 👍

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
