### PR TITLE
Ground_Engine: Add project for ground related objects and associated engine methods

### LINKED ISSUE #3173: Ground_Engine: Add project for methods related to new ground objects

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/issues/1548
   
### Issues addressed by this PR

Closes #3173 

Add project for future development in 6.4 milestone

### Test files

CI/CD

### Changelog

- Added Ground_Engine for future development planned in 6.4 milestone

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
If the bots happy then this is a reasonable addition in advance of objects coming in during draft PRs without merging prior to the 6.3 beta to avoid versioning issues as discussed offline with @peterjamesnugent

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Pull request merged**
