### PR TITLE
Structure_Engine: Update UT for CellularSection

### LINKED ISSUE #3380: Structure_Engine: Update CellularSectionFromSection
#### Description:

Unit tests for CellularSection methods are not passing. This is because they were updated but the Serialiser_Engine `Serialise` method for `IBHoMObjects` was changed (and the UTs were not updated to reflect that).

#### Steps to reproduce:

See test script.

#### Expected behaviour:

Unit Test should pass.

#### Test file(s):

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Serialiser_Engine/%233357-Cellular%20Section%20UT%20Fail.gh?csf=1&web=1&e=9YBTte

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #3380 

### Changelog

- Updated unit tests for `CellularSectionFromBase`;

### Additional comments

@pawelbaran this is because the commits we made to remove checking the `Name` property altogether in the `Serialise` method - and I never updated the UTs.

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Review by pawelbaran — APPROVED** [review]
Approving on the basis of comparison of the .json files before and after: the only differences observed are `BHoM_Guid` and presence of `Name` property on one hand side, which is in line with @peterjamesnugent's PR description. So in essence, the datasets were updated without any change to the test itself.

**Comment by pawelbaran** [comment]
Dispensating the `unit-tests` check based on the fact that the reported failure also occurs on `develop`.

**Comment by pawelbaran** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 27915619358

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
