### PR TITLE
.ci: removed duplicate reference

### LINKED ISSUE #3196: .ci: Remove duplicate NetStandard reference
https://github.com/BHoM/BHoM_Engine/blob/eb756492dbf5274f069bdcbbcac9641c6e19107b/.ci/BHoMBot/Nuget/BHoM.Engine.nuspec#L22

In the `nuspec` template.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #3196 

removed duplicate reference to net standard library

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
Thanks @Tom-Kingstone

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Pull request merged**
