### PR TITLE
BHoM_Engine & Serialiser_Engine: hardcoded namespace checks replaced with method calls

### LINKED ISSUE #3340: BHoM_Engine: inconsistency in what is considered BHoM namespaces
#### Description:

In different parts of reflection, some namespaces are considered valid BHoM or not:
- core reflection method `ExtractAssembly` is checking namespaces against `Regex` patterns: https://github.com/BHoM/BHoM_Engine/blob/7cb0fb17ea012daeace6cdc6b8b500693c8ffcf0/BHoM_Engine/Compute/ExtractAssembly.cs#L281-L282
- meanwhile, `.Create.AllTypes` in BHoM_Engine: https://github.com/BHoM/BHoM_Engine/blob/7cb0fb17ea012daeace6cdc6b8b500693c8ffcf0/BHoM_Engine/Create/Type/AllTypes.cs#L50-L56
- meanwhile Serialiser_Engine has hardcoded `StartsWith` queries: https://github.com/BHoM/BHoM_Engine/blob/7cb0fb17ea012daeace6cdc6b8b500693c8ffcf0/Serialiser_Engine/Compute/Serialise/Type.cs#L91 https://github.com/BHoM/BHoM_Engine/blob/7cb0fb17ea012daeace6cdc6b8b500693c8ffcf0/Serialiser_Engine/Compute/Deserialise/Type.cs#L148

The above inconsistency introduces idiosyncrasies in some more complex reflection/serialisation workflows - would be great to unify across the entire code base.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3340

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FBHoM%5FEngine%2F%233341%2DBHoMNamespaceInconsistency&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4), passing the bot checks will also greatly add confidence.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling
@BHoMBot check versioning
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@IsakNaslundBh following our offline chat, I have added quite solid UTs to the GH test script and serialised them into datasets - ready for (hopefully final) review! 💪

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by IsakNaslundBh — APPROVED** [review]
Checked through in detail with @pawelbaran . Tested and works on my machine. Happy with the code as well as logic and semantics behind the changes. As long as bot checks passes, happy for this to be merged to alpha.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 24419999934

**Comment by IsakNaslundBh** [comment]
Granting dispensation on the basis that all new UTs are passing. Only failures found relates to UTs already failing

**Pull request merged**
