### PR TITLE
Fix typo in DomainTree creation

### LINKED ISSUE #3317: Typo in DomainTree creation
#### Description:

There seems to be a typo here ((min + min)/2):
https://github.com/BHoM/BHoM_Engine/blob/d13f40bb41726cb0b8ab3b4c809ac6819a8266a5/Data_Engine/Create/DomainTree.cs#L130

#### Expected behaviour:

The line should read ((min + max)/2)
`if ((data.DomainBox.Domains[index].Min + data.DomainBox.Domains[index].Max) / 2 < centre)`

### PR DESCRIPTION
**Pull request by vietle-bh**
### Issues addressed by this PR

Closes #3317 

The existing code does (min + min)/2 which I've rectified to (min + max)/2.

### Test files

It's just a typo so hopefully someone who worked on Domain Tree before can approve right away 😉

### CODE REVIEW

**Comment by vietle-bh** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Approving on code review and historical review [here](https://github.com/BHoM/BHoM_Engine/commit/360e58c72555fc119e85e476115b485ead3825ad#diff-8201c7d7ab5b2c4216333b53eed7377a83b729a353c3ce24e452ee4089f4cb2d) which shows that using `min - max` was put in to other areas which does suggest this is a typo bug.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@vietle-bh just a gentle reminder to include which engine is primarily affected by a PR to the BHoM_Engine repository in the title - I've added `Data_Engine` for this one 😄 just helps our automated change log processes

**Pull request merged**
