### PR TITLE
Environment_Engine: Add check for null Space perimeter in the IsValid method 

### LINKED ISSUE #2959: Environment_Engine: IsValid(Spaces) method to handle null perimeter
#### Description:

IsValid method currently can't handle cases where perimeter = null. Didn't previously realise this was possible but has just occurred for spaces pulled from an IES model.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2959 

### Test files
See Issue

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Review by michaelhoehn — APPROVED** [review]
Looks great! Ready to merge.

**Review by rboulton-BH — COMMENTED** [review]
I have tested this PR using the script proposed in the Issue it addresses and the fix performs flawlessly. This PR is a truly remarkable solution to the problem at hand. Highly commendable work by all those who contributed. Huzzah

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check ready-to-merge

**Pull request merged**
