### PR TITLE
Facade_Engine: Construction bugfix and adjacency tolerance bugfix

### LINKED ISSUE #2225: Facade_Engine: Constructions not included in opening create method
#### Description:
The construction input is not applied to the created opening for the Opening create method.

### LINKED ISSUE #2232: Facade_Engine: Adjacency check bug for miniscule tolerance errors
#### Description:
Adjacency check fails for endpoints that are off by miniscule amounts due to hardcoded =0 check.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #2225 
Closes #2232 

Fixes bugs for construction creation on opening create method and adjacency check accounting for tolerance.

### Test files
[TestFacadeEngineCreateConstructionAndAdjacency.zip](https://github.com/BHoM/BHoM_Engine/files/5676563/TestFacadeEngineCreateConstructionAndAdjacency.zip)

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Review by michaelhoehn — DISMISSED** [review]
Code looks good to me barring some minor compliance notes from the check.

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
Happy based on @michaelhoehn review as last commit was only a compliance fix :smile:

**Pull request merged**
