### PR TITLE
Geometry_Engine: Correctly pass tolerance for LineIntersection methods

### LINKED ISSUE #2902: Geometry_Engine: LineIntersection not passing tolerances properly
#### Description:

Some methods in LineIntersection are not passing the tolerance properly to the method doing the actual work.

#### Steps to reproduce:

Try checking the tolerance when intersection for example a PolyCurve with a Line. Could for example be 2 parallel lines that are more than 1e-6 (default tolerance) away from each other, say 1e-5, and set the tolerance to be larger than 1e-5. The method should now give itersections, but due to the lack of tolerance passing it is not.

#### Expected behaviour:

As above

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2902

Fixes tolerances being correctly passed to method doing actual work in line intersections.

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EuTzNW600kpFglxk53P9rlEBW6FsOhhmEEgKMHqCnCCLeQ?e=hhoZ9M

### Additional comments

Changed the name of the file from LineIntersections to LineIntersection (removing the plural s) as the code compliance accepts a trailing s on the method relative to the file name, but does not accept it the other way around.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check code-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Review by pawelbaran — APPROVED** [review]
Happy about the changes (clear improvement), but as discussed with @IsakNaslundBh offline, the whole concept of line infinity looks pretty overcooked now, possibly we could get rid of `useInfiniteLine` argument and simply drive the queries by `Line.Infinite`? Of course not for this PR, more of a general thought.

**Comment by FraserGreenroyd** [comment]
@IsakNaslundBh could we consider adding some Unit Tests for this in the future (happy for it to be a new issue if desired)?

**Comment by IsakNaslundBh** [comment]
> @IsakNaslundBh could we consider adding some Unit Tests for this in the future (happy for it to be a new issue if desired)?

Yes, we can. Will handle spearately. Issue raised here https://github.com/BHoM/BHoM_Engine/issues/2904

**Pull request merged**
