### PR TITLE
Spatial_Engine: Update description for create CircleProfile

### LINKED ISSUE #3249: Spatial_Engine: Description for CircleProfile is incorrect
#### Description:

https://github.com/BHoM/BHoM_Engine/blob/8e3fc35b66e7b6e924606aa0fda055a494b5864b/Spatial_Engine/Create/ShapeProfiles/CircleProfile.cs#L42C43-L42C43

#### Steps to reproduce:

1. Add CircleProfile `Create` method to canvas.

#### Expected behaviour:

Correct description.

### PR DESCRIPTION
**Pull request by MayaAroraJonsson**
### Issues addressed by this PR

Closes #3249

### CODE REVIEW

**Review by peterjamesnugent — APPROVED** [review]
Approved by inspection.

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
