### PR TITLE
BHoM_Engine: Remove deprecated methods

### LINKED ISSUE #3243: Remove methods marked ToBeRemoved
#### Broken rules:

Many methods are marked ToBeRemoved since 3.2, but some later.

#### Suggestions to restore compliance:

Remove the methods in question.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #3243 

Following methods marked `ToBeRemoved` have been removed:
- `BH.Engine.Architecture.QueryNewElement1D(Room, ICurve)`
- `BH.Engine.Diffing.Query.ListModifiedProperties(Dictionary<string, Dictionary<string, Tuple<object, object>>>)`
- `BH.Engine.Environment.Create.CleanSpace(Panel)`
- `BH.Engine.Environment.Query.FilterPanelsNotByType(Panel, PanelType)`
- `BH.Engine.Geometry.Query.Centre(Polyline, double)`
- `BH.Engine.Geometry.Query.Radius(Arc)`
- `BH.Engine.Structure.Create.Panel(ICurve, List<Opening>, ISurfaceProperty, string)`
- `BH.Engine.Structure.Create.Panel(List<Edge>, List<ICurve>, ISurfaceProperty, string)`
- `BH.Engine.Structure.Create.AreaUniformlyDistributedLoad(Loadcase, Vector, BHoMGroup<IAreaElement>, LoadAxis, boolean, string)`
- `BH.Engine.Structure.Create.BarUniformTemperatureLoad(Loadcase, double, BHoMGroup<Bar>, LoadAxis, boolean, string)`
- `BH.Engine.Structure.Create.ContourLoad(Polyline, Vector, Loadcase, LoadAxis, boolean, string)`
- `BH.Engine.Structure.Results.Create.MeshResult(MeshResultSmoothingType, MeshResultLayer, double, MeshResultType, Cartesian, IEnumerable<object>, IEnumerable<object>)`
- `BH.Engine.Structure.Create.GeometricalLineLoad(Line, Loadcase, Vector, Vector, Vector, Vector, string)`

And fixed cases where some deprecated methods were still being used in Structure_Engine

### Additional comments

If there are still unit tests for these methods, they will need to be removed as well.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 20502085398

**Review by FraserGreenroyd — APPROVED** [review]
I have reviewed the code and the deletions make sense, it's good to tidy these up so thanks @Tom-Kingstone !

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
