### PR TITLE
Structure_Engine: Add unit tests for local orientation methods

### PR DESCRIPTION
**Pull request by IsakLarbornBH**
### Issues addressed by this PR

See #550 

Adds unit tests to `Structure_Engine` local orientation methods:
* `Query.Tangent()`
* `Query.Normal()`
* `Query.LocalOrientation()`
* `Query.CoordinateSystem()`
* `Modify.SetNormal()`
* `Modify.SetLocalOrientation()`

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

Thanks @IsakLarbornBH , great work!

@FraserGreenroyd any worry about the failing checks?

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd any worry about the failing checks?

Nej, ingen oro fran mig

**Pull request merged**
