### PR TITLE
Reflection_Engine: Add ability to set Fragment property from list of objects

### LINKED ISSUE #2613: Reflection_Engine: Add ability to Set Fragment property from a list of objects
#### Description:
This is specifically to resolve the case of Excel VBA (see [this PR](https://github.com/BHoM/Excel_Toolkit/pull/310)) but could have other applications.

### LINKED ISSUE #2614: Reflection_Engine: Add ability to set a DateTime property from a number
#### Description:
This is more specifically to solve issues with the way Excel represents dates as number but but could have other applications.

@enarhi

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #2613
Closes #2614 

### Test files
- FragmentSet: The best way to test this is to try to push load combinations using [this file](https://burohappold.sharepoint.com/:x:/r/sites/Direction/designtechnology/RandDWishlist/00270_Load%20Case%20and%20Combinations%20Excel%20Tool/BuroHappold_BHoM_v4.3.beta_Loadcases%20and%20Combinations.xlsm?d=w20416a094cc24266aa6225fad5d7a64b&csf=1&web=1&e=RkFIKq)
- DateTime: [this file](https://burohappold.sharepoint.com/:x:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Reflection_Engine/%232614-DatetimeTest.xlsx?d=wb41a7dd8771d42b3ae21ae122eb662e3&csf=1&web=1&e=gSkxtv)

### CODE REVIEW

**Comment by adecler** [comment]
@enarhi , as luck has it, I had to make a change to the `SetPropertyValue` to improve our ability to set fragment property from a list of object as it was causing a bug in [this PR](https://github.com/BHoM/Excel_Toolkit/pull/310). 
So I ended up pushing the change for `DateTime` as well to avoid clashes between PRs.

**Comment by adecler** [comment]
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check dataset-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by enarhi** [comment]
Will leave to @IsakNaslundBh for a proper review on the FragmentSet piece, but DateTime's LGTM, tested and it is working as expected.

**Review by IsakNaslundBh — APPROVED** [review]
Works as expected. Tested in both excel with linked sheet and in Grasshopper with SetProperty component for Fragments

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
