### PR TITLE
BHoM_Engine: IToText fixed for primitives and DateTime

### LINKED ISSUE #3019: BHoM_Engine: IToText returns nonsensical values for primitives and DateTime
#### Description:
As in the title, the value returned is `GetType.ToString()` instead of simply `ToString()`.

image

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3019

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FBHoM%5FEngine%2FExcel%5FToolkit%2D%2314%2DEnumValueBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Review by adecler — APPROVED** [review]
The code change makes sense and works well in GH:

image

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Review by adecler — CHANGES_REQUESTED** [review]
Actually, I forgot to test one type and that's the one not working anymore: 

image

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance
@BHoMBot check unit-tests

**Review by adecler — APPROVED** [review]
All good now: 
image

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
