### PR TITLE
Facade_Engine: Spandrel u-value calculation method

### LINKED ISSUE #3145: Facade_Engine: Calculation Method to Calculate Spandrel Specific U-value for Opening
#### Description:
The current area weighting method to calculate the u-value for an opening uses an "edge" zone of 2.5 in. (0.0635 m) into the opening based on US standards for vision assembly. New US standards require the use of a 10 in. edge zone for _spandrel_ calculations so a secondary, spandrel-specific method is needed to accommodate this.

This method will require that spandrel openings will be differentiated from vision openings. New opening type enums need to be added for CurtainwallSpandrel and CurtainwallVision.

### PR DESCRIPTION
**Pull request by vgreen-BH**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1553

   
### Issues addressed by this PR

Closes #3145 

- Adds method for calculating area weighted u-value of a spandrel opening using methods per NFRC 100.
- Updates OpeningAW calculation method to call spandrel calculation when req'd, based on assigned OpeningType

### Test files

[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/BHoM_Engine/Facade_Engine/BHoM%20PR%20Test%20Files/230906_SpandrelAWTestFile.gh?csf=1&web=1&e=1rxpMK)

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check installer

**Comment by enarhi** [comment]
@BHoMBot check installer

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Review by enarhi — APPROVED** [review]
LGTM, tested with the test file and opening calcs are correct per spandrel/vision types, and warnings and errors are intuitive.

**Comment by enarhi** [comment]
@BHoMBot check required

**Comment by enarhi** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 16602599617

**Pull request merged**
