### PR TITLE
Verification_Engine added

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1644

   
### Issues addressed by this PR

Supports https://github.com/BHoM/BHoM/issues/1643

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FVerification%5FEngine%2F%233431%2DAddVerification)

### Additional comments

@alelom please note that the GH script mentioned under test files contains a suite of tests that fail to serialise due to a diffing bug - I will try to extract the exact culprit and raise an issue for you to debug. Once the bug gets fixed, I will gladly push UTs for this PR.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by michal-pekacki** [comment]
If we compare two strings with `LessThan` and `GreaterThan` comparison type the result for both is `False` and we have following entry in the report:
image

Should we disable numbering comparisons for strings?

**Comment by pawelbaran** [comment]
Thanks @michal-pekacki, I've just fixed that, returning `null` as inconclusive in such cases 👍

**Comment by michal-pekacki** [comment]
Shouldn't we be consistent and do the same when comparing number to string?
In following entry comparing numeric `ValueSource` with string `ReferenceValues` doesn't return `null`:

image

**Comment by pawelbaran** [comment]
Ha, I disabled comparing numbers to strings now, thanks for another good catch @michal-pekacki 👍  also added test cases

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
