### PR TITLE
Spatial_Engine, Structure_Engine: OrientationAngleBar migrated to Spatial_Engine and renamed to OrientationAngleLinear

### LINKED ISSUE #2336: Structure_Engine, Spatial_Engine: Migrate BH.Engine.Structure.Compute.OrientationAngleBar to BH.Engine.Spatial.Compute.OrientationAngleLinear
#### Description:

As in the title, migration will allow reusing the method for types other than Bar, e.g. IFramingElement, Duct, CableTray etc., which will be really helpful in getting #2322 resolved.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #2336

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FSpatial%5FEngine%2F%232337%2DOrientationAngleLinear%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FSpatial%5FEngine) - only versioning is tested, nothing else had changed effectively. Please remember to rebuild Versioning_Toolkit before testing.

### Changelog

- `OrientationAngleBar` migrated to Spatial_Engine and renamed to `OrientationAngleLinear`

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Review by IsakNaslundBh — COMMENTED** [review]
Have not gotten around to test this yet, but as an initial comments, think we almost might as well move over the area element orientation method to Spatial as well, while doing this. Have the hope that that also will be useful for other disciplines @FraserGreenroyd @michaelhoehn @enarhi

**Comment by pawelbaran** [comment]
@IsakNaslundBh as discussed on the stand-up, I agree with the general concept of moving the method for panels to Spatial_Engine, but I would love to keep this PR as minimalistic as possible - it is one of the few layers of changes that I need to introduce gradually to enable `Transform` methods, so I am very cautious about not getting distracted too much. I hope you will understand 😉

**Review by IsakNaslundBh — APPROVED** [review]
LGTM. Versioning works, and method renaming makes sense

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core

**Comment by IsakNaslundBh** [comment]
Regarding the failing compliance on the modify; This will get fixed together with the batch fixes of SetGeometry, once this is ready to be done based on changes that first needs to happen in other toolkits. Also, is was there before and should not be targeted by this PR.

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
