### PR TITLE
Resolve #821 - exposed to sun parameter

### LINKED ISSUE #821: Environment_Engine: Exposed to Sun not always accurate
The `ExposedToSun` method is not always accurately identifying exterior elements as being exposed to the sun.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #821 

Exposed to Sun parameters resolved

### Test files
See XML toolkit PR for full test files.

#### Fixed
 - Fixed ExposedToSun by string function
#### Added
 - Added ExposedToSun by BuildingElement function

### CODE REVIEW

**Comment by pawelbaran** [comment]
Not sure, but don't we have a naming convention for PRs? How can I know if the Geometry_Engine is blocked?

**Comment by FraserGreenroyd** [comment]
@pawelbaran sorry I somehow managed to delete your comment by mistake when trying to quote it! Quoted below from the email I got instead to show no censorship is deliberately happening!

> Not sure, but don't we have a naming convention for PRs? How can I know if the Geometry_Engine is blocked?

In response - even if I named this `Environment_Engine Fix exposed to sun` there would be no guarantee from the name that I hadn't also modified something in another engine.

There are only 2 ways which can 100% tell you whether another engine has been touched.

1) Check the code changed in this PR against any files in an engine you might care about
2) Ask me - of course if I was making any modifications that would impact another engine it would be on me to make the engine owners aware of that either by reaching out or through the PR text.

Plus, the whole 'blocked' thing is still a ridiculous point given we can resolve pretty much any blocks before getting to the PR stage. I would never advocate that my work blocks anyone else, even myself - I regularly raise a PR and then work on the next bit of work on the Environment_Engine, and would hate to think anyone would be using my PRs as an excuse not to get their work done :wink:

**Comment by pawelbaran** [comment]
Sure thing, it is just easier to browse GitHub when everyone uses  (more or less) same convention + as far as I remember (it was a looooong time ago) we agreed upon [branch naming system](https://github.com/BHoM/documentation/wiki/Resolving-an-Issue#branch-naming-conventions), which was also used for the PRs by many:

**_ProjectName-IssueX-Description_**

However, you are right that it is not stated clear in the guidelines. @al-fisher maybe an update on that?

**Comment by FraserGreenroyd** [comment]
@pawelbaran no apologies needed - better to have the discussion somewhere than nowhere! :smile:

The branch does follow the conventions (barring a description cos I was being quick), and normally if you've made several commits to the branch, GitHub defaults the PR title to be the name of the branch. So by extension, PRs would have followed the same naming convention when people did multiple commits. If there is only a single commit then GitHub takes the PR title from the commit message, which is what it did here - and because it was prefilled I didn't really look to see to change it - I just filled in the template (ticked my boxes that way instead 😛 ).

To confirm however - this PR does not change anything to `Geometry_Engine` so you shouldn't be blocked by it hopefully :smile:

**Comment by pawelbaran** [comment]
My trick for branch/PR naming is to name the branch in a sensible way and then copy-paste its name into the PR header - see my contributions for examples ;-)

**Pull request merged**
