### PR TITLE
Matter_Engine: Add missing PreviousVersion Attributes

### LINKED ISSUE #2933: Matter_Engine: Missing PreviousVersion Attributes
#### Broken rules:

https://github.com/BHoM/BHoM_Engine/pull/2897 did not correctly apply the required PreviousVersion attributes required for Versioning

#### Suggestions to restore compliance:

Add the attributes

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2933

Adds PreviousVersion attributes that were missed in https://github.com/BHoM/BHoM_Engine/pull/2897

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by pawelbaran — APPROVED** [review]
The change makes perfect sense - thanks for catching @IsakNaslundBh

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, installer, null-handling, serialisation, unit-tests, ready-to-merge, versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

**Pull request merged**
