### PR TITLE
BHoM_Engine: replaced C:/ProgramData with SpecialFolder construct

### LINKED ISSUE #3218: BHoM_Engine: BHoM Folder points directly to the C:
https://github.com/BHoM/BHoM_Engine/blob/034bd82ab020f3a1eb09c87013901ee7f43342c5/BHoM_Engine/Query/BHoMFolder.cs#L36

It should make use of the Special Folder construct to obtain the `ProgramData` folder to allow for non-C:/ users

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #3218 

replaced reference to C: so that users not using C: can use the BHoM.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
Looks good, aligns with our desire to not rely on a `C:` existing on users machines as a pre-requisite for using BHoM, thanks @Tom-Kingstone

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 19065876442

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
