### PR TITLE
BHoM_Engine: Replace \\ in description attributes with /

### LINKED ISSUE #3227: BHoM_Engine: replace `\` in description attributes with `/`
`\` is an escape character in json, so needs to be replaced with `/`

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #3227 

Description attributes which referred to file paths now use `/` instead of `\\` as there are some json issues during beta deployment.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
Thanks @Tom-Kingstone - will make my life easier at the end of the milestone 😄

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Pull request merged**
