### PR TITLE
.ci: Remove failing unit tests pending upgrade

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Removes 2 failing unit tests that need upgrading but can be done at a separate point by people best placed to do so.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Review by jamesramsden-bh — APPROVED** [review]
Approved on the basis that appropriate code owners are contacted to replace with working tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
