### PR TITLE
Facade_Engine: Add Key Methods for Facades Workflows

### LINKED ISSUE #2199: Facade_Engine: Add key methods for facades workflows
#### Description:
Required methods include:

- Compute.UniqueAdjacencies
- Query.OpeningAreas (Frame, Edge of Glass, Center of Glass with input for code based edge of glass width)
- Modify.AssignFrameEdgePropertiesBy*
- Compute.WindowWallRatio+

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #2199 

- Added methods for solving element adjacencies and identifying unique adjacencies amongst a set of objects
- Added methods for facade-workflow related area calculations

### Test files
[201204-TestFacadeEngineAdjacencyAndAreaMethods.zip](https://github.com/BHoM/BHoM_Engine/files/5646190/201204-TestFacadeEngineAdjacencyAndAreaMethods.zip)

Test files allow for testing unique adjacencies / edge adjacency detection as well as area breakdowns of elements / collections of elements. Suggest manipulating and adding / removing geometry to the rhino file to further test functionality.

### CODE REVIEW

**Comment by enarhi** [comment]
@FraserGreenroyd  I am still adding a couple methods but wanted to get this on your radar for preliminary code and compliance review. Let me know if you have any questions, otherwise I'll pick up any review comments ASAP alongside adding said methods so that we can get this PR sorted by the feature add deadline.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@FraserGreenroyd this is good to go now. @ben-martinson we will go over functionality testing tomorrow am so you can review this. @al-fisher just a heads up this one should be ready to go around 12 PST tomorrow.

**Comment by enarhi** [comment]
@BHoMBot check installer please

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Review by FraserGreenroyd — APPROVED** [review]
Some compliance issues and some things to discuss with @IsakNaslundBh next milestone, I think a few of the methods would be well suited for the Spatial_Engine, but am happy to approve this for now to get in before feature freeze to unblock you as discussed @enarhi :smile:

**Pull request merged**
