### PR TITLE
Minor fixes required for BHoM UI refactoring

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

See https://github.com/BHoM/BHoM_UI/pull/297 for details

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
Discussion with @adecler @IsakNaslundBh @alelom @rolyhudson and @AndreBalasian this morning, this PR is going to be reviewed by @IsakNaslundBh and myself with a view to merge to ease up people reviewing the UI PRs which depend on this while people continue working on the Engine but can run usability tests through the UIs.

**Review by IsakNaslundBh — APPROVED** [review]
Have not noticed any issues with this PR, and solves a bug with explode for dictionaries.

Will let @FraserGreenroyd also approve before merging.

**Review by FraserGreenroyd — APPROVED** [review]
Have been using this branch this morning during other things, have not noticed any adverse reactions to master branch of Grasshopper so happy to merge as discussed to allow more testing/uptake of the UI branches :smile:

**Pull request merged**
