### PR TITLE
Facade_Engine: Added continuous UValue Calc to SAM method and Overarching UValue Methode for Collections of Elements

### LINKED ISSUE #3434: Facade_Engine: Add U Value methods for general UValue assessment of FacadeElements leveraging existing specific methods per type/method used
#### Description:
As per the title, we would like to add general methods that accept a list of facade elements and return the UValue (total and per element) as per the specified method to use. This will allow us to easily evaluate various facade systems for thermal performance using the same method.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #3434 

Added continuous UValue to SAM Method, and added parent methods to get collective UValues for any collection of FacadeElements.

### Test files
[Test Script](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%233434-OverallUValueMethods/%233434-CheckFacadeEngineUValueMethods.gh?csf=1&web=1&e=hU9YQe)

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check required

**Review by vgreen-BH — APPROVED** [review]
Tested against linked script. Everything worked as expected.

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Comment by enarhi** [comment]
@BHoMBot check unit-tests

**Pull request merged**
