### PR TITLE
Reflection_Engine: Extract descriptions of enum options

### LINKED ISSUE #1584: Reflection_Engine: Get Enum item options and Descriptions
#### What is missing/incorrect?

Add method to get all enum options and descriptions (if any) for enum descriptions.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #1584 

Adding the options of the enums, and their inner descriptions, to the description text of an enum. Enum values and text below added:

image

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@FraserGreenroyd Thought about that, but thought it never would get tooo bad. But could put a limit of say 10 items, and state something like "...and more" after.

Do you have an example of a really long enum, so I can check how it looks?

**Comment by FraserGreenroyd** [comment]
@IsakNaslundBh I would support an `and more` option - Environment Space Type is the first one that springs to mind as being a bit on the longer side.

**Comment by IsakNaslundBh** [comment]
BHoM_Engine.CheckCompliance

**Pull request merged**
