### PR TITLE
MEP_Engine: Organisation of MEP Namespaces

### LINKED ISSUE #2125: MEP_Engine: Namespaces Changes to Reflect oM Changes
#### Description
Reflect oM namespace changes from:
https://github.com/BHoM/BHoM/pull/1063

Removal of SetGeometry method due to use of Geometry methods (Points) being used in lieu of previous MEP Node

### PR DESCRIPTION
**Pull request by michaelhoehn**
### NOTE: Depends on:
https://github.com/BHoM/BHoM/pull/1069

   
### Issues addressed by this PR 

Closes #2125 

### Test files

[Here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/MEP_oM/MEP_oM-%231041_Namespace%20Updates.gh?csf=1&web=1&e=jI9bbC)

### Additional comments
@michaelhoehn please review applicability of the Query Centreline Method and Geometry Method

### CODE REVIEW

**Review by kayleighhoude — DISMISSED** [review]
Happy with the changes, particularly the query methods that dealt with nodes previously

**Comment by michaelhoehn** [comment]
@BHoMBot check code compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check code compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check documentation compliance

**Comment by michaelhoehn** [comment]
@BHoMBot fix documentation punctuation ref. 1387769318

**Comment by FraserGreenroyd** [comment]
@BHoMBot check documentation compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check documentation compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check documentation compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check installer bro

**Review by FraserGreenroyd — APPROVED** [review]
LGTM

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]

**Pull request merged**
