### PR TITLE
Reflection_Engine: Make it easy to clear the value of a property

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 

Needed for this PR in BHoM_UI:  https://github.com/BHoM/BHoM_UI/pull/334

   
### Issues addressed by this PR

See BHoM_UI PR

### CODE REVIEW

**Review by pawelbaran — DISMISSED** [review]
LGTM

**Comment by adecler** [comment]
Had to rebase because of this:

image

I have never seen that one before so not even sure that rebasing will solve it

**Review by pawelbaran — APPROVED** [review]
Still LGTM

**Pull request merged**
