### PR TITLE
Geometry Engine: PointAtParameter(Polyline) sometimes returns null on parameter equal 1.0

### LINKED ISSUE #2043: Geometry_Engine: PointAtParameter(Polyline) sometimes return null when given parameter equals 1.0
#### Description:

Due to the computational error point at 1.0 parameter is sometimes outside the curve and then the method returns null.

#### Steps to reproduce:

The only known case occurred deep inside other method so it's hard to reproduce.

#### Expected behaviour:

Should return endpoint.

#### Test file(s):

As in Steps to reproduce.

### PR DESCRIPTION
**Pull request by LMarkowski**
### Issues addressed by this PR

Closes #2043 

Adding a quick fix to the PointAtParameter method for `Polyline` class which matches the one added once to the `PolyCurve` one.

Both will be probably replaced by using tolerance while resolving #2044.

### Test files

The issue itself occurred only once, deep inside another method so it's hard to isolate it to the specific test file.
[Here](https://burohappold.sharepoint.com/:f:/s/BHoM/Esd2eZj9Hc1Mkh5tar8m-NsBlIxJtyJ40zXatKwF4D3uOQ?e=aAy2n2) is the generic `PointAtParameter` test to ensure that the fix doesn't break anything. (Test for the Circle class need to be fixed, out of scope this PR)

### Changelog

- Modified `PointAtParameter` method for `Polyline` class in the `Geometry_Engine`
 
### Additional comments

This will unfortunately interfere with #2028 by editing the same file, but is necessary to resolve [#48](https://github.com/BHoM/TriangleNet_Toolkit/issues/48)

### CODE REVIEW

**Review by pawelbaran — APPROVED** [review]
LGTM, happy as an interim fix

**Comment by pawelbaran** [comment]
I would consider adding same checks to `parameter == 0` for `Polyline` and `PolyCurve` too - @LMarkowski, does that make sense?

**Comment by LMarkowski** [comment]
@pawelbaran hm, I can't see a case for which it could crash for `parameter == 0` but it could save as a tiny bit on computation time and make the code more transparent.
I'm pushing a commit then.

**Review by pawelbaran — CHANGES_REQUESTED** [review]
Looks like you've pushed too much @LMarkowski 🙈

**Comment by LMarkowski** [comment]
@pawelbaran, yes. Accidentally pushed all my stashed changes 🤦
fixed.

**Review by pawelbaran — APPROVED** [review]
LGTM as interim fix 👍

**Review by al-fisher — APPROVED** [review]
Makes sense as discussed

**Pull request merged**
