### PR TITLE
Structure_Engine: Add more unittests

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, code-compliance, copyright-compliance, dataset-compliance, documentation-compliance, installer, null-handling, project-compliance, ready-to-merge, serialisation, versioning

**Review by FraserGreenroyd — APPROVED** [review]
Only adding unit tests which is great, have looked through them with @IsakNaslundBh as code owner and am happy that he's happy with the level of detail included in these tests.

**Pull request merged**
