### PR TITLE
Environment_Engine: Remove FindFragment

### LINKED ISSUE #2747: Environment_Engine: Remove FindFragment
https://github.com/BHoM/BHoM_Engine/blob/main/Environment_Engine/Query/FindFragment.cs

Use versioning on the Base_Engine/Query/FindFragment.cs file to version from this method to that.

Versioning key should be:

`[PreviousVersion("5.1", "BH.Engine.Environment.Query.FindFragment(BH.oM.Environment.IEnvironmentObject, System.Type)")]`

### PR DESCRIPTION
**Pull request by robinflyman**
Closes #2747 

Versioned and removed FindFragment.

### CODE REVIEW

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
The Environment Engine file needs deleting.

**Comment by jamesramsden-bh** [comment]
@BHoMBot check installer

**Comment by robinflyman** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 5159426915

**Pull request merged**
