### PR TITLE
Data_Engine: Requests method moved to Query class

### LINKED ISSUE #2332: Data_Engine: Requests method is in the wrong class
#### Description:

These the method is a query, it is in Query folder, but the class is `Modify` 🐒 
https://github.com/BHoM/BHoM_Engine/blob/2761083ed5771eee3c642544cbc73e9f1e5f8b6f/Data_Engine/Query/Requests.cs#L29-L31

**IMPORTANT:** the change will require versioning.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #2332

### Test files

Versioning tested [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FData%5FEngine%2FData%5FEngine%2D%232385%2DRequestsInWrongClass%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FData%5FEngine) - please remember about rebuilding Versioning_Toolkit.

### Changelog

- `Requests` method moved to `Query` class

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check serialisation

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Review by FraserGreenroyd — APPROVED** [review]
LGTM, versioning report looks good.

**Pull request merged**
