### PR TITLE
Diffing_Engine: reworked the NumericTolerance mechanism

### LINKED ISSUE #3039: Diffing_Engine: implementation of `NumericalDifferenceInclusion` Tolerance approximation to be reviewed
#### Description:

(Edited by @alelom)

Currently, the Diffing uses a numerical comparison mechanism implemented in the `NumericalDifferenceInclusion()` method. This method has 2 distinct numerical approximation mechanisms that can be invoked for numerical comparisons: **_Tolerance_** and _**SignificantFigures**_.

The **_Tolerance_** approximation mechanism is implemented like so: when two numbers are passed to the method `NumericalDifferenceInclusion()` method, they are individually rounded down using the specified tolerance, and then compared between each other. If they are found different, the method returns true (i.e. they are seen as different by the Diffing), otherwise false. 

https://github.com/BHoM/BHoM_Engine/blob/8faa8506938ae18ee4c321bbacb867eb35b892dd/Diffing_Engine/Query/NumericalDifferenceInclusion.cs#L86-L91

This logic is not correct. When an user uses the Tolerance, they expect the _difference_ between the number to be compared against the Tolerance.

Instead, the above logic is correct when using the **_SignificantFigures_** approximation. This considers how many significant figures should be accounted for when comparing numbers (use case example: engineers only account for significant figures when comparing large forces). 

#### Proposed changes
When using a numeric tolerance, the logic should instead be: compute the difference between the numbers, then see if it is larger than the specified tolerance.

#### Test File:
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%231349%2DParameterDiffingToleranceBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #3039

Reworked the NumericalTolerance mechanism to compute the difference between the numbers, then see if it is larger than the specified tolerance.

### Test files

See #3039.

### CODE REVIEW

**Review by pawelbaran — COMMENTED** [review]
Code changes make sense to me, but I am getting errors in tests:

<details>

image

</details>

**Comment by alelom** [comment]
> Code changes make sense to me, but I am getting errors in tests

Thanks, I missed to update the older tests to the new mechanism. See the PR: https://github.com/BHoM/DiffingTests_Prototypes/issues/11

**Comment by alelom** [comment]
@BHoMBot check core

**Comment by alelom** [comment]
@BHoMBot check required

**Review by pawelbaran — APPROVED** [review]
All tests passed, also successfully tested on actual sample problems.

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests

**Pull request merged**
