### PR TITLE
Geometry_Engine: split at self intersections method added

### LINKED ISSUE #3291: Geometry_Engine: add SplitSelfIntersecting(Polyline) method
#### Description:

Following [this comment](https://github.com/BHoM/BHoM_Engine/pull/3283#issuecomment-1959782728), `SplitSelfIntersecting(Polyline)` can be added almost for free.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3291

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%233292%2DSplitAtSelfIntersections&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by vietle-bh — APPROVED** [review]
It works great both in the test script and in a tool I'm building!

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
Happy with the test script, msall changes to descriptions.

**Review by peterjamesnugent — APPROVED** [review]
Happy my comments have been addressed without any changes to the method itself.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, installer, null-handling, serialisation, versioning, unit-tests, ready-to-merge

**Comment by FraserGreenroyd** [comment]
I have dispensated the checks as they had passed prior to the final change which was documentation only.

**Pull request merged**
