### PR TITLE
Reflection_Engine: support methods for legacy attributes removed

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1577

   
### Issues addressed by this PR

Closes #

### Test files

See https://github.com/BHoM/BHoM/pull/1577.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
Approving based on oM review and code review. Thanks @pawelbaran

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Pull request merged**
