### PR TITLE
Base_Engine: Remove Base Engine Set Geometry method

### LINKED ISSUE #1754: Base_Engine: The set geometry method in BHoM_Engine does not do anything
#### Description:

The method does a dynamic cast call to an method that returns the obejcts. Should either be fixed or removed as it currently is confusing rather than adding value

#### Steps to reproduce:

Try using the SetGeometry method in the base BHoM_Engine.

#### Expected behaviour:

For it to either work or not exist.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #1754

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by jamesramsden-bh — APPROVED** [review]
Have tested and confirmed that the removed component indeed does nothing useful! Happy to have it removed. Versioning looks fine, and to be confirmed by the bot.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning, unit-tests, ready-to-merge

**Pull request merged**
