### PR TITLE
Environment_Engine: UX improvement on panel creation

### LINKED ISSUE #3096: BHoM Environment Panels from BREP failed to run properly
#### Description:

Panels from BREP sometimes fails to produce panels from input BREPs. 

image

Input BREPs
image

Output Panels
image

As a workaround, using Edges works as expected
image

#### Steps to reproduce/Test file:

Example geometry in this file.
[ExamplePanelsFromBREPsError.zip](https://github.com/BHoM/BHoM_Engine/files/11871723/ExamplePanelsFromBREPsError.zip)

### LINKED ISSUE #3142: Geometry_Engine: Missing fall back method for Internal edges
Per title, this results in a `RuntimeBinderException` being thrown if, for example, you call the `IInternalEdges` method with a `NurbsSurface`. Related to #3096

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #3096 
Fixes #3142

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by EKAdebo — APPROVED** [review]
Pair programmed together with @FraserGreenroyd and code works as expected following investigations noted in #3096

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer -quick

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning, code-compliance, unit-tests, ready-to-merge

**Comment by FraserGreenroyd** [comment]
Versioning failures are not related to this PR. Check dispensated for time being.

**Pull request merged**
