### PR TITLE
Reflection_Engine: Adding null handling

### LINKED ISSUE #2447: Serialiser_Engine & Reflection_Engine: Handle nulls
For the following reported methods to help clean the noise:

- [x] BH.Engine.Serialiser.Create.MethodBase(Type type, String methodName, List<String> paramTypeNames)
- [x] BH.Engine.Serialiser.Create.MethodBase(Type type, String methodName, List<Type> paramTypes)
- [x] BH.Engine.Serialiser.Query.GenericTypeConstraint(Type type)
- [x] BH.Engine.Serialiser.Query.ParametersWithConstraints(MethodBase method)
- [x] BH.Engine.Reflection.Compute.MakeGenericFromInputs(MethodInfo method, List<Type> inputTypes)
- [x] BH.Engine.Reflection.Compute.RecordEvent(Event newEvent)
- [x] BH.Engine.Reflection.Convert.ToFunc(MethodInfo method)
- [x] BH.Engine.Reflection.Convert.ToFunc(ConstructorInfo ctor)
- [x] BH.Engine.Reflection.Create.MethodInfo(Type declaringType, String methodName, List<Type> paramTypes)
- [x] BH.Engine.Reflection.Modify.MakeFromGeneric(Type genericType)
- [x] BH.Engine.Reflection.Modify.MakeFromGeneric(MethodInfo genericMethod)
- [x] BH.Engine.Reflection.Modify.SetPropertyValue(Object obj, String propName, Object value)
- [x] BH.Engine.Reflection.Query.UsedMethods(MethodBase method, Boolean onlyBHoM)
- [x] BH.Engine.Reflection.Query.InputDescriptions(MethodBase method)
- [x] BH.Engine.Reflection.Query.Path(Type type)
- [x] BH.Engine.Reflection.Query.Path(MethodBase method, Boolean userReturnTypeForCreate, Boolean useExtentionType)
- [x] BH.Engine.Reflection.Query.Description(ParameterInfo parameter, Boolean addTypeDescription)
- [x] BH.Engine.Reflection.Query.Description(QuantityAttribute quantity)
- [x] BH.Engine.Reflection.Query.PropertyDictionary(Object obj)
- [x] BH.Engine.Reflection.Query.PropertyDictionary(CustomObject obj)
- [x] BH.Engine.Reflection.Query.PropertyNames(Object obj)
- [x] BH.Engine.Reflection.Query.PropertyNames(Type type)
- [x] BH.Engine.Reflection.Query.PropertyObjects(Object obj, Boolean goDeep)
- [x] BH.Engine.Reflection.Query.PropertyObjects(IEnumerable<Object> objects, Type type)
- [x] BH.Engine.Reflection.Query.PropertyTypes(Object obj, Boolean goDeep)
- [x] BH.Engine.Reflection.Query.PropertyTypes(Type type, Boolean goDeep)
- [x] BH.Engine.Reflection.Query.ImplementingTypes(Type interface)
- [x] BH.Engine.Reflection.Query.IsAssignableFromIncludeGenerics(Type assignableTo, Type assignableFrom)
- [x] BH.Engine.Reflection.Query.NestedMethods(Type type)
- [x] BH.Engine.Reflection.Query.IsAutoGenerated(Type type)
- [x] BH.Engine.Reflection.Query.IsInterfaceMethod(MethodBase method)
- [x] BH.Engine.Reflection.Query.PropertyAbbreviation(Object obj, String propName)
- [x] BH.Engine.Reflection.Query.UsedAssemblies(Assembly assembly, Boolean onlyBHoM, Boolean goDeep)
- [x] BH.Engine.Reflection.Query.UsedNamespaces(MethodBase method, Boolean onlyBHoM, Int32 maxDepth)
- [x] BH.Engine.Reflection.Query.UsedNamespaces(Type type, Boolean onlyBHoM, Int32 maxDepth)
- [x] BH.Engine.Reflection.Query.InheritedTypes(Type type, Boolean onlyBHoM)
- [x] BH.Engine.Reflection.Query.UsedTypes(MethodBase method, Boolean onlyBHoM)
- [x] BH.Engine.Reflection.Query.UsedTypes(Type type, Boolean onlyBHoM, Boolean inheritedTypes)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2447

### Additional comments
@adecler please check you're happy with the return options and messages. Please suggest changes (and feel free to commit, happy to co-author this solution) as appropriate :smile:

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2289724987

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by adecler** [comment]
@FraserGreenroyd , I have done a series of corrections on your initial commits (see my commit above this comment). Here's the general trend in my changes:
- Added a few more null checks when missing
- Modified the returned type from null to something more appropriate in case on null input. As the reflection engine is at a very low level, the handling of nulls need to be often considered as part of the normal flow. I a lot of cases, they can just be considered closer to something as an empty object and should therefore return a similar output.
- Modified quite of few of the error records to warning records. Same reason as above. You might notice that there are even cases where I don't even return a warning because a null can be handled in a fairly logical manner. I have kept most of the warnings you have created though. I have tried to consider the impact on each of them on the UI experience but it might still be possible that we will have to remove some of them in the future if I missed something.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by adecler** [comment]
@FraserGreenroyd , it looks like the null-handling check is running on more than just the modified files. 
I am not entirely sure where this increase in the number of failing test is coming from though. A quick search on the results tells me that none of Reflections method are failing a null test.

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd , it looks like the null-handling check is running on more than just the modified files.
> I am not entirely sure where this increase in the number of failing test is coming from though. A quick search on the results tells me that none of Reflections method are failing a null test.

Yeah I think the bot is having issues again with the tunnelling. I've just tried rebooting the bot again and have run the checks locally and agree with you, none of the reflection stuff is failing so the bot is having an off-day. I'm going to dispensate the check for now because this PR does improve the situation from our manual checks.

Also to confirm, I'm happy with your changes :smile:

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2304366977

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by adecler — DISMISSED** [review]
Approving based on the fact that @FraserGreenroyd and I are both happy with each other's changes.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
Ok today was definitely a day to stay in bed...

image

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
🤦‍♂️

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Review by adecler — APPROVED** [review]

**Pull request merged**
