### PR TITLE
BHoM_Engine: Add ParseEnum method for int value and add ignoreCase option for string conversion

### LINKED ISSUE #3119: BHoM_Engine string to enum converter
#### Description:

It would be useful to have the method in the Engine that can convert string to enum. It should take the string and the enum type as inputs, look up the string in the enum list and return value as an enum. Would be good to include 'ignore case' setting with a default value set to 'True'.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #3119

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by EKAdebo — APPROVED** [review]
Tested this code and it works as expected. LGTM, LGTM!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning, unit-tests, ready-to-merge

**Pull request merged**
