### PR TITLE
Versioning_Engine: Add a VersioningEvents() and a VersioningKey(BsonDocument) method

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 

https://github.com/BHoM/Versioning_Toolkit/pull/159
https://github.com/BHoM/BHoM/pull/1237
   
### Issues addressed by this PR

This PR is done within the context of solving this issue: https://github.com/BHoM/BHoM_UI/issues/389

This provides basic functionality that will be used in the related BHoM_UI PR as well as a method that facilitate the access to the versioning events in the UI:

image

### Test files
Either open an outdated script or try to deserialise outdated json before runnign the component above. Here's a few json representations of items that have been versioned since they were saved:

```
{ "_t" : "System.Reflection.MethodBase", "TypeName" : "{ \"_t\" : \"System.Type\", \"Name\" : \"BH.Engine.Architecture.Modify, Architecture_Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null\" }", "MethodName" : "SetGeometry", "Parameters" : ["{ \"_t\" : \"System.Type\", \"Name\" : \"BH.oM.Architecture.Elements.Grid\" }", "{ \"_t\" : \"System.Type\", \"Name\" : \"BH.oM.Geometry.ICurve\" }"] }
```

```
{ "_t" : "System.Reflection.MethodBase", "TypeName" : "{ \"_t\" : \"System.Type\", \"Name\" : \"BH.Engine.Environment.Query, Environment_Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null\" }", "MethodName" : "Tilt", "Parameters" : ["{ \"_t\" : \"System.Type\", \"Name\" : \"BH.oM.Geometry.Polyline\" }"] }
```

```
{ "_t" : "System.Reflection.MethodBase", "TypeName" : "{ \"_t\" : \"System.Type\", \"Name\" : \"BH.Engine.Adapters.XML.Query, XML_Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null\" }", "MethodName" : "ConstructionID", "Parameters" : ["{ \"_t\" : \"System.Type\", \"Name\" : \"BH.oM.Environment.Elements.Panel\" }"] }
```

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
See the review on [this PR](https://github.com/BHoM/BHoM_UI/pull/390)

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2573852961

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2573852756

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
