### PR TITLE
Serialiser_Engine: Fix ToJson for null Name property

### LINKED ISSUE #2938: Serialiser_Engine: Bug when converting object with null name property
#### Description:
Converting an object `ToJson` with a `null` `Name` property results in an `NullReferenceException` being thrown, and preventing the JSON string being created.

#### Steps to reproduce:
Convert an object with a `null` `Name` property `ToJson`.

#### Expected behaviour:
Error is not thrown, conversion to JSON continues.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2938 

### Test files
```
{
	Name: null
}
```

Try converting this JSON string `FromJson` and then immediately `ToJson` on `main` and then on this PR. You should find it throws an error on `main` but this branch will continue.

image

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests
@BHoMBot check core
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation
@BHoMBot check versioning

**Review by adecler — APPROVED** [review]
Tested on the example provided and can this PR fixes the issue.
Code change makes sense.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
