### PR TITLE
Settings_Engine: Fix output path

### LINKED ISSUE #3162: Settings_Engine: Output not set to ..\Build\
Causing an issue with Nugets - can't scrape the DLL if it can't be found in the right folder...

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #3162

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Review by enarhi — APPROVED** [review]
LGTM as per visual inspection.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: installer, null-handling, ready-to-merge, serialisation, unit-tests, versioning

**Pull request merged**
