### PR TITLE
Structure_Engine: Remove duplicate methods from structure engine

### LINKED ISSUE #682: Structure_Engine: Area(PanelPlanar) coincides with Area(IElement2D) in Common
It possibly could be removed

### LINKED ISSUE #686: Structure_Engine: ControlPoints to be Deprecated as coincides with same method in Common
It possibly could be removed

### LINKED ISSUE #688: Structure_Engine: Query.Edges could possibly be cleaned up
Common_Engine contains following methods for IElement2D:
ElementCurves
OutlineElements1D
OutlineCurve

Can't these be used instead some of the methods in Edges.cs file?

### LINKED ISSUE #690: Structure_Engine: Query.Length should be moved to Spatial_Engine
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

### LINKED ISSUE #691: Structure_Engine: Query.Outline coincides with Query.OutlineCurve in Common
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

### LINKED ISSUE #2135: Structure_Engine: Remove dupliacte methods from engine
#### Broken rules:

Collection issue of many small issues raised before:

#690 
#682 
#688 
#691 
#686 

Also adding in a few more. All methods that have duplicates in either Analytical_Engine or Spatial_Engine should be removed from the Structure_Engine.

The following methods have been identified:

- BH.Engine.Structure.Query.Area(BH.oM.Structure.Elements.Panel)
- BH.Engine.Structure.Query.Area(BH.oM.Structure.Elements.Opening)
- BH.Engine.Structure.Query.AllEdgeCurves(BH.oM.Structure.Elements.Panel)
- BH.Engine.Structure.Query.ControlPoints(BH.oM.Structure.Elements.Panel, System.Boolean)
- BH.Engine.Structure.Query.ControlPoints(BH.oM.Structure.Elements.Opening)
- BH.Engine.Structure.Query.ControlPoints(System.Collections.Generic.List<BH.oM.Structure.Elements.Edge>)
- BH.Engine.Structure.Query.ControlPoints(BH.oM.Structure.Elements.Bar)
- BH.Engine.Structure.Query.EdgeCurves(BH.oM.Structure.Elements.Opening)
- BH.Engine.Structure.Query.ExternalEdgeCurves(BH.oM.Structure.Elements.Panel)
- BH.Engine.Structure.Query.Elements0D(BH.oM.Structure.Elements.Bar)
- BH.Engine.Structure.Query.Geometry(BH.oM.Structure.Elements.Node)
- BH.Engine.Structure.Query.Geometry(BH.oM.Structure.Elements.Bar)
- BH.Engine.Structure.Query.Geometry(BH.oM.Structure.Elements.Edge)
- BH.Engine.Structure.Query.Geometry(BH.oM.Structure.Elements.Surface)
- BH.Engine.Structure.Query.Geometry(BH.oM.Structure.Elements.Panel)
- BH.Engine.Structure.Query.Geometry(BH.oM.Structure.Elements.FEMesh)
- BH.Engine.Structure.Query.Geometry(System.Collections.Generic.IEnumerable<BH.oM.Structure.Elements.FEMeshFace>)
- BH.Engine.Structure.Query.Geometry(BH.oM.Structure.Elements.FEMeshFace)
- BH.Engine.Structure.Query.InternalEdgeCurves(BH.oM.Structure.Elements.Panel)
- BH.Engine.Structure.Query.InternalElements2D(BH.oM.Structure.Elements.Panel)
- BH.Engine.Structure.Query.Length(BH.oM.Structure.Elements.Bar)
- BH.Engine.Structure.Query.Outline(BH.oM.Structure.Elements.Panel)
- BH.Engine.Structure.Query.Outline(BH.oM.Structure.Elements.Opening)
- BH.Engine.Structure.Query.Outline(System.Collections.Generic.List<BH.oM.Structure.Elements.Edge>)
- BH.Engine.Structure.Query.OutlineElements1D(BH.oM.Structure.Elements.Opening)
- BH.Engine.Structure.Query.OutlineElements1D(BH.oM.Structure.Elements.Panel)
- BH.Engine.Structure.Modify.SetGeometry(BH.oM.Structure.Elements.Node, BH.oM.Geometry.Point)
- BH.Engine.Structure.Modify.SetGeometry(BH.oM.Structure.Elements.Bar, BH.oM.Geometry.ICurve)
- BH.Engine.Structure.Modify.SetGeometry(BH.oM.Structure.Elements.Edge, BH.oM.Geometry.ICurve)
- BH.Engine.Structure.Modify.SetGeometry(BH.oM.Structure.Elements.Surface, BH.oM.Geometry.ISurface)
- BH.Engine.Structure.Modify.SetInternalElements2D(BH.oM.Structure.Elements.Panel, System.Collections.Generic.List<BH.oM.Dimensional.IElement2D>)
- BH.Engine.Structure.Modify.SetOutlineElements1D(BH.oM.Structure.Elements.Opening, System.Collections.Generic.List<BH.oM.Dimensional.IElement1D>)
- BH.Engine.Structure.Modify.SetOutlineElements1D(BH.oM.Structure.Elements.Panel, System.Collections.Generic.List<BH.oM.Dimensional.IElement1D>)
- BH.Engine.Structure.Create.NewInternalElement2D(BH.oM.Structure.Elements.Panel)

#### Suggestions to restore compliance:

Remove the above method, and add versioning to their new target methods.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #690
Closes #682
Closes #688
Closes #691
Closes #686
Closes #2135 

Removes all duplicate methods from structure engine

### Test files

versioning tests:

https://burohappold.sharepoint.com/:f:/s/BHoM/EqppgtmwOHpNv6TyaBlC7mUBKkZZiTAWlJXYPspiUKhOUQ?e=sLqRzs

IElement tests

https://burohappold.sharepoint.com/:f:/s/BHoM/EknHCkxzC1dNm3LoOI4nSmYBexQH3dGhGtoOZWr-yhy2hg?e=P01O07

### Additional comments

@al-fisher @rolyhudson @FraserGreenroyd @alelom @pawelbaran @LMarkowski FYI, I had to update Analytical and Spatial Engines with previous method attributes to be able to get rid of all the stuff from structures. Just to make you aware of any potential clashes if you were planning to work on those engines. (I looked at your PR @rolyhudson, and could not spot any place were we wanted to change the same files, so should be fine, but would be great if you could double check)

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
Running bhom bot check installer to investigate impact of the changes in this PR

**Comment by IsakNaslundBh** [comment]
Know a few are still outstanding and this will fail, but to testing again @BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check project compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check code compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check documentation compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check documentation compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot fix documentation punctuation ref. 1395326069

**Comment by IsakNaslundBh** [comment]
@BHoMBot fix documentation punctuation ref. 1395326069

**Comment by IsakNaslundBh** [comment]
@BHoMBot fix documentation punctuation ref. 1395326069

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix documentation punctuation ref. 1395326069

**Comment by IsakNaslundBh** [comment]
@BHoMBot fix documentation punctuation ref. 1395326069

**Comment by IsakNaslundBh** [comment]
@BHoMBot fix documentation punctuation ref. 1395326069

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
_Issue2153-RemoveDuplicateMethodsFromStructureEngine.gh_
This is coming from `OutlineCurve` with `Edge` inputs.
image

_BuroHappold_BHoM_v3.3.beta_Structures_ML_BasicWorkFlow.gh_
There's a floating `IsInBounds()` component, shouldn't have been affected by the versioning in this PR but flagging just in case.
image

This warning appeared a few times but nothing to be alarmed about:
> 1. The internal edges overlap with the external.Boolean intersection has been used to try to get out the correct geometry.Topology might have changed for the surface obejct

**Comment by IsakNaslundBh** [comment]
> _Issue2153-RemoveDuplicateMethodsFromStructureEngine.gh_
> This is coming from `OutlineCurve` with `Edge` inputs.

Dont think there is anything I can do about that in this PR. Something in GH failing with the versioning.

> _BuroHappold_BHoM_v3.3.beta_Structures_ML_BasicWorkFlow.gh_
> There's a floating `IsInBounds()` component, shouldn't have been affected by the versioning in this PR but flagging just in case.

Not touched by this, so if the rest of the script is working, would not worry about that one.

> This warning appeared a few times but nothing to be alarmed about as it is part of the method rather than anything impacted the scope of this PR:
> 
> > 1. The internal edges overlap with the external.Boolean intersection has been used to try to get out the correct geometry.Topology might have changed for the surface obejct

Yeah, it is a pre-existing issue. As long as all methods in the are being called and things are generally functioning, that can be ignored.

**Review by peterjamesnugent — APPROVED** [review]
Based on the below justification, LGTM.

> > _Issue2153-RemoveDuplicateMethodsFromStructureEngine.gh_
> > This is coming from `OutlineCurve` with `Edge` inputs.
> 
> Dont think there is anything I can do about that in this PR. Something in GH failing with the versioning.
> 
> > _BuroHappold_BHoM_v3.3.beta_Structures_ML_BasicWorkFlow.gh_
> > There's a floating `IsInBounds()` component, shouldn't have been affected by the versioning in this PR but flagging just in case.
> 
> Not touched by this, so if the rest of the script is working, would not worry about that one.
> 
> > This warning appeared a few times but nothing to be alarmed about as it is part of the method rather than anything impacted the scope of this PR:
> > > 1. The internal edges overlap with the external.Boolean intersection has been used to try to get out the correct geometry.Topology might have changed for the surface obejct
> 
> Yeah, it is a pre-existing issue. As long as all methods in the are being called and things are generally functioning, that can be ignored.

**Pull request merged**
