### PR TITLE
Environment_Engine: Fix bug in MapRegions for wholly contained regions

### LINKED ISSUE #2121: Environment_Engine: MapRegions method does not work for regions wholly contained
Found by @rboulton-BH that a region entirely contained by an outer region, is not picked up.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2121

### CODE REVIEW

**Review by JohannaOlin1 — CHANGES_REQUESTED** [review]
Need to test for doubled regions before merging

**Comment by FraserGreenroyd** [comment]
Following testing with @JohannaOlin1 discovered that regions which overlapped slightly, and were wholly contained, were getting caught twice by the first iteration of the fix. We're now taking distinct items only after doing all the checks for the things we think we want to match to.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check documentation compliance

**Review by JohannaOlin1 — APPROVED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check documentation compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Pull request merged**
