### PR TITLE
Settings_Engine: Add LoadSettings method for loading a single settings file

### LINKED ISSUE #3299: Settings_Engine: Ability to load single JSON file settings into memory
Add ability to load a single JSON file which may contain a settings object in BHoM serialised JSON.

Currently we can only load in an entire folder (primarily used on start up). Adding the ability to also load in an individual file will help with dependent toolkits/UIs load in specific settings files.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #3299

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Review by Tom-Kingstone — APPROVED** [review]
Useful for when we want to load settings for toolkits easily. Approved.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
