### PR TITLE
Security_Engine: Transform method added for CameraDevice

### LINKED ISSUE #2322: Add type-specific rigid body transforms where needed
#### Description:

As discussed with @IsakNaslundBh, some object types will require a dedicated rigid body transform method that goes beyond simple `GetGeometry` and `SetGeometry`:
- [ ] `BH.oM.Structure.Elements.Node` - orientation
- [ ] `BH.oM.Structure.Elements.Bar` - orientation angle and nodes
- [ ] `BH.oM.Structure.Elements.FEMesh` - nodes
- [ ] `BH.oM.Structure.Elements.RigidLink` - nodes
- [ ] `BH.oM.Structure.Elements.Panel`- orientation angle
- [ ] `BH.oM.Physical.Elements.IFramingElement` (all implementations) - orientation angle
- [ ] `BH.oM.MEP.System.CableTray` - orientation angle
- [ ] `BH.oM.MEP.System.Duct` - orientation angle
- [ ] `BH.oM.Lighting.Elements.Luminaire` - direction
- [ ] `BH.oM.Security.Elements.CameraDevice` - target position
- [ ] `BH.oM.Architecture.Elements.Ceiling` - tiles
- [ ] `BH.oM.Architecture.BuildersWork.Opening` - it is neither `IElement0D` nor `IElement1D`, but will be nice to unlock it

Uff... the list got suspiciously long... I will be thankful if others could check if I am not missing anything here @al-fisher @IsakNaslundBh @FraserGreenroyd @rolyhudson @LMarkowski @alelom @adecler - happy to do the coding part by myself.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #2322

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FSecurity%5FEngine%2F%232322%2DTransform%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FSecurity%5FEngine).

### Changelog

- `Transform` method added for `CameraDevice`

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Review by tiagogrossi — APPROVED** [review]
LGTM!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
I am closing this due to merge conflicts - new PR with same code changes has been opened in #2392.

**Pull request closed without merging**
