### PR TITLE
BHoM_Engine: TryRunExtensionMethod made more sensitive to inputs

### LINKED ISSUE #3424: BHoM_Engine: make TryRunExtensionMethod look into all method arguments when binding
#### Description:

Currently when trying to bind methods as a part of `TryRunExtensionMethod` (`ExtensionMethodToCall` more specifically), we only match the 1st method argument to the most applicable method signature. That means that if we declare the following method:
```C#
public static void DoNothing(this Bar bar, double number)
{
}
```

The following call would bind:
```C#
Bar bar = new Bar();
double number = 123;
bar.TryRunExtensionMethod("DoNothing", new object[] { number });
```

However, if we add the following:
```C#
public static void DoNothing(this Bar bar, object obj)
{
}
```

The call to `bar.TryRunExtensionMethod("DoNothing", new object[] { number });` will not bind because there will be two extension methods taking `Bar`.

Following the above example, more sensitivity to other method arguments would be welcome, essentially treating them as if they were cast dynamically.

FYI @alelom @IsakNaslundBh

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3424

### Test files

See the changes in the test project - review and run the newly added tests.

### CODE REVIEW

**Comment by pawelbaran** [comment]
Good shout @alelom! I did not know we have a NUnit test solution ready for use. Ported the code over and updated the PR description. Ready for review!

**Review by alelom — APPROVED** [review]
Reviewed and tested with @pawelbaran. Only change I'd recommend is to make more descriptive names to test where applicable.

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Review by alelom — APPROVED** [review]
Re-approving following previous review. Thank you! 😄

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
Dispensating documentation compliance because all failures concern UTs sitting under .ci.

**Comment by pawelbaran** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 32533482456

**Pull request merged**
