### PR TITLE
Facade_Engine: Improvements to Facade SolidVolume and MaterialComposition Methods

### LINKED ISSUE #2848: Facade_Engine: Update MaterialComposition method to return only composition of Non-opening portion of panel
#### Description:
To align with other methods, the Facade-based MaterialComposition method should return the composition of the panel without its openings. The Volume query method should behave the same as well.

#### Steps to reproduce:
Get the material composition of a Panel with openings within it, and the material composition will include the opening materials. Per other namespace equivalent methods, this should return only the MC of the Panel itself. Volume should behave the same as well.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #2848 

Errors and warnings have been improved, and the methods have been tweaked to improve quality of method outputs for various cases.

### Test files
[#2848 GH and Rhino test files](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%232848-VolumeAndCompositionAlignment?csf=1&web=1&e=WUsmvF)

To test, flip through the different dropdown options for FrameEdge, Opening, and Panel and constructions and confirm that the results / errors that result are as expected, and help inform the user what they need to provide to get the method to work accordingly.

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check required

**Comment by vgreen-BH** [comment]
LGTM!

**Review by vgreen-BH — APPROVED** [review]
LGTM!

**Comment by enarhi** [comment]
@bhombot check ready-to-merge

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
