### PR TITLE
Diffing_Engine: Handle nulls

### LINKED ISSUE #2468: Diffing_Engine: Fix nulls
For the following methods:

 - [x] BH.Engine.Diffing.Compute.DiffRevisions(Revision pastRevision, Revision followingRevision, DiffingConfig diffingConfig)
 - [x] BH.Engine.Diffing.Convert.TryParseObjectToGuid(Object obj, Guid& guid)
 - [x] BH.oM.Diffing.Delta.Delta(Revision pastRevision, Revision currentRevision, DiffingConfig diffingConfig, String comment)
 - [x] BH.oM.Diffing.Delta.Delta(Revision revision, DiffingConfig diffingConfig, String comment)
 - [x] BH.oM.Diffing.Revision.Revision(IEnumerable<IBHoMObject> objects, Object streamId, String revisionName, String comment, DiffingConfig diffConfig)
 - [x] BH.Engine.Diffing.Query.RevisionFragment(IBHoMObject obj)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2468 - ain't never too late!

### Additional comments
Bonus points to whoever gets the reference after the issue number...

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2362894108

**Comment by alelom** [comment]
@FraserGreenroyd sorry but I think I found a bug: see issue [#2489](https://www.youtube.com/watch?v=kGrnEc_3mYo#t=0m41)

**Review by alelom — APPROVED** [review]
Tested, LGTM.

**Pull request merged**
