### PR TITLE
Facade_Engine: Geometry queries added for facade elements

### LINKED ISSUE #3333: Facade_Engine: missing Geometry queries cause UI glitches
#### Description:

Currently there is no `Query.Geometry` overloads in Facade_Engine leading to glitches in the UI:
- preview `CurtainWall` consisting of `Openings` throws an error due to empty outline (openings cancel out the outline)
- preview of `Opening` malfunctions in case when the edges form a closed loop but their directions are not aligned with it

FYI following today's chats @enarhi @IsakNaslundBh 

#### Test file:
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FFacade%5FEngine%2F%233333%2DFacadePreviewGlitches&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3333

### Test files

See #3333

### CODE REVIEW

**Comment by enarhi** [comment]
LGTM, tested with various facade geometry from revit pulls and natively created and this works as expected, representing correct geometry.

**Review by enarhi — APPROVED** [review]
LGTM, tested with various facade geometry from revit pulls and natively created and this works as expected, representing correct geometry.

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by enarhi — APPROVED** [review]
LGTM, only change since last review is copyright addition

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling
@BHoMBot check versioning
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 24144886781

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
