### PR TITLE
Analytical_Engine: Refactor and efficiency of graph methods

### LINKED ISSUE #2165: Analytical_Engine: remove relations when accessing spatial view of graphs.
#### Description:
When `SpatialView` is passed to the method `GraphView` a new graph is created that should only contain Entities that implement `IElement0D` and the Relations defined by these entities.

The method does not ensure the non-spatial relations are removed.

Currently this is not a problem as use cases so far have not involved graphs which are hybrid of spatial and non-spatial entities

However, future use will require hybrid graph use cases.

#### Expected behaviour:
When an entity is removed all relations dependent on that entity should also be removed.

### LINKED ISSUE #2433: Analytical_Engine: Geometry method for Graph fails
#### Description:
When creating graphs where the Curve property of relations has not been defined the Geometry extension method fails as there is no null check on the Relation.Curve property.

#### Steps to reproduce:
Create a graph by 

#### Expected behaviour:
If possible (when graph is based on IElement0D entities) straight lines should be created for entities with no Curve property defined.
If the the graph entities are non-spatial and no relations have the Curve property set the Geometry method should handle null Curves.

#### Test file(s):

[Simple graph](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Analytical_Engine/%232271_subgraphtest.gh?csf=1&web=1&e=oKtbln)

### LINKED ISSUE #2754: Analytical_Engine: Query.Geometry method for a non-spatial graph fails
#### Description:
Bit of a confusing one. Two cases exist (perhaps more):

- Generally non-spatial graphs have no geometry (no positions for nodes or curve / lines for relations). 
- However it is possible to create the relations with reference to a curve. A user could define geometry to represent a non-spatial graph.

Both will generate an grasshopper UI error when the `Query.Geometry` is called but produce a valid graph.

Easiest fix is provide warning if the entities in the graph are not `IElementOD`

Longer term more complex fix is the method should check for curves on the relations and use those. If no curves use a generic graph layout.

#### Steps to reproduce:
Create a non spatial graph and see the error on the graph component:
image

#### Expected behaviour:
Easiest fix is provide warning if the entities in the graph are not `IElementOD`

#### Test file(s):
[nonspatialgraphs.zip](https://github.com/BHoM/BHoM_Engine/files/8097022/nonspatialgraphs.zip)

### LINKED ISSUE #2809: Analytical_Engine: Refactor and efficiency of Graph methods
#### Description:

Some of the Methods in the Analytical_Engine can be refactored to be made more efficient and for some cases simplified.

this includes but is not limited to:
- Adjecency
- EntityNeighbourhood
- IsolatedEntities
- Geometry

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2809
Closes #2754
Closes #2433
Closes #2165

Various tweaks and refactoring's so drastically improve the performance of some of the Graph methods, by use of Lookups, dictionaries etc, and general rejigging the way the code run to dramatically improve the performance.

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Eu87lOuPfq1BvmoimITDszkBCtuwbKUadANis4NDer5_jQ?e=rHLXyK

### Changelog

- Significant speed improvement to Adjacency method
- Complete rewrite of EntityNeighbourhood to significantly quicker method making use of the Depth method. Most notable performance can be seen when finding Neighbourhood in both directions, and slightly larger Depth.
- Rewrite of the Geometry method for it to display more geometries, if set, and significant speed upgrade.
- Rewrite the way ProjectGraph works from excluding things not wanted, to pick out things sought for

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Review by FraserGreenroyd — APPROVED** [review]
Code review looks good and test files looked ok when I ran them, happy for this to be deployed for further testing.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
