### PR TITLE
MEP_Engine: Transform methods added for Duct and CableTray

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Contributes to resolving #2322

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FMEP%5FEngine%2F%232322%2DTransform%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FMEP%5FEngine). For verification purposes I have created a cluster that dumbly converts MEP elements into bars with same driving curve, profile and orientation angle - I hope that will be enough to convince the reviewers that the method does what it is expected to do 🐒 

### Changelog

- `Transform` methods added for `Duct` and `CableTray`

### CODE REVIEW

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
This will need some unit tests please as it was decided that all PRs for Environment_Engine and MEP_Engine would require unit tests to be added at the same time 🙈 sorry!

**Comment by pawelbaran** [comment]
UT added based on the GH script @FraserGreenroyd

**Review by michaelhoehn — APPROVED** [review]
LGTM Thanks @pawelbaran 🐒

**Comment by pawelbaran** [comment]
@BHoMBot check all

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Review by FraserGreenroyd — APPROVED** [review]
LGTM

**Pull request merged**
