### PR TITLE
Geometry_Engine: Singular Value Decomposition algorithm applied to FitPlane method

### LINKED ISSUE #3287: Geometry_Engine: Rewrite FitPlane method to leverage Singular Value Decomposition
#### Description:

Once https://github.com/BHoM/BHoM_Engine/pull/3280 gets merged, we will have an implementation of Singular Value Decomposition that can be applied in various applications. Once of them is line fitting (covered in the original PR), another one plane fitting. It would be desirable to rewrite the latter to leverage SVD as it seems to be very robust, I strongly believe more robust than my rather old attempt to compute eigenvectors using a mixture of geometrical tolerance and row echelon form.

@peterjamesnugent FYI

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3287

### Test files

See https://github.com/BHoM/BHoM_Engine/issues/3287

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by peterjamesnugent — APPROVED** [review]
Tested using develop and then this branch.

Improvement considering the cases provided.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
