### PR TITLE
Structure_Engine: Add null check for reinforcement in material composition

### LINKED ISSUE #2818: Structure_Engine: MaterialComposition for ConcreteSection is missing a null check
#### Broken rules:

As description. This causes crashes to happen for default concrete sections without any reinforcement set.

#### Suggestions to restore compliance:

Add null check

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2818 

Makes sure MaterialComposition works if no rebar is applied to concrete section

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/ErwwHG8L9P1Fk0W1tFnUujUBOVdXenAfUd1mCggfPl6N_A?e=v0Kb7r

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by JosefTaylor — APPROVED** [review]
It builds and doesn't crash!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
