### PR TITLE
Geometry-Engine: Issue 874-BooleanDifference/Intersection/UnionForPolyCurves

### LINKED ISSUE #874: Geometry_Engine: Add BooleanDifference, BooleanIntersection and BooleanUnion methods for PolyCurve
Add BooleanDifference, BooleanIntersection and BooleanUnion methods for PolyCurve.

### PR DESCRIPTION
**Pull request by LMarkowski**
### Issues addressed by this PR

Closes #874 

### Test files
Regular tests for Boolean operations are [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FCompute) marked with ~~'V2'~~ 'V3' (the 2 recorded errors are the result of different tolerance handling by BHoM and Rhino, ours is more precise 🙊), `IsContaining` for `BoundingBoxes` is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FGeometry_Engine%2FQuery)
~~Test for performance of rewritten Polylines methods is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%2DEngine%2DIssue874%2DBooleanDifferenceIntersectionUnionForPolyCurvesPerformance)~~

#### Changed (with no change in input/output type or logics)
- `List<Polyline> BooleanIntersection(this Polyline region, Polyline refRegion, double tolerance = Tolerance.Distance)`
- `List<Polyline> BooleanIntersection(this List<Polyline> regions, double tolerance = Tolerance.Distance)`
- `List<Polyline> BooleanUnion(this List<Polyline> regions, double tolerance = Tolerance.Distance)`
- `IsContaining` methods for `BoundingBoxes`
 ~~booleanIntersection(PolyCurve,PolyCurve)
booleanIntersection(List<PolyCurve>)
booleanUnion(List<PolyCurve>)
booleanDifference(PolyCurve, List<PolyCurve>)   //returns List<PolyCurve>
booleanDifference(List<PolyCurve>, List<PolyCurve>)   //returns List<List<PolyCurve>>~~

#### Added
- `List<Polyline> BooleanDifference(this Polyline region, List<Polyline> refRegions, double tolerance = Tolerance.Distance)`
- `List<PolyCurve> BooleanDifference(this PolyCurve region, List<PolyCurve> refRegions, double tolerance = Tolerance.Distance)`
- `List<PolyCurve> BooleanIntersection(this PolyCurve region, PolyCurve refRegion, double tolerance = Tolerance.Distance)`
- `List<PolyCurve> BooleanUnion(this List<PolyCurve> regions, double tolerance = Tolerance.Distance)`
- `List<List<PolyCurve>> ClusterCoplanar(this List<PolyCurve> curves, double distanceTolerance = Tolerance.Distance)` (needed to make the above work)
 ~~newBooleanIntersection(polyline, polyline)
newBooleanIntersection(List<polyline>)
newBooleanUnion(List<polyline>) spaghetti-geometry~~

#### Deprecated
- `BooleanDifference(this List<Polyline> regions, List<Polyline> refRegions, double tolerance = Tolerance.Distance)`

**The above changes lead to a consistent set of Boolean operations on regions for both `Polyline` and `PolyCurve`.** These are:
- Boolean union of a list of regions
- Boolean intersection of 2 regions
- Boolean intersection of a list of regions
- Boolean difference of a region and a list of cutting regions

> My methods for PolyCurves are different from those for Polylines. I rewrited some of Polylines methods with my logic and here are the results:
> - New intersection is slightly faster when there is high density of regions
> - New union is much faster when there is low density of regions but gets really slow with high density
> (I may be unclear with this high/low density. I think it's clear in test files)
> 
> We have to decide which method we should apply to the code. Maybe some algorythm chosing one of methods by density of regions would be useful.

@pawelbaran improved the performance of methods written by @LMarkowski to the extent that made them almost as fast as the old methods for high density of curves (many curve intersections) and much faster for low density. The old methods have been removed.

### Additional comments

> - Difference. We talked with @pawelbaran about return type of difference method. Probably difference between two lists of regions should return list of lists of regions (as I did for PoluCurves) and not list of regions (as it is for Polylines). That is to be discussed and that's why I haven't rewritten differnce(Polylines).

This has been resolved by leaving only a Boolean difference of a region and a list of cutting regions. The other methods have been deprecated (@FraserGreenroyd please confirm this is OK for you).

- I found an error in BooleanUnion(Polylines) and made an issue #919 

> - TODO: Interface allowing to perform boolean operations between Polylines and PolyCurves

Raised #924 for this one.

### CODE REVIEW

**Comment by LMarkowski** [comment]
Ugh. I forgot that at some point new methods needs new IsContaining methods for BoundingBox which I wrote in a meantime. They are not big, but I haven't prepared tests for them and I will propably do minor changes in them. I'll push a commit for know and mabye test them officialy before merging.

**Comment by pawelbaran** [comment]
I've looked through the test files, did some minor tweaks. What needs to be done before merging:
- [ ] make the test files compliant - now they do what is needed, but they do not follow the template
- [ ] make sure the input and return types match for `PolyCurve` and `Polyline` - cleanup needed
- [ ] add necessary interfaces
- [ ] decide which `BooleanUnion` algorithm to keep

I will take care of the above as @LMarkowski is on holidays. @IsakNaslundBh @epignatelli it would be nice if you could play around with the tests focusing on the outputs. Thanks!

**Comment by pawelbaran** [comment]
I perceive the PR as ready - sorry for the mess in the description but I tried to be as informative as possible without losing any initial information.

Would be thankful for a review from you guys 🐒

**Comment by pawelbaran** [comment]
Adding @al-fisher since as far as I remember you might have some other stuff to push to the Geometry_Engine - let's tick this one off and then the stage is yours.

**Comment by pawelbaran** [comment]
> - Difference from result for BooleanIntersection in testfile between GH solution and BHoM solution, but test file is reporting no fails. At least one of these three must be wrong: 1. BHoM Solution 2. GH solution 3. Verification

Will go through this one before merging

**Comment by pawelbaran** [comment]
@IsakNaslundBh could you merge then?

**Pull request merged**
