### PR TITLE
Settings_Engine: Ensure SaveSettings also updates settings in memory

### LINKED ISSUE #3295: Settings_Engine: Ensure that SaveSettings also updates settings loading in memory
Currently `SaveSettings` will update settings on disc, but not the settings in memory, while `UpdateSettings` will update the settings but not save them.

This means, when working with settings programmatically, you need to call both to ensure later calls to `GetSettings` return the ones saved - which is extra work for developer users.

So instead, if we `SaveSettings`, let's ensure we also `UpdateSettings` at the same time. However, keep `UpdateSettings` as is, to allow for people to update their in-memory settings without overwriting the saved settings for on-the-fly setting operations.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #3295

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by Tom-Kingstone — APPROVED** [review]
Addition makes sense as a user otherwise would have to reset whenever changing settings.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
