### PR TITLE
Environment_Engine: opening split bug fixed

### LINKED ISSUE #2969: Environment_Engine: SplitOpeningByGeometry method bug
I was trying to use SplitOpeningByGeometry method on my project and I've noticed instead of returning split openings it is returning the splitting curves from the input (as an opening object though). I think it would be really useful to have this method working.

image

fyi shoutout to @rboulton-BH @charliebrookerBH

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #2969

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FEnvironment%5FEngine%2F%233004%2DSplitOpeningFix&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

### CODE REVIEW

**Review by kprusicka — APPROVED** [review]
Reviewed the code and tested in grasshopper, method returns spitted curves correctly.

**Review by FraserGreenroyd — APPROVED** [review]
Code looks good, tests work well, happy to deploy.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: null-handling

**Pull request merged**
