### PR TITLE
Add proper protection for IsEquals check for Serialisation

### LINKED ISSUE #3442: Fix issue with Serialisation check for objects requiring more protection
#### Description:

If the IsEquals method crashes, the whole process stops executing. The isEqual check should be inside a try-ctach

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #3442

Add try-catch around IsEquals method to ensure it does not crash the whole test method, if exception is raised inside.

### Test files

running check serialisaiton should show some known errors for objects

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check serialisation

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests

**Comment by adecler** [comment]
@BHoMBot check required

**Review by adecler — APPROVED** [review]
Discussed and reviewed during a call with Isak and Pawel. Happy to approve from that.

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 34308208495

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
