### PR TITLE
Planar surface creation without openings fixed

### LINKED ISSUE #2593: Geometry_Engine: Create.PlanarSurface requires the collection of openings not to be empty
#### Description:

https://github.com/BHoM/BHoM_Engine/pull/2586 introduces a bug to `Create.PlanarSurface`: as mentioned, after the change, the method requires the collection of openings not to be empty, which means that it does not work for solid surfaces.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #2593

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%232594%2DPlanarSurfaceWithoutOpeningBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

### CODE REVIEW

**Review by enarhi — APPROVED** [review]
LGTM

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Review by IsakNaslundBh — APPROVED** [review]
LGTM

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
Closing this PR as reopened in https://github.com/BHoM/BHoM_Engine/pull/2608.

**Pull request closed without merging**
