### PR TITLE
Geometry_Engine: Fix code comment spelling

### LINKED ISSUE #3126: Geometry_Engine: Spelling in code comment
https://github.com/BHoM/BHoM_Engine/blob/develop/Geometry_Engine/Query/Normal.cs#L139

Code comment does not spell `adjacent` correctly.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #3126

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by EKAdebo — APPROVED** [review]
Spelling in one code comment has been fixed as expected.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning

**Comment by FraserGreenroyd** [comment]
Versioning bypassed due to failures not being caused by this PR.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
