### PR TITLE
Lighting_Engine: Add Base Lighting Engine Methods

### LINKED ISSUE #2365: Lighting_Engine: Add key methods for base lighting workflow
#### Description:
The required methods will be dictated by the base workflow of  **read model>place lighting>assign properties to lighting>analyze lighting>consume and communicate results**

Methods to be added will include:

- User-friendly create methods
- Modify methods to improve location, orientation, property handling
- Query methods as required for core workflow

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #2365 

### Test files
[Test File](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Lighting_Engine/%232365-BaseEngineMethods?csf=1&web=1&e=mA1acJ
)

Test file includes all methods that are part of this PR, confirm each section is working as expected with proper created object outputs.

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check versioning

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Review by michaelhoehn — APPROVED** [review]
LGTM! Tested and functions as expected!

**Comment by enarhi** [comment]
@BHoMBot check versioning

**Comment by enarhi** [comment]
@BHoMBot check installer

**Comment by enarhi** [comment]
@BHoMBot check core

**Review by michaelhoehn — APPROVED** [review]
Still LGTM!

**Review by michaelhoehn — APPROVED** [review]
Still LGTM

**Comment by enarhi** [comment]
@BHoMBot check versioning

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check core

**Comment by enarhi** [comment]
@BHoMBot check installer

**Comment by enarhi** [comment]
@BHoMBot check serialisation

**Pull request merged**
