### PR TITLE
Diffing_Engine: more null guarding against empty IEnumerables in the ComparisonConfig

### LINKED ISSUE #2806: Diffing_Engine: stronger null checks
#### Description:

Throughout the Diffing_Engine, we should check for nulls nested inside the `DiffingConfig` and the `ComparisonConfig` objects' properties. Setting them to null does not case any issue. However, setting some of their property to null – which, incidentally, can only happen intentionally and not by means of the existing code – will throw null exceptions when those properties are invoked.

This was the subject of https://github.com/BHoM/BHoM_Engine/pull/2805 where `ComparisonConfig.PropertiesToConsider` was null and the `Diffing()` method in `DiffWithCustomIds.cs` rightly throws a NullReferenceException. 

While this behaviour should be expected, stronger null checks can be added on every property of those two objects before starting any diffing process. This will effectively allow people to either input empty lists or null inputs to obtain the same result with some of the inputs.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #2806

### Test files

Run [this test](https://github.com/BHoM/DiffingTests_Prototypes/commit/cfca2016d654603b39fd7cf6d8013a6779a9f58c) in the DiffingTests_Prototypes. If the test is run before compiling this PR, it will fail; otherwise, it will succeed.

### CODE REVIEW

**Review by pawelbaran — APPROVED** [review]
LGTM, works as expected 👍

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by alelom** [comment]
@BHoMBot check null-handling

**Comment by alelom** [comment]
@BHoMBot check null-handling

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check serialisation

**Comment by alelom** [comment]
@BHoMBot check required

**Review by pawelbaran — APPROVED** [review]

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
