### PR TITLE
Geometry_Engine: Fix StartPoint for NurbsCurve

### LINKED ISSUE #435: Geometry_Engine: Query.StartPoint failing for NurbsCurve
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #435

Fix correctly getting out the StartPoint of NurbsCurve via point at parameter

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EkJFzOyIs8hLlgzaTaVCjM8BbhxlyfcvV3Vr0bELfMXBKQ?e=m6r5Bu

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
I have run the test script on todays alpha, and am getting the error regarding the start point for nurbs curve. I have then run the test script on this pull request and the error is gone, and the points are available, so I'm happy for this pull request from the hack session to be deployed.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check serialisation
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: null-handling, documentation-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
