### PR TITLE
Structure_Engine: Align to PointForce renamed to PointLoad

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1582

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Review by Tom-Kingstone — APPROVED** [review]
Approved based on linked PR - updated Enum

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Review by peterjamesnugent — APPROVED** [review]
Happy to approve on account of bot checks passing.

**Pull request merged**
