### PR TITLE
Diffing_Engine: Simplify code following new Base.GetHash() implementation

### LINKED ISSUE #1885: Diffing_Engine: modify code to remove NewtonSoft dependency
#### Broken rules:

As title.

#### Suggestions to restore compliance:

As title.

### LINKED ISSUE #1987: Diffing_Engine: Simplify code following new Base.GetHash() implementation
#### Description:

As title. This closes #1885 too

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #1987 
Closes #1885 

### Test files

Any test file in https://burohappold.sharepoint.com/:f:/s/BHoM/EpqHO1Ooxv5OqIwXsQvgFhsB1NwJEmkKhmNkZZ7hwLgjmQ?e=K7gQ23 

### Changelog

- Removed unused Newtonsoft dependency (https://github.com/BHoM/BHoM_Engine/pull/1952 had already switched to the new GetHash() method in Base)
- Deleted methods and files related to the deprecated hash generation
- Minor bug fix in `DifferentProperties()`: missing DiffConfig propagation

### CODE REVIEW

**Comment by alelom** [comment]
@al-fisher I've reviewed all example files in the folder linked above. The folder contains the example workflows that I produced for the Diffing and that I maintain as test files. All works fine.

**Review by al-fisher — APPROVED** [review]
LGTM
Tested on provided sample files.
And also performing diffing on a couple of random objects:

image

**Review by adecler — APPROVED** [review]
LGTM

**Comment by al-fisher** [comment]
Setting label for changelog

**Pull request merged**
