### PR TITLE
Update Assembly Version

### LINKED ISSUE #456: Geometry_Engine: Create Unit Tests for the Create class
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

### LINKED ISSUE #2425: Update AssemblyFileVersion
The `AssemblyFileVersion` attribute should now be updated to read `4.2.0.0` for all `AssemblyInfo.cs` files within this repository for the 4.2 milestone.

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #2425

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed from a CI/CD perspective. Will let discipline merge when happy.

**Review by adecler — APPROVED** [review]
LGTM

**Comment by adecler** [comment]
@BHoMBot check core

**Comment by adecler** [comment]
@BHoMBot check project-compliance

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@BHoMBot check versioning

**Comment by adecler** [comment]
@BHoMBot check serialisation

**Comment by adecler** [comment]
@BHoMBot check ready-merge

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
