### PR TITLE
Serialiser_Engine: Various changes to get unit-tests functional

### LINKED ISSUE #3390: Serialiser_Engine: Unit-Test storing HashSet in CustomData
#### Description:

Dataset has a `Hashset` stored in the `CustomData` which causes the method `System.Type.GetType()` to fail when called, leading to the `UnitTest` failing. 
https://github.com/search?q=repo%3ABHoM%2FBHoM_Engine%20path%3A%2F%5E%5C.ci%5C%2Funit-tests%5C%2FSerialiser_Engine_Tests%5C%2F%2F%20Hashset&type=code

#### Steps to reproduce:

Run `check unit-tests`.

https://github.com/BHoM/BHoM_Engine/pull/3381/checks?check_run_id=27915619358

#### Expected behaviour:

No failure.

### LINKED ISSUE #3392: Reflection_Engine: DocumentationURL, IsProtoType and URL are all failing UnitTests
#### Description:

Unit tests failing, see:
https://github.com/BHoM/BHoM_Engine/tree/develop/.ci/Datasets/Reflection_Engine/Query

#### Steps to reproduce:

Run unit-tests.

#### Expected behaviour:

Unit tests to pass.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #3390 
Closes #3392 

### Test files

Check with CI/CD

### Changelog

- Removed test in Serialiser_Engine that contained `Hashset<int>` in the `CustomData` causing it to fail.
- Added `ExplictType` for `Hashset<T>` to avoid failing `UnitTest`;
- Removed null inputs from `URL` unit test that was causing a `null` execption;
- Updated `URL`, `IsPrototype` and `DocumentationURL` unit-tests;
- Removed tests for `AllTypesIObject()` and `Versinoing` from Serialiser_Engine_Tests because the `[Ignore]` attribute is not working as inteded for CI;
- Removed serialiser test for `BitMap` as test is not functioning as intended for CI.

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Review by alelom — APPROVED** [review]
I'm leaving an approval regarding the previously failing Unit Tests:

<details>

image

</details>

I replicated the failure by running the tests a number of times (Run until failure). In the test, the input object is generated randomly. Some incorrect configuration of the randomly generated object can lead to a failure in obtaining the geometry with IGeometry(). I know we could test this with a dataset to ensure repeatability, and we should probably do that, but generating the object at random is also useful to check that the method returns a proper error message normally. Unfortunately we can't see the real issue because we capture exceptions instead of throwing them. We just see the test failing because it expects the geometry to not be null.

This means that re-running the tests will likely return a "Pass", I just triggered them again to verify. Regardless, this is not reason to block the PR. We can either:
1. Remove the randomness by instantiating the object manually. Even if having a "Random object" in a test can be useful to verify edge cases, our exception handling prevent us to make the best of it.
2. Transform the test in a data-driven test. Reading from a serialized ConcreteSection, for example. This is tricky to deal with given that our serializer is fundamentally incompatible with classical Unit Testing, because it requires loading all dependencies, which slows down the running of the unit tests immensely when running them from Visual Studio. A workaround would be to serialize/deserialize the object with Newtonsoft, or apply another ad-hoc workaround for our serializer.
3. Remove the test.

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by alelom — APPROVED** [review]
Re-approving following adjustment to my comment here:
https://github.com/BHoM/BHoM_Engine/pull/3391#pullrequestreview-2235539139

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests
@BHoMBot check dataset-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
