### PR TITLE
Diffing_Engine: Compliance Update

### LINKED ISSUE #1511: Diffing_Engine - Compliance issues
This report has been generated as part of a close out for the 3.1 milestone compliance and outlines all of the compliance issues currently highlighted by the CI team. @alelom will be undertaking this issue to resolve all compliance issues which do not impact scripts or versioning, with the remainder being moved to the 3.2 milestone for further discussion and resolution.

The following compliance issues have been found for this project. Please see the checklist below.
##### Incorrect Engine class name based on file path
 - [x] in BHoM_Engine\Diffing_Engine\Comparers\HashComparer.cs at line 39, column 17 
 - [x] in BHoM_Engine\Diffing_Engine\Convert\ToDiffingJson.cs at line 42, column 32 

##### Input attribute does not match any of the given parameters
 - [x] in BHoM_Engine\Diffing_Engine\Create\Stream.cs at line 44, column 15 

##### Method name must match file name
 - [x] in BHoM_Engine\Diffing_Engine\Comparers\HashComparer.cs at line 57, column 20 
 - [ ] in BHoM_Engine\Diffing_Engine\Comparers\HashComparer.cs at line 67, column 19 
 - [ ] in BHoM_Engine\Diffing_Engine\Modify\UpdateRevision.cs at line 43, column 43 
 - [ ] in BHoM_Engine\Diffing_Engine\Query\GetHash.cs at line 36, column 35 

##### Modify methods must return the same type as their first parameter
 - [x] in BHoM_Engine\Diffing_Engine\Modify\SetHashFragment.cs at line 47, column 22 

##### Invalid Engine class: Engine classes must be static
 - [ ] in BHoM_Engine\Diffing_Engine\Comparers\HashComparer.cs at line 39, column 4 

##### Invalid Engine class name
 - [ ] in BHoM_Engine\Diffing_Engine\Comparers\HashComparer.cs at line 39, column 17

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #1511 

### Test files
N/A

### Additional comments
The issue will be resolved by the changes made. Outstanding issues will be raised in 3.2 compliance reports as discussed.

Diffing_Engine has some fundamental compliance issues, with sub-classes and incorrect classes which will need addressing as part of a 3.2 discussion as there may be script breakages as a result.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
The compliance report has failed on punctuation which is deemed as acceptable for this current work and this PR can be merged, following successful review, with that problem on the report.

**Comment by alelom** [comment]
Rejecting the PR and requesting a re-run of compliance after https://github.com/BHoM/BHoM_Engine/pull/1534 is ready to review

**Comment by FraserGreenroyd** [comment]
PR is rejected as #1534 will cause changes to the compliance of Diffing_Engine. @alelom is requested to look at incorporating required compliance in his PR and compliance report will be rerun accordingly.

**Pull request closed without merging**
