### PR TITLE
Ground_Engine: Add method that returns a unique list of suite names

### LINKED ISSUE #3395: Ground_Engine: Add method for counting the number of suites in the ContaminantSample
#### Description:

This is necessary to count the number of Suites which are used to organise the different the tests on a `ContaminantSample`. 

This can be achieved, but it's difficult in Excel (requiring expanding and condensing) so it is probably better suited to it's own method.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #3395 

### Test files

https://burohappold.sharepoint.com/:u:/s/BHoM/Ea1ITPbisJ9FluD0BrkYMJMBSVESWJtefVkIdnPr1VuJuQ?e=cdP7fG

### Changelog

- Added `DistinctSuites` which gets all the unique suites for testing from the `ContaminantSamples` on a `Borehole`;
- Updated `IsValid` method and outputs;
- Updated methods that reference `IsValid()`;
- Added `ContaminantProperty` method to return an `IContaminantProperty` based on `Type`;

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by jtrainor1 — APPROVED** [review]
Component works in organising contaminant samples by first sample reference, then depth and finally test name.

**Comment by peterjamesnugent** [comment]
@BHoMBot check required
@BHoMBot check copyright-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by jtrainor1 — APPROVED** [review]
The component works as intended. Organising contaminant data based on Specimen Reference, then depth and finally test name.

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Comment by peterjamesnugent** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

**Pull request merged**
