### PR TITLE
Facade_Engine: Added PsiValuesMatch method and OpeningsSAM check for matching

### LINKED ISSUE #3132: Facade_Engine: Psi Value Method to check that adjacent edges have equal psi values assigned
#### Description:
This method will need to find an edge's adjacent edge(s), confirm they have equal psi values, and record an error if they do not before running the `UValueSAM` methods as Psi Values must match for this calc to be accurate.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #3132

Added method to check that adjacent frame edges have matching PsiValues, as mismatching PsiValues indicates an error in frame properties that needs to be resolved before running the calc.

### Test files
[Test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/BHoM_Engine/Facade_Engine/Facade_Engine-OverallUFactorCalculationMethods_PsiBased.gh?csf=1&web=1&e=L7pxdh)

### CODE REVIEW

**Review by AhmedElnagar1 — COMMENTED** [review]
Tested the PsiValuesMatch and OpeningsSAM methods with matching and different psi value inputs for adjacent edges.
Expected result occured in both cases. Matching psi value inputs gives the correct ouput U value and different adjacent psi value inputs gives an error stating that adjacent edges must have the same psi value.

**Comment by enarhi** [comment]
@BHoMBot check required

**Review by AhmedElnagar1 — APPROVED** [review]
Tested the PsiValuesMatch and OpeningsSAM methods with matching and different psi value inputs for adjacent edges.
Expected result occured in both cases. Matching psi value inputs gives the correct ouput U value and different adjacent psi value inputs gives an error stating that adjacent edges must have the same psi value.

**Comment by enarhi** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 15755410361

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
