### PR TITLE
Serialiser_Engine: Prevent duplicated types being registered

### LINKED ISSUE #2995: Serialiser_Engine: Multiple discriminator
#### Description:
For assemblies with multiple versions (such as the Revit assemblies which have a version for each Revit version (2018, 2019, etc.)), the object types end up getting registered multiple times with the discriminator in instances/situations where all of the Revit assemblies have to be loaded at once resulting in an ambiguous discriminator issue.

#### Steps to reproduce:
Load all Revit assemblies and try to deserialise the 6.0 object datasets with the versioning checker and it'll say everything is a custom object because it can't deserialise them.

#### Expected behaviour:
Objects get deserialised happily.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2995 

### Test files
[Available here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FSerialiser%5FEngine%2F%232996%2DMultipleDiscriminator&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b) - **note this requires Test_Toolkit to be built to run**

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by pawelbaran — CHANGES_REQUESTED** [review]
I have left one suggestion regarding the code itself, I have also tried to test the fix using the test files provided, without success:
- link is broken (ofc I looked up the file manually)
- there seems to be nothing that would showcase the fix (or I do not know how to read the file)

Could you please explain/tweak the test file to make testing easier @FraserGreenroyd?

**Comment by FraserGreenroyd** [comment]
> I have left one suggestion regarding the code itself

Implemented.

> * link is broken (ofc I looked up the file manually)

Woops - fixed!

> * there seems to be nothing that would showcase the fix (or I do not know how to read the file)

Added a second test file - the first one (original one) shows that serialisation isn't broken as a result of this change (this is the script used at the end of each milestone by DevOps to verify serialisation is happy). The second test file specifically showcases the issue for multiple discriminators which this PR is aiming to resolve.

Hope that helps 😄

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check unit-tests

**Review by pawelbaran — APPROVED** [review]
Happy with the code changes, tested and all good - approving!

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 10856602383

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 10856095641

**Pull request merged**
