### PR TITLE
MEP_Engine: Adding Create method for generating a Graph from a set of IFlowObejcts and fixtures

### LINKED ISSUE #2869: MEP_Engine: Graph from MEP objects
#### Description:

Add method for creating a graph from a set of MEP Flow obejcts and fittings

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2869

Raising this now, as I am about to go on leave for a few weeks, and while it is still fresh in my mind in case useful for further development discussed in planning call.

Adding a method for efficient creation of a analytical Graph from a set of `IFlow` objects as well as `Fixtures`.

Ideally we should be doing this in the Analytical_Engine, working on some interfaces such as the `ILink` etc, but as the `IFlow` objects currently do not implement that interface, added this as a temporary solution.

The graph currently assumes directionality from the `IFlow` objects, this is, from StartPoint to EndPoint. I suspect that this is not always correct, but could be handled by a second pass down the graph, once sources and exhausts etc are known.

Assume there are more point/node-based objects like HVAC units etc that will be required to form the full graph, but should hopefully be made easier by expanding the code in this PR.

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EiieIrVtZwpJn5KUmwaPgb8BAWRcn9cFaq3w97GvvkE29Q?e=WiErl7

### Additional comments

Ofc, not to be merged before 5.2 beta release.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot fix project file ref. 6938116854

**Comment by travispotterBH** [comment]
@IsakNaslundBh I suggest we move a link to this branch to an issue, and close this PR. We plan to do an overhaul of the MEP_oM to tackle this and other items later in this milestone. Thoughts?

**Comment by IsakNaslundBh** [comment]
> @IsakNaslundBh I suggest we move a link to this branch to an issue, and close this PR. We plan to do an overhaul of the MEP_oM to tackle this and other items later in this milestone. Thoughts?

More than happy with that. Mostly did this to try to help illustrate how the graphs could be used, not really expecting it to get merged. Happy for it to be closed.

Will let you do it @travispotterBH so that you can handle the linking of the branch to the appropriate issue before closing this PR.

**Comment by travispotterBH** [comment]
Closing will take care of in: https://github.com/BHoM/BHoM/issues/1139

**Pull request closed without merging**
