### PR TITLE
Remove PreviousVersion attributes for previous milestones

### LINKED ISSUE #448: Geometry_Engine: ProjectAlong issues from TestScript
Unit test here: https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/Archive/BHoM_Engine/Geometry_Engine/Modify/[Scale.gh](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/Archive/BHoM_Engine/Geometry_Engine/Modify/Scale.gh?csf=1&web=1&e=dWrlqc)?csf=1&web=1&e=dWrlqc

Methods failing without exceptions:

 Plane
 Arc
 Circle
 PolyCurve
 Loft
 CompositeGeometry
 CoordinateSystem
Methods failing due to other issues:

 NurbsSurface #441
 PolySurface #441
Methods that needs to be restructured:

 Vector Scale(Vector vector, Double rad, Vector axis) is a Rotate method, not sure why it is here

### LINKED ISSUE #2260: Removal of PreviousVersion attributes
`PreviousVersion` attributes have been detected in this repo and should be removed for the start of the new milestone.

The following files have been identified to have outdated `PreviousVersion` attributes:

 - Analytical_Engine\Create\IElement2D\NewInternalElement2D.cs
 - Analytical_Engine\Modify\SetGeometry.cs
 - Analytical_Engine\Modify\SetInternalElements2D.cs
 - Analytical_Engine\Modify\SetOutlineElements1D.cs
 - Analytical_Engine\Query\Elements0D.cs
 - Analytical_Engine\Query\Geometry.cs
 - Analytical_Engine\Query\InternalElements2D.cs
 - Analytical_Engine\Query\OutlineElements1D.cs
 - Environment_Engine\Compute\DateTimeList.cs
 - Environment_Engine\Compute\ExportEPW.cs
 - Environment_Engine\Compute\ImportEPW.cs
 - Environment_Engine\Modify\CullOverlaps.cs
 - Environment_Engine\Query\FilterOpenings.cs
 - Environment_Engine\Query\FilterPanels.cs
 - Environment_Engine\Query\FilterResults.cs
 - Environment_Engine\Query\Orientation.cs
 - Geometry_Engine\Modify\CullDuplicate.cs
 - Geometry_Engine\Query\DiscontinuityPoints.cs
 - Geometry_Engine\Query\LongestSegmentLength.cs
 - Physical_Engine\Query\Geometry.cs
 - Reflection_Engine\Query\Description.cs
 - Spatial_Engine\Create\ShapeProfiles\AngleProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\BoxProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\ChannelProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\CircleProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\FabricatedBoxProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\FabricatedISectionProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\FreeFormProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\GeneralisedFabricatedBoxProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\GeneralisedTSectionProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\ISectionProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\KiteProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\RectangleProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\TaperedProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\TSectionProfile.cs
 - Spatial_Engine\Create\ShapeProfiles\TubeProfile.cs
 - Spatial_Engine\Query\Area.cs
 - Spatial_Engine\Query\Bounds.cs
 - Spatial_Engine\Query\Centroid.cs
 - Spatial_Engine\Query\ControlPoints.cs
 - Spatial_Engine\Query\ElementCurves.cs
 - Spatial_Engine\Query\ElementVertices.cs
 - Spatial_Engine\Query\InternalOutlineCurves.cs
 - Spatial_Engine\Query\Length.cs
 - Spatial_Engine\Query\OutlineCurve.cs
 - Structure_Engine\Create\Elements\FEMesh.cs
 - Structure_Engine\Create\Elements\Panel.cs
 - Structure_Engine\Create\Framing\ConstantFramingProperty.cs
 - Structure_Engine\Create\Framing\FramingElement.cs
 - Structure_Engine\Create\Loads\AreaUniformTemperatureLoad.cs
 - Structure_Engine\Create\Loads\BarUniformTemperatureLoad.cs
 - Structure_Engine\Create\Loads\BarVaryingDistributedLoad\BarVaryingDistributedLoadDistanceBothEnds.cs
 - Structure_Engine\Create\MaterialFragments\Aluminium.cs
 - Structure_Engine\Create\MaterialFragments\Concrete.cs
 - Structure_Engine\Create\MaterialFragments\Steel.cs
 - Structure_Engine\Create\MaterialFragments\Timber.cs
 - Structure_Engine\Create\SectionProperties\ConcreteSection\ConcreteCircularSection.cs
 - Structure_Engine\Create\SectionProperties\ConcreteSection\ConcreteFreeFormSection.cs
 - Structure_Engine\Create\SectionProperties\ConcreteSection\ConcreteRectangleSection.cs
 - Structure_Engine\Create\SectionProperties\ConcreteSection\ConcreteSectionFromProfile.cs
 - Structure_Engine\Create\SectionProperties\ConcreteSection\ConcreteTSection.cs
 - Structure_Engine\Query\AnalyticalBars.cs
 - Structure_Engine\Query\DeformedShape.cs
 - Structure_Engine\Query\HasAssignedObjectIds.cs
 - Structure_Engine\Query\PlotBarForce.cs

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #2260

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed from a CI/CD perspective, would be good to have a second review as this is the engine before merging.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Review by adecler — APPROVED** [review]
Looks good to me

**Pull request merged**
