### PR TITLE
BHoM_Engine: Modify.SortExtensionMethods fixed not to exclude methods targeting object 

### LINKED ISSUE #3349: BHoM_Engine: Modify.SortExtensionMethods excludes methods targeting object
#### Description:

When calling methods via `TryRunExtensionMethod` mechanism, at some point `Modify.SortExtensionMethods` gets called to pick the most suitable method to call. Currently, the sorting method cannot meaningfully deal with extension methods targeting type `object`, so it skips them, which in practice means that extension methods targeting `object` cannot be called using `TryRunExtensionMethod`.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3349

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FBHoM%5FEngine%2F%233350%2DSortExtensionMethodsBug)

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by IsakNaslundBh — APPROVED** [review]
Could potentially have tried to deal with this in the `InheritanceHierarchy` method rather than as a hardcoded fallback, but given that this is the only case I can possibly think of to be hard coded, I think this is fine. 

Test script works as expected. Approved

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Pull request merged**
