### PR TITLE
Result_Engine: Add support for IResultSeries type results for property extraction and display

### LINKED ISSUE #2781: Results_Engine: Add support for IResultSeries for ResultValueProperty and visualisation methods
#### Description:

Add support for interface added in https://github.com/BHoM/BHoM/issues/1378

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1379   

### Issues addressed by this PR

Closes #2781

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot check null-handling

**Review by enarhi — APPROVED** [review]
LGTM, tested with a couple test cases and test implementation and all working as expected.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
