### PR TITLE
Facade_Engine: Updated and readded Unit Tests for UValueAW Methods

### LINKED ISSUE #3067: Facade_Engine: Unit Test upgrade for UValueOpeningAW
`.ci\Datasets\Facade_Engine\Compute\UValueOpeningAW.json`

This dataset needs updating following the changes to LCA objects and workflows. The dataset has been removed currently owing to the issues with unit tests for the engine. Please remake and readd the unit test.

### LINKED ISSUE #3068: Facade_Engine: Unit Test upgrade for UValuePanelAW
`.ci\Datasets\Facade_Engine\Compute\UValuePanelAW.json`

This dataset needs updating following the changes to LCA objects and workflows. The dataset has been removed currently owing to the issues with unit tests for the engine. Please remake and readd the unit test.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #3067 
Closes #3068 

Unit tests updated for accurate usage, and test data readded accordingly.

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: code-compliance, copyright-compliance, core, dataset-compliance, documentation-compliance, installer, null-handling, project-compliance, ready-to-merge, serialisation, versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 14230770046

**Review by FraserGreenroyd — APPROVED** [review]
New unit tests, in the words of Del Boy, lovely jubbly!

**Pull request merged**
