### PR TITLE
Analytical_Engine: Add CleanRegion method

### LINKED ISSUE #2543: Environment_Engine: CleanRegion
#### Description:

Expand upon the [CleanRoom ](https://github.com/BHoM/BHoM_Engine/blob/36bc1c146c07c66cc50a33d3ce24a026bdf6405e/Architecture_Engine/Modify/CleanRoom.cs)method to also apply to other IRegion objects such as Environment.Spaces. Needs to query perimeter curve of Region then apply CleanPolyline method then set perimeter property as the cleaned polyline.

image

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #2543 

### Test files
[Available here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FEnvironment%5FEngine%2F%232549%2DCleanRegions)

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 3159852916

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Review by rboulton-BH — APPROVED** [review]
LGTM

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
