### PR TITLE
Architecture_Engine: Transform methods added for Ceiling, CeilingTile and Opening

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Contributes to resolving #2322

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FArchitecture%5FEngine%2F%232322%2DTransform%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FArchitecture%5FEngine).

### Changelog

- `Transform` methods added for `Ceiling`, `CeilingTile` and `Opening`

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by LMarkowski** [comment]
@BHoMBot check unit tests

**Review by LMarkowski — APPROVED** [review]
LGTM, just polished the UT a bit, same as in other PRs.
Also, [this comment](https://github.com/BHoM/BHoM_Engine/pull/2361#issuecomment-791215148) applies here as well (`Ceiling` and `CeilingTile`).

**Comment by pawelbaran** [comment]
UT as well as GH script updated following the discussion in https://github.com/BHoM/BHoM_Engine/pull/2361

**Comment by pawelbaran** [comment]
@BHoMBot check all

**Review by LMarkowski — APPROVED** [review]
Thanks for adding the test. LGTM now.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Pull request merged**
