### PR TITLE
Diffing_Engine: InputObjectsNullOrEmpty method bugfixed

### LINKED ISSUE #3146: Diffing_Engine: InputObjectsNullOrEmpty checks previous objects twice instead of previous + following
#### Description:

As in the title, the line 184 below requires an obvious fix:
https://github.com/BHoM/BHoM_Engine/blob/fd47862cc03e385581836b63e9910aae4af811c2/Diffing_Engine/Compute/IDiffing.cs#L183-L184

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3146

### Test files

Standard test procedure for diffing.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by alelom — APPROVED** [review]
Approving based on code review. The code change makes sense and removes an incorrect assignment.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning, ready-to-merge, unit-tests

**Pull request merged**
