### PR TITLE
Diffing_Engine: IsEqual method added

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Supports closing out https://github.com/BHoM/Test_Toolkit/issues/473

### Test files

Very raw test file uploaded on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FDiffing%5FEngine%2F%233338%2DReplaceKellermanWithDiffing&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4), also diffing test project written by @alelom

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@alelom @IsakNaslundBh @FraserGreenroyd I ran the `unit-tests` check against `develop` under https://github.com/BHoM/BHoM_Engine/pull/3339 - the failures are exactly the same as on this branch, so I according to my best understanding, this PR together with https://github.com/BHoM/Test_Toolkit/pull/474 is neutral for the existing tests.

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Review by alelom — APPROVED** [review]
Works well, tested with Grasshopper Script and https://github.com/BHoM/DiffingTests_Prototypes/pull/21

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
