### PR TITLE
Geometry_Engine: Add shortest path algorithm

### LINKED ISSUE #2826: Geometry_Engine: Sort list of points to minimise distance between all points
Take a list of points. You want to reorder this list so that, if you measure the distance between each consecutive pair of points, then sum these distances for the list, the overall distance is minimised. This is the gist of the Travelling Salesman Problem. 

While the full solution to the TSP is NP-hard, I created a simplified version in GH/C#, which could be useful to be formalised into the BHoM. While the full TSP aims for a global optimum, my version is much simpler (and non-globally-optimal in the general case):
- Pick a start point and add it to the new sorted list. Remove this point from the pool of remaining points. 
- Find the nearest point to the first point, and add that to the sorted list, and remove it from the pool of remaining points. 
- Repeat the above point for all other points. 

The GH code is below, and would need to be adapted to BHoM standards. 

```
  private void RunScript(List<Point3d> x, ref object A)
  {

    //get ring of points
    List<Point3d> ringPoints = x;

    //join this ring up with nearest neighbours
    List<Point3d> sortedPoints = new List<Point3d>();


    //set up first item
    sortedPoints.Add(ringPoints[0]);
    ringPoints.RemoveAt(0);

    //now go through the ring points, finding nearest neighbours, and adding them
    int safety = 100; //safety not necessary if the loop below is well written!
    while(ringPoints.Count > 0)
    {
      Point3d np = NearestPoint(sortedPoints.Last(), ringPoints);
      sortedPoints.Add(np);
      ringPoints.Remove(np);
      //remember to remove a ringPoint for every loop!!
      safety--;
      if(safety < 0) break;
    }

    A = sortedPoints;



  }

  // <Custom additional code> 

  //finds the nearest point in a collection. Ignores itself if it finds itself.
  Point3d NearestPoint(Point3d pt, List<Point3d> comparisonpts)
  {
    double minDistance = Double.MaxValue;
    Point3d rtnpt = new Point3d();
    foreach (var cp in comparisonpts)
    {
      double dist = cp.DistanceTo(pt);
      if(dist == 0) continue;
      if(dist < minDistance)
      {
        minDistance = dist;
        rtnpt = cp;
      }
    }
    return rtnpt;
  }
```

### PR DESCRIPTION
**Pull request by albinber**
### Issues addressed by this PR

Closes #2826

### CODE REVIEW

**Comment by albinber** [comment]
@BHoMBot check compliance

**Comment by albinber** [comment]
@BHoMBot fix copyright headers ref. 16412106428

**Comment by albinber** [comment]
@bhombot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
All looks good now, thanks @albinber - great work 😄

**Comment by albinber** [comment]
@bhombot check compliance
@bhombot check required

**Review by pawelbaran — COMMENTED** [review]
Hi @albinber, glad to see more faces contributing! 🚀 🚀 🚀 

Starting from apologies: I do not want to spoil the party but... are we sure we are OK with modifying (i.e. emptying) the input collection? That should not happen from what I reckon - can be fixed easily by calling the following in line 42:

```C#
List<Point> ringPoints = points.ToList();
```

Would also be good to add checks against `points` being null or empty as well. But besides that, good stuff, can't wait for more! 👍

**Comment by albinber** [comment]
@bhombot check compliance
@bhombot check required

**Review by FraserGreenroyd — APPROVED** [review]
Changes make sense in line with comments, good to go.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Pull request merged**
