### PR TITLE
Physical engine: adding geometry3D method for Physical Floor

### LINKED ISSUE #2329: Physical_Engine: add more Geometry3D methods
#### Description:

More methods needed for objects such as Floor

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #2329

### Test files

Try creating a Floor and display its layers like:

image

### Limitations

The extrusion of the floor is not "capped", also this is not accounting for openings in the floor. Targeted by #2360.

One solution will be to extrude the openings also - and then translate the planar srf (including openings crvs) to top and bottom

image

image

### CODE REVIEW

**Comment by alelom** [comment]
@BHoMBot check all

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
Approving per previous PR

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by al-fisher** [comment]
Thanks @fraser @alelom

**Pull request merged**
