### PR TITLE
Settings_Engine: Ensure settings are loaded when queried

### LINKED ISSUE #3150: Settings_Engine: Ensure settings are loaded if queried
If using Settings_Engine to `GetSettings` outside a UI context, the `LoadSettings` method may not have run. A call to `LoadSettings` should be done within `GetSettings` to ensure settings are loaded when queried for all contexts.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #3150

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by enarhi — APPROVED** [review]
LGTM, settings loaded as expected.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: code-compliance, ready-to-merge, unit-tests, versioning

**Pull request merged**
