### PR TITLE
Environment_Engine: Null handling

### LINKED ISSUE #2443: Environment_Engine: Handle nulls
Handle nulls better in the 95 methods currently failing `null-handling` checks to help clean up the noise.

 - [x] BH.Engine.Environment.Modify.AddMaterialProperties(Material material, IMaterialProperties newProperties)
 - [x] BH.Engine.Environment.Compute.BooleanIntersect(Panel element, Panel elementToCompare)
 - [x] BH.Engine.Environment.Compute.ExportEPW(WeatherFile weatherfile, String outputPath)
 - [x] BH.Engine.Environment.Compute.ExtrudeToVolume(IRegion region, Double height, Double tolerance)
 - [x] BH.Engine.Environment.Compute.ExtrudeToVolume(Polyline pLine, String connectingSpaceName, Double height)
 - [x] BH.Engine.Environment.Compute.SolarPosition(SpaceTime spaceTime)
 - [x] BH.oM.Environment.Elements.Opening.Opening(Point location, OpeningOption configurationOption, List<Panel> panels)
 - [x] BH.oM.Environment.Analysis.AnalysisGrid.AnalysisGrid(Polyline externalBoundary, List<Polyline> innerBoundaries, Int32 id, String name, Double gridSpacing, Double edgeOffset, and 1 more inputs)
 - [x] BH.oM.Environment.Elements.Panel.Panels(BoundaryRepresentation brep, String connectedSpaceName, Double angleTolerance)
 - [x] BH.Engine.Environment.Modify.UpdateZones(Space space, List<String> zones, Boolean replace)
 - [x] BH.Engine.Environment.Modify.ChangeAdjacentSpace(Panel panel, String spaceNameToChange, String replacementSpaceName)
 - [x] BH.Engine.Environment.Modify.OffsetOpenings(Panel panel)
 - [x] BH.Engine.Environment.Modify.SetAdjancentSpaces(Panel panel, List<String> spaceNames)
 - [x] BH.Engine.Environment.Modify.AddAdjacentSpace(Panel panel, String spaceName)
 - [x] BH.Engine.Environment.Modify.AddOpening(Panel panel, Opening opening)
 - [x] BH.Engine.Environment.Modify.Copy(Panel panel)
 - [x] BH.Engine.Environment.Modify.SetInternalElements2D(Panel panel, List<IElement2D> internalElements2D)
 - [x] BH.Engine.Environment.Modify.SetOutlineElements1D(Opening opening, List<IElement1D> outlineElements1D)
 - [x] BH.Engine.Environment.Modify.SetOutlineElements1D(Panel panel, List<IElement1D> outlineElements1D)
 - [x] BH.Engine.Environment.Modify.SetOutlineElements1D(Space space, List<IElement1D> outlineElements1D)
 - [x] BH.Engine.Environment.Modify.SetGeometry(Node node, Point point)
 - [x] BH.Engine.Environment.Modify.SetGeometry(Panel panel, ICurve curve)
 - [x] BH.Engine.Environment.Modify.SetGeometry(Opening opening, ICurve curve)
 - [x] BH.Engine.Environment.Modify.SetGeometry(Edge edge, ICurve curve)
 - [x] BH.Engine.Environment.Modify.SetGeometry(Space space, Point locationPoint)
 - [x] BH.Engine.Environment.Convert.ToEdges(Polyline polyline)
 - [x] BH.Engine.Environment.Query.Azimuth(Polyline polyline, Vector refVector)
 - [x] BH.Engine.Environment.Query.Tilt(Polyline polyline, Double distanceTolerance, Double angleTolerance)
 - [x] BH.Engine.Environment.Query.Bounds(Panel panel)
 - [x] BH.Engine.Environment.Query.Width(Panel panel)
 - [x] BH.Engine.Environment.Query.Width(Opening opening)
 - [x] BH.Engine.Environment.Query.Width(ICurve panelCurve)
 - [x] BH.Engine.Environment.Query.IsTransparent(Material material)
 - [x] BH.Engine.Environment.Query.IsTransparent(Layer layer)
 - [x] BH.Engine.Environment.Query.ToLines(Edge edge)
 - [x] BH.Engine.Environment.Query.ToLines(Panel panel)
 - [x] BH.Engine.Environment.Query.ToLines(Opening opening)
 - [x] BH.Engine.Environment.Query.Polyline(Edge edge)
 - [x] BH.Engine.Environment.Query.Polyline(Panel panel)
 - [x] BH.Engine.Environment.Query.Polyline(Opening opening)
 - [x] BH.Engine.Environment.Query.TopRight(Panel panel, List<Panel> panelsAsSpace)
 - [x] BH.Engine.Environment.Query.TopRight(Polyline polyline, List<Panel> panelsAsSpace)
 - [x] BH.Engine.Environment.Query.Roughness(Construction construction)
 - [x] BH.Engine.Environment.Query.Roughness(Material material)
 - [x] BH.Engine.Environment.Query.MatchPointOn2Of3(Point point, Point comparePoint)
 - [x] BH.Engine.Environment.Query.RValue(Layer layer)
 - [x] BH.Engine.Environment.Query.Thickness(Panel panel)
 - [x] BH.Engine.Environment.Query.Thickness(Opening opening)
 - [x] BH.Engine.Environment.Query.Thickness(Opening opening, Boolean useFrameConstruction)
 - [x] BH.Engine.Environment.Query.UnconnectedEdges(Panel panel, List<Panel> panelsAsSpace)
 - [x] BH.Engine.Environment.Query.ExposedToSun(Panel panel)
 - [x] BH.Engine.Environment.Query.Height(Panel panel)
 - [x] BH.Engine.Environment.Query.Height(Opening opening)
 - [x] BH.Engine.Environment.Query.Height(ICurve curve)
 - [x] BH.Engine.Environment.Query.IsCoPlanar(Panel panel, Panel panelToCompare)
 - [x] BH.Engine.Environment.Query.UValue(Construction construction)
 - [x] BH.Engine.Environment.Query.Vertices(Panel panel)
 - [x] BH.Engine.Environment.Query.InternalElements2D(Panel panel)
 - [x] BH.Engine.Environment.Query.OutlineElements1D(Opening opening)
 - [x] BH.Engine.Environment.Query.OutlineElements1D(Panel panel)
 - [x] BH.Engine.Environment.Query.OutlineElements1D(Space space)
 - [x] BH.Engine.Environment.Query.IsContaining(List<Panel> panels, Point point, Boolean acceptOnEdges)
 - [x] BH.Engine.Environment.Query.IsExternal(Panel panel)
 - [x] BH.Engine.Environment.Query.IsInternal(Panel panel)
 - [x] BH.Engine.Environment.Query.NormalAwayFromSpace(Panel panel, List<Panel> panelsAsSpace, Double tolerance)
 - [x] BH.Engine.Environment.Query.Absorptance(Construction construction)
 - [x] BH.Engine.Environment.Query.Absorptance(Layer layer)
 - [x] BH.Engine.Environment.Query.Absorptance(Material material)
 - [x] BH.Engine.Environment.Query.BottomLeft(Panel panel, List<Panel> panelsAsSpace)
 - [x] BH.Engine.Environment.Query.BottomLeft(Polyline polyline, List<Panel> panelsAsSpace)
 - [x] BH.Engine.Environment.Query.BottomRight(Panel panel, List<Panel> panelsAsSpace)
 - [x] BH.Engine.Environment.Query.BottomRight(Polyline polyline, List<Panel> panelsAsSpace)
 - [x] BH.Engine.Environment.Query.FilterOpeningsByLevel(List<Opening> openings, Level searchLevel)
 - [x] BH.Engine.Environment.Query.FilterOpeningsByMaximumLevel(List<Opening> openings, Level searchLevel)
 - [x] BH.Engine.Environment.Query.FilterOpeningsByMinimumLevel(List<Opening> openings, Level searchLevel)
 - [x] BH.Engine.Environment.Query.FilterPanelsByLevel(List<Panel> panels, Level searchLevel)
 - [x] BH.Engine.Environment.Query.FilterPanelsByMaximumLevel(List<Panel> panels, Level searchLevel)
 - [x] BH.Engine.Environment.Query.FilterPanelsByMinimumLevel(List<Panel> panels, Level searchLevel)
 - [x] BH.Engine.Environment.Query.FrameFactor(Opening opening)
 - [x] BH.Engine.Environment.Query.Geometry(Node node)
 - [x] BH.Engine.Environment.Query.Geometry(Edge edge)
 - [x] BH.Engine.Environment.Query.HasMergeablePropertiesWith(Node element, Node other)
 - [x] BH.Engine.Environment.Query.IsLeft(Line line, Point check)
 - [x] BH.Engine.Environment.Query.MaterialComposition(Panel panel)
 - [x] BH.Engine.Environment.Query.MaterialComposition(Opening opening)
 - [x] BH.Engine.Environment.Query.IsValidLocation(Location location)
 - [x] BH.Engine.Environment.Query.DateTime(SpaceTime spaceTime)
 - [x] BH.Engine.Environment.Query.DateTime(Time time)
 - [x] BH.Engine.Environment.Query.Level(Panel panel, IEnumerable<Level> levels)
 - [x] BH.Engine.Environment.Query.MaximumLevel(Panel panel)
 - [x] BH.Engine.Environment.Query.MaximumLevel(Opening opening)
 - [x] BH.Engine.Environment.Query.MinimumLevel(Panel panel)
 - [x] BH.Engine.Environment.Query.MinimumLevel(Opening opening)
 - [x] BH.Engine.Environment.Query.SolidVolume(Panel panel)
 - [x] BH.Engine.Environment.Query.SolidVolume(Opening opening)
 - [x] BH.Engine.Environment.Modify.AssignGenericConstructions(Panel panel, Boolean assignOpenings)
 - [x] BH.Engine.Environment.Modify.AssignGenericConstructions(Opening opening)
 - [x] BH.Engine.Environment.Query.Orientation(IEnvironmentObject environmentObject, Double northAngle, Boolean returnAzimuthAngle)
 - [x] BH.Engine.Environment.Query.AltitudeRange(IEnvironmentObject environmentObject)
 - [x] BH.Engine.Environment.Query.Altitude(IEnvironmentObject environmentObject)
 - [x] BH.Engine.Environment.Query.Inclination(IEnvironmentObject environmentObject)
 - [x] BH.Engine.Environment.Query.IsContaining(List<Panel> panels, Point point, Boolean acceptOnEdges)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2443

### Additional comments
So many methods 🙈

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2288647733

**Review by tg359 — APPROVED** [review]
Wow, BHoMbot does a lot of stuff! LGTM 👍

**Pull request merged**
