### PR TITLE
Geometry_Engine: project along lowercase character compliance

### LINKED ISSUE #2990: Geometry_Engine: Method input should have lowercase character
https://github.com/BHoM/BHoM_Engine/blob/728f9fa98b7bf58fffb22d33156236bc3e62a278/Geometry_Engine/Modify/ProjectAlong.cs#L58

`ToPlane` should be `toPlane` on the method input at the link above.

### PR DESCRIPTION
**Pull request by kprusicka**
### Issues addressed by this PR

Closes #2990 

Character changed to lowercase.

### CODE REVIEW

**Comment by kprusicka** [comment]
@BHoMBot check compliance
@BHoMBot check required
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 10611239267

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 10611233820

**Review by FraserGreenroyd — APPROVED** [review]
This meets the requirements of the issue, thanks @kprusicka

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by kprusicka** [comment]
Dziekuje @BHoMBot

**Pull request merged**
