### PR TITLE
Common_Engine-Issues886,889-RightHandNormalAndDistributeOutlinesFix

### LINKED ISSUE #886: Common_Engine: Implement right hand rule based normal for IElement2D
Following #872, implement right hand rule based normal for `IElement2D`

### LINKED ISSUE #889: Common_Engine: make DistributeOutlines method ignore openings when cannot be cut
Some IElements2D can have openings cut in them (e.g. PanelPlanar in the Structure_oM) and some not since they are at the bottom of the hierarchy (Opening in the Structure_oM). For the latter, placing of the openings needs to be blocked. To be resolved by an extra bool argument in the method header.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #886 
Closes #889 

### Test files

No test file for the Normal method (I believe #872 should be enough), a DistributeOutlines test file is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FCommon_Engine%2FCommon_Engine-Issues886%2C889-RightHandNormalAndDistributeOutlinesFix) - this one should also be safe.

### Changelog

Added Normal method for an IElement2D + an extra argument that makes the `DistributeOutlines` method work correctly on the IElement2D that do not allow cutting holes.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@IsakNaslundBh I needed to step into the Structure_Engine to make the PanelPlanar constructor work - hope this will not be an issue.

**Comment by FraserGreenroyd** [comment]
@pawelbaran was the change to `PanelPlanar` truly necessary? It looks to me as if you've added a `true` input to the method, but the method it is calling already has `true` as the default bool value for that parameter? In my mind, this change to `PanelPlanar` isn't needed, other than providing clarification to someone scanning it that it `canCutOpenings`?

**Comment by pawelbaran** [comment]
@FraserGreenroyd yes it was: without a boolean input, the method call was ambiguous and the code did not compile. It surprised me too 😸

**Comment by FraserGreenroyd** [comment]
@pawelbaran ah is there another method with a similar name that wasn't changed for the files changed that I looked at? That makes more sense then :smile:

**Comment by pawelbaran** [comment]
Yeah, there is the original, deprecated one without a Boolean and a new one with a default `True` value.

**Pull request merged**
