### PR TITLE
Remove PreviousVersion Attributes

### PR DESCRIPTION
**Pull request by BHoMBot**
Remove `PreviousVersion` attributes for pre-5.0 versioning

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Approved from a DevOps perspective, will leave merge to toolkit lead or will be merged automatically on 29th September 2021.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check ready-to-merge

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3733656733

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3733659452

**Pull request merged**
