### PR TITLE
NewInternalElementXD moved to Query class

### LINKED ISSUE #1572: Spatial_Engine: Create NewElement1D etc. should be Query methods
As discussed here: https://github.com/BHoM/BHoM_Engine/pull/1543#issuecomment-595757027

> [...] all of these "New" methods actually should be Queries, not Creates. If we see Create methods as constructors, then these should most definitely not be Creates at least, and seeing it as "I get a new compatible type of a lower level object" rather than "I create a new lower level object, based on this higher level object" I think actually even semantically makes more sense.

The `NewElement0D` `NewElement1D`, `NewInternalElement2D` need to be migrated to Query namespace as above.

This will need to be coordinated with Physical_Engine, Structure_Engine, Environment_Engine and any other IElementXD implementations of those interfaces.

As part of this I would suggest we flatten the folder structures completely. Compliance for for Query should not be concerned with this in any case I do not believe. 

FYI @adecler @IsakNaslundBh @FraserGreenroyd @pawelbaran

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #1572 

Moved all occurrences of NewInternalElement2D from `Create` to `Query` as in issue, and deleted methods with ToBeRemoved attributes.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by FraserGreenroyd — APPROVED** [review]
Meets the issue and discussion, discussed through with @Tom-Kingstone and everything is looking good for another historic issue closed through a clean up, a nice way to start the year this sprint 😄

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
