### PR TITLE
Geometry_Engine: Support closed planar curve types

### LINKED ISSUE #2803: Geometry_Engine: Add more control over what checks to run initially on methods
#### Description:

As discussed in https://github.com/BHoM/BHoM_Engine/issues/2797 we need better control over what checks are redundant to run at the start of our methods. This is especially critical for heavy checks such as IsSelfIntersecting on very low level methods such as Normal and Centroid as highlighted in the linked issue, as it can become a real performance burden.

Some different options discussed in call
- Additional immutable curve classes to be added for closed planar non-selfintersecting PolyCurve and Polyline equivalents that are checked on creation and then do not require to be checked again. This might be the cleanest and simplest way to handle the issue.
- Additional boolean inputs on methods such as `unsafe` or `performChecks` or similar, by default set to check everything, but can then be turned off depending on if called from methods where it is safe to do so.
- Add additional `UnsafeXXXXX` (for example `UnsafeNormal` method that just does the computation without doing any checks. The method without the Unsafe prefix can then do all the checks first, and then call the `Unsafe` method for current behaviour, but internally we can choose whether to use the unsafe equivalent or not in various algorithms.

Might be more options than this, and even a combination of the above. @pawelbaran @al-fisher fyi

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1393
   
### Issues addressed by this PR

Closes #2803 

Adds support for the new Polygon and BoundaryCurve curves.

Change the signature of some of the more heavy methods to accept IPolyline and IPolyCurve instead of Polyline and PolyCurve, to enable passing Polygons and BoundaryCurves to them instead.

Update Centroid method for lists of curves to avoid calling BooleanUnion if it can be avoided. 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EkuLDyGrA2FHi4MlPS1N-WMBCcfi8sdjzIigKDsL1FuHOA?e=XAFq1E

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check documentation-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check documentation-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Review by alelom — APPROVED** [review]
Approving based on:
1. the code - great work
2. the test files, with the following comments:
 - `Area` - no problem
 - `Centroid` - the cases [`List<ICurve> outlines, List<ICurve> openings`](https://user-images.githubusercontent.com/6352844/170758135-66c6d05e-6320-40b9-8d05-f99a43dac95e.png) and [`PlanarSurface`](https://user-images.githubusercontent.com/6352844/170757854-0d1517e5-9ec8-4bbd-96d2-edac7434203c.png) both reports 99 curves CORRECT and 1 FAIL, and it's not clear from the test fail whether this is to be expected or not. 
 - `Check BoundaryCurve` - no problem
 - `Check Polygon` - no problem
 - `Planarsurface test` - the last two components return a Planarsurface object, but the object is not visible on the canvas, unlike the first one of the group. Not sure if intended. [See picture.](https://user-images.githubusercontent.com/6352844/170760244-772fb91c-8267-4076-bf73-4c4e40940ad8.png)

**Comment by IsakNaslundBh** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Review by alelom — APPROVED** [review]
Approving based on:
1. Latest code changes
2. Test scripts.

I am getting the same results of my [previous review](https://github.com/BHoM/BHoM_Engine/pull/2841#pullrequestreview-987813006) and I am satisfied with the answers provided in https://github.com/BHoM/BHoM_Engine/pull/2841#issuecomment-1140866172, in particular on the precision "fail". The visualisation issue is still there but I am convinced it must be something on my end and not related to this PR.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check code-compliance
@BHoMBot check copyright-compliance
@BHoMBot check core
@BHoMBot check dataset-compliance
@BHoMBot check documentation-compliance
@BHoMBot check null-handling
@BHoMBot check project-compliance
@BHoMBot check ready-to-merge
@BHoMBot check serialisation
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
The descriptions missed and flagged by the documentation compliance have intentionally been left out due to https://github.com/BHoM/BHoM_Engine/issues/2840 . Descriptions to be added when the method is fixed. Will dispense the check for this PR, which ahs been agreed in call with @FraserGreenroyd .

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 8612058397

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 8612058397

**Pull request merged**
