### PR TITLE
Reflection_Engine: Adding check for Fragments in the DistinctProperties

### LINKED ISSUE #1250: Reflection_Engine: DistinctProperties to look for fragments
#### Description:

Once the fragments have been updated to the FragmentSet (https://github.com/BHoM/BHoM/pull/574), the DistinctProperties method can start looking through the fragments as well for any property of the specified type.

Will increase flexibility in the DependencyObjects and allow toolkits to add fragments to obejcts and still rely on the standard behaviour of the adapter.

#### Comments:

@rwemay think this can be a neat way to finally solve being able to handle for example FramingElementDesignProperties in Robot that I know you asked for quite some time ago.

FYI @JosefTaylor @peterjamesnugent @adecler @FraserGreenroyd

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #1250 

Making DistinctProperties check if P is a fragment type, and if so, try to fetch it from the fragment List of the objects.

### CODE REVIEW

**Review by adecler — COMMENTED** [review]
Looks good to me on the side of the code. 

That will obviously need to be reviewed from the perspective of the Adapter (as it is the only part of the code calling this method).

Not a deal breaker but it is good to keep in mind that this PR creates a inconsistent behaviour among the property accessor methods in the reflection Engine as it is the only one that now treats fragment as a primary property. 

This, for example, raises the question on what should be done on the level of the `Explode` component. This is an important one because all objects of sa same type are not guaranteed to have the same fragments on them (as opposed to a guaranteed list of properties). So would potentially need a reevaluation of the warning system in `Explode` as well.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Review by alelom — APPROVED** [review]
Approving from the Adapter perspective.

**Pull request merged**
