### PR TITLE
BHoM_Engine: Adding description to Create.Enumeration and Compute.ParseEnum

### LINKED ISSUE #2697: BHoM_Engine: Create.Enumeration and Compute.ParseEnum methods should have proper description (including inputs/output)
#### Broken rules:
As per title

#### Suggestions to restore compliance:
Add Description, Input, And Output attributes to those methods

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #2697

See issue / title.

### Test files
Not needed

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Review by IsakNaslundBh — APPROVED** [review]
LGTM.

Could make use of the bot to add punctuation if you like, but will leave that to you

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 4259972281

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
