### PR TITLE
Facade_Engine: Transform methods added

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Contributes to resolving #2383

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FFacade%5FEngine%2F%232383%2DTransform) - a trick with a cluster converting `FrameEdge` to `Bar` has been used to validate the results.

### Changelog

- `Transform` methods added for facade elements: `FrameEdge`, `Opening`, `Panel` and `CurtainWall`

### CODE REVIEW

**Review by enarhi — APPROVED** [review]
LGTM!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Pull request merged**
