### PR TITLE
Reflection_Engine: Add a check to filter out non-BH Types from the IsPrototype check

### LINKED ISSUE #2913: Reflection_Engine: System types are flagged as prototypes
#### Description:

Current IsPrototype check does deem all system types to be prototypes, which then makes them getting flagged as such in the UI:

image

Might need to add some form of exception in the https://github.com/BHoM/BHoM_Engine/blob/main/Reflection_Engine/Query/IsPrototype.cs method, either filtering so that system types are not flagged as prototypes, or that all types with a namespace not beginning with BH are not flagged as prototypes.

#### Steps to reproduce:

Create a system type (for example string) with the CreateType component.

#### Expected behaviour:

For only BH types not included in an installer to be flagged as prototype.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2913 

### Test files
[Here is a test script](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Reflection_Engine/%232913-IsPrototypeBug/ReflectionEngineIsPrototype.gh?csf=1&web=1&e=XBl37L)

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@IsakNaslundBh one for us to investigate in the morning I think, the unit test is passing locally but failing on the PR when it was made for this PR...!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting a force check on: dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting a force check on: dataset-compliance

**Review by jamesramsden-bh — APPROVED** [review]
LGTM

**Comment by jamesramsden-bh** [comment]
@BHoMBot check ready-to-merge

**Review by jamesramsden-bh — APPROVED** [review]
Fixed functionality demonstrated in GH with BHoM and non-BHoM types, works as expected.

**Pull request merged**
