### PR TITLE
Structure_Engine: Update names of MeshResults

### LINKED ISSUE #1321: Structure_Engine: Updates to MeshResults
#### Parent issue(s) or Pull Request(s) causing the changes:

https://github.com/BHoM/BHoM/issues/589

#### Description:

Updated naming of MeshResults and MeshResult

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/611
   
### Issues addressed by this PR

Closes #1321 

Update references to MeshResults to new name MeshResult

### CODE REVIEW

**Comment by al-fisher** [comment]
Sorry 🤖 
🤦‍♂

**Comment by FraserGreenroyd** [comment]
> Sorry 🤖
> 🤦‍♂

😄

**Pull request merged**
