### PR TITLE
Spatial_Engine: bounding box query for profiles added

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #

### Test files

Implicitly tested by https://github.com/BHoM/Revit_Toolkit/pull/1225

### CODE REVIEW

**Comment by pawelbaran** [comment]
Fair point @JosefTaylor - I have looked up `Extrude` method and the stuff that I am just adding should be applicable to it. However, I would rather do that in a separate PR not to inflate the scope of this PR. Happy to raise an issue once this one gets approved 👍

**Review by vietle-bh — APPROVED** [review]

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
