### PR TITLE
Structure_Engine: Add methods for setting analysis parameters for Timber materials

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1469   

### Issues addressed by this PR

Add methods supporting the newly added ITimber materials, in particular methods to get the materials set up for analysis.

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EiFjdCHeLjlDpuedn07U_WMB8JwuERwa2YMR-LxVus0z8w?e=ftT2Ed

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
Reviewed online with @IsakNaslundBh talking through the rationale - we need to make sure this is captured in the Wiki.

Reviewed both methods - generally happy with what is happening (though I am no Timber expert).

Couple of changes to the descriptions to make sure they're consistent throughout.

**Review by peterjamesnugent — DISMISSED** [review]
Happy that the latest commits address the requested changes.

**Review by peterjamesnugent — APPROVED** [review]
Still happy just with UnitTests added.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
Ah, forgot about https://github.com/BHoM/Test_Toolkit/issues/405

Will remove the modify UTs. Script is still there to generate them once this issue has been resolved.

**Review by FraserGreenroyd — APPROVED** [review]
Only changes made since @peterjamesnugent review is on removing unit tests and updating based on the oM changes. No functionality has changed so I am approving on the basis of code review of the final 2 commits, and using @peterjamesnugent review of functionality previously.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@FraserGreenroyd this one as well please

**Pull request merged**
