### PR TITLE
Reflection_Engine: Make sure no warning is shown when setting property of a CustomObject

### LINKED ISSUE #2418: Reflection_Engine: SetPropertyValue displays a warning when assigning to CustomObject
#### Description:

As title says. A warning is raised when assigning data to a CustomObject.

image

We previously used to not display this warning for CustomObjects, but seem that has been missed after some refactoring, unless this is intentional, in which case, this issue can be closed.

All is working fine, and the warning is after all factually correct, so not a big problem

#### Expected behaviour:

For things to function as they do, but for no warning to be raised on custom objects

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #2418

See issue

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check all

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@BHoMBot check project-compliance

**Comment by adecler** [comment]
@BHoMBot check core

**Comment by adecler** [comment]
@BHoMBot check-serialisation

**Comment by adecler** [comment]
@BHoMBot check versioning

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Comment by adecler** [comment]
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
### Test Report

No test assets were provided on the PR or issue, nor could I find any on SharePoint when looking for a folder of `#2412-NoWarningOnSetPropertyOfCustomObject`. However, issue description was sufficient to work out the problem I think, see the below to make sure I did get it right.

I downloaded todays alpha (1st April 2021) and then compiled this PR on top of it.

I opened a blank Grasshopper script and produced a `CustomObject` and used `SetProperty` to assign some data. No warning was displayed on doing this. I then created an `Environment.Panel` object and used `SetProperty` to assign some data which does not belong as a property of the `Panel`. A warning was displayed that this was being set to `CustomData`. I then used `SetProperty` to assign some data to the `Panel` which does belong as a property of the object. No warning was displayed.

I feel these three outcomes are the expected and correct behaviour for the functionality. The image below shows the set up of the script I used for this test.

image

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by adecler** [comment]
@BHoMBot check core

**Comment by adecler** [comment]
@BHoMBot check serialisation

**Comment by adecler** [comment]
@BHoMBot check versioning

**Comment by adecler** [comment]
@BHoMBot check null-handling

**Comment by adecler** [comment]
@FraserGreenroyd , I have requested dispensation on compliance for the method return type as it is irrelevant for this PR. 
For reference, this issue was already raised here: https://github.com/BHoM/admin/issues/11

**Comment by adecler** [comment]
@BHoMBot check installer

**Pull request merged**
