### PR TITLE
Leverage the versioning engine for deserialisation of objects

### LINKED ISSUE #1267: Serialiser_Engine: Leverage the versioning engine for deserialisation of objects
#### Description:
Make sure deprecated object are automatically upgraded when deserialised by using the versioning engine

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/Versioning_Toolkit/pull/2

   
### Issues addressed by this PR
Closes #1267 

See the PR in the Versioning_Toolkit for more details

### Additional comments
Recreating with proper branch name

Edit: This doesn't really depends on the Version toolkit per se anymore (no direct reference) but you will need it for testing.

### CODE REVIEW

**Comment by adecler** [comment]
Although we don't have circular dependencies between projects, we now have one between repos because
- The Versioning Engine depends on the Reflection-Engine for logging messages
- The Serialisation_Engine depends on the Versioning_Engine
This means that AppVeyor and Code_Assistant will stop working properly

The only thing I can think of to avoid this is to move the Versioning_Engine project into the BHoM_Engine (contains a single file). The Versioning_Toolkit would then contain only the upgrader dlls. Maybe we shouldn't call it a toolkit then as it doesn't cover any part of the diamond in that case.

Any thoughts?

**Comment by IsakNaslundBh** [comment]
Was going to ask you about the dependencies when trying to compile this yesterday, and agree with the solution. To me it does not make sense for the core engine to depend on any toolkit at all, so agree with moving the Versioning_Engine in here.

When it comes to the Versioning_Toolkit only containing the upgrader dlls, I am personally fine with that solution, can not think of anything better of the top of my head.

**Comment by al-fisher** [comment]
> The only thing I can think of to avoid this is to move the Versioning_Engine project into the BHoM_Engine

Good idea - agree best to avoid circular dependencies across repos also 👍

**Comment by adecler** [comment]
See [the comment on the Versioning_Toolkit PR](https://github.com/BHoM/Versioning_Toolkit/pull/2#issuecomment-544871222) for moredetails about the exact scope covered here.

**Comment by al-fisher** [comment]
With introduction of new `Compute partial class` in `BH.Engine.Serialiser` creates an error in Excel_Toolkit:

> `Compute` is an ambiguous reference between `BH.Engine.Reflection.Compute` and `BH.Engine.Serialiser.Compute` in Excel_UI	

Have raised an issue here: https://github.com/BHoM/Excel_Toolkit/issues/159

**Comment by al-fisher** [comment]
Also - on building and running the Engine PR _with_ Versioning_Toolkit PR built etc. https://github.com/BHoM/Versioning_Toolkit/pull/2

Still get warnings regarding "Cannot find a definition" and a `CustomObject` is returned
image

**Comment by al-fisher** [comment]
Although the simple "primitive" `Level` class works - consisting of only simple type Properties?
image

**Comment by adecler** [comment]
oh boy, the one time I don't test with Bars and Nodes. Sorry about that. You're right, I had tested on Level but it doesn't contain other BHoM objects. I am still a bit confused why it was complaining for the bar type itself though and not just its children properties. 
Anyway, it should be fixed now.

**Comment by adecler** [comment]
@al-fisher , the conversion now returns the old version when the upgraders are missing. I have also turned the messages into warnings instead of errors for that situation. Let me know if that works for you.

**Comment by al-fisher** [comment]
Tested this again _without_ Versioning_Toolkit.  The above three scenarios:

> 1. non-deprecated objects will simply work
> 2. deprecated will return as "old" (as converts will naturally not be found)
> 3. deleted will be returned as CustomObjects (as also converts will not be found)

 are all behaving as expected. Thanks @adecler 

For case 2. Noting deprecated objects are deserialsed without warning they are Deprecated. That could be a nice to have? - but not critical for this PR perhaps.

**Comment by al-fisher** [comment]
Tested _with_ Versioning_Toolkit and case 2. upgrades:

image

**Comment by al-fisher** [comment]
Also important we address https://github.com/BHoM/Excel_Toolkit/issues/159 as noted above before merging.

Leaving **`status:do-not-merge`** label on this PR

**Comment by al-fisher** [comment]
Thanks @alelom

**Pull request merged**
