### PR TITLE
Spatial_Engine: Fixing RoundCoordinates(IElement) bug and unit test

### LINKED ISSUE #2427: Spatial_Engine: Fix RoundCoordinates(IElement) unit test

### PR DESCRIPTION
**Pull request by LMarkowski**
### Issues addressed by this PR

Closes #2427 

Unit test for Spatial's `RoundCoordinates` was failing since merging. While updating it I decided to create a proper validation test script to ensure that new one will be correct. I found a basic bug which I by the way fixed.

There is still one more edge case to be taken care of (#2419) but it might be caused by other error in `IsCoplanar` and I also wanted to fix the UT asap, so I'll do it separately.

### Test files

[SharePoint](https://burohappold.sharepoint.com/:f:/s/BHoM/Es7u_pVlelBHnMn4FMLckToBg_rAo9B9mua_D35VuZAdYw?e=C5nszg)

### Changelog

- Updated `RoundCoordinates` method in the `Spatial_Engine` for `IElement2D` class.
- Updated unit test for `RoundCoordinates` method in the `Spatial_Engine`.

### CODE REVIEW

**Comment by LMarkowski** [comment]
@BHoMBot check unit-test

**Comment by LMarkowski** [comment]
@BHoMBot check unit-tests

**Comment by LMarkowski** [comment]
@BHoMBot check unit-tests

**Review by rolyhudson — CHANGES_REQUESTED** [review]
Code changes look fine but the test file validation scripts all fail as they reference local dlls in your build folder(s) for the following:
C:\Users\lmarkowski\Documents\GitHub\BHoM\Build\BHoM.dll
C:\Users\lmarkowski\Documents\GitHub\BHoM\Build\Geometry_oM.dll

Can you update to use C:\ProgramData\BHoM\Assemblies.

**Comment by LMarkowski** [comment]
@rolyhudson good point! I've updated the script, it should be good now.

**Comment by rolyhudson** [comment]
@BHoMBot check unit-tests

**Review by rolyhudson — DISMISSED** [review]
LGTM - sorry for not getting back and finalising the review here sooner. Unit tests PRs always seem to drag out way longer then necessary. We need to become swifter in getting these into the system and fixed when needed.

Don't ever hesitate to remind on a teams message. 👍

**Comment by LMarkowski** [comment]
@BHoMBot check installer

**Comment by LMarkowski** [comment]
@BHoMBot check compliance

**Comment by LMarkowski** [comment]
@BHoMBot check core

**Comment by LMarkowski** [comment]
@BHoMBot check null-handling

**Comment by LMarkowski** [comment]
@BHoMBot check serialisation

**Comment by LMarkowski** [comment]
@BHoMBot check versioning

**Comment by LMarkowski** [comment]
@rolyhudson I needed to manually remove the attributes from 4.1, as this branch was omitted during the automatic version change. Could you please rubberstamp this one?

**Comment by LMarkowski** [comment]
@BHoMBot check compliance

**Comment by LMarkowski** [comment]
@BHoMBot check core

**Comment by LMarkowski** [comment]
@BHoMBot check installer

**Comment by LMarkowski** [comment]
@BHoMBot check versioning

**Comment by LMarkowski** [comment]
@BHoMBot check serialisation

**Comment by LMarkowski** [comment]
@BHoMBot check null-handling

**Review by rolyhudson — APPROVED** [review]
LGTM previous version attributes removed

**Comment by FraserGreenroyd** [comment]
The current version is 4.2 - I note the removed previous version said this current development version so was that right to remove them?

**Comment by rolyhudson** [comment]
My understanding @FraserGreenroyd is that these were removed from the master by BHoMBot but this branch was not up to date with the master so Lukas manually removed them.

**Comment by FraserGreenroyd** [comment]
Fair enough, just the 4.2 bit confused me. `check versioning` appears to be happy though so evidently not an issue! :smile:

**Comment by LMarkowski** [comment]
> Fair enough, just the 4.2 bit confused me. `check versioning` appears to be happy though so evidently not an issue! 😄

Yes, when I saw the compliance error I've just updated the version at my first reflex. Then I realised that those attributes shouldn't be there at all 😅

**Comment by LMarkowski** [comment]
@BHoMBot check null-handling

**Comment by LMarkowski** [comment]
@BHoMBot check serialisation

**Comment by LMarkowski** [comment]
@BHoMBot check versioning

**Comment by LMarkowski** [comment]
@BHoMBot check installer

**Comment by LMarkowski** [comment]
@BHoMBot check core

**Comment by LMarkowski** [comment]
@BHoMBot check compliance

**Comment by LMarkowski** [comment]
@BHoMBot check compliance

**Comment by LMarkowski** [comment]
@BHoMBot check core

**Comment by LMarkowski** [comment]
@BHoMBot check installer

**Comment by LMarkowski** [comment]
@BHoMBot check versioning

**Comment by LMarkowski** [comment]
@BHoMBot check serialisation

**Comment by LMarkowski** [comment]
@BHoMBot check versioning

**Comment by LMarkowski** [comment]
@BHoMBot check null-handling

**Comment by LMarkowski** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2305520414

Only because @LMarkowski has suffered enough on this PR and will fix it later as discussed.

**Comment by LMarkowski** [comment]
@BHoMBot check serialisation

**Comment by LMarkowski** [comment]
@BHoMBot check null-handling

**Comment by LMarkowski** [comment]
@BHoMBot check core

**Comment by LMarkowski** [comment]
@BHoMBot check compliance

**Comment by LMarkowski** [comment]
@BHoMBot check installer

**Comment by LMarkowski** [comment]
@BHoMBot check versioning

**Review by rolyhudson — APPROVED** [review]
Still look good to me. Delighted to review this again. 😆

**Comment by FraserGreenroyd** [comment]
> Still look good to me. Delighted to review this again. 😆

This is a lot of work for 1 line of change, @LMarkowski definitely knows how to make a mountain out of a mole hill 😝

**Comment by LMarkowski** [comment]
> This is a lot of work for 1 line of change, @LMarkowski definitely knows how to make a mountain out of a mole hill 😝

@FraserGreenroyd It's not me! It's him -> @BHoMBot

**Comment by LMarkowski** [comment]
> sorry, I didn't understand.

Yeah, yeah. I know. 🙄

**Comment by rolyhudson** [comment]
@BHoMBot we love you really a lot ❤️

**Comment by FraserGreenroyd** [comment]
@BHoMBot thank you my friend :smile:

**Comment by FraserGreenroyd** [comment]
I'm merging this before anyone has any bright ideas to do another commit... :wink:

**Pull request merged**
