### PR TITLE
Geometry_Engine: Add unit tests based on method usage analytics

### LINKED ISSUE #2413: Geometry_Engine: Unit tests based on usage analytics.
#### Definition of the test :
Create the next batch of Geometry Engine unit tests based on the usage based priority list [here](https://github.com/BHoM/BHoM/discussions/1148#discussioncomment-359855). Focusing on Query, Modify, Compute methods first.

### PR DESCRIPTION
**Pull request by rolyhudson**
### Issues addressed by this PR
More Geometry unit tests

Closes #2413 

### Test files
Creation scripts [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Geometry_Engine/%232414-UnitTestsFromUsage?csf=1&web=1&e=ieyDPf)

### CODE REVIEW

**Comment by rolyhudson** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
PR title needs improving for change log please :smile:

**Comment by rolyhudson** [comment]
@BHoMBot check unit-tests

**Comment by rolyhudson** [comment]
@BHoMBot check unit-tests

**Review by LMarkowski — CHANGES_REQUESTED** [review]
I checked the test scripts and in general all looks good. I've only got one comment and also logged few missing methods.

Comment :
- **CullDuplicateLines:** It's more an issue of the method itself but the naming is inconsistent. File is named `CullDuplicate.cs` but it contains only one method - `CullDuplicateLines`. Eventually it should be unified, but for now I'd rename the unit test to match the file name, not the method name, as I think this is the general rule we follow.

Missing methods:
- **Angle:**  `Point, Point, Point`.
- **ControlPoints:** `ICurve`.
- **Length:** `ICurve`.

**Review by LMarkowski — APPROVED** [review]
It seems that .gh scripts for Length and CullDuplicate were not saved after the updates, but I deserialized the datasets and everything seems to be alright. Approving.

**Comment by rolyhudson** [comment]
@BHoMBot  check-ready-to-merge

**Comment by rolyhudson** [comment]
@BHoMBot check-ready-to-merge

**Comment by rolyhudson** [comment]
@BHoMBot check ready-to-merge

**Comment by rolyhudson** [comment]
@BHoMBot check core

**Comment by rolyhudson** [comment]
@BHoMBot check installer

**Comment by rolyhudson** [comment]
@BHoMBot check ready-to-merge

**Comment by rolyhudson** [comment]
@BHoMBot check ready-to-merge

**Comment by rolyhudson** [comment]
@FraserGreenroyd any idea why ready-to-merge is failing? Core and installer both passed yet ready-to-merge reports otherwise.

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd any idea why ready-to-merge is failing? Core and installer both passed yet ready-to-merge reports otherwise.

Could be related to the names change discussed this morning, lemme take a quick look

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@rolyhudson there you go, all fixed :smile:

**Comment by rolyhudson** [comment]
@BHoMBot check unit-tests

**Comment by rolyhudson** [comment]
@FraserGreenroyd @LMarkowski this one is ready to go. Failing unit tests are the old trouble makers although I thought RoundCoordinates had been fixed @LMarkowski?

**Comment by LMarkowski** [comment]
@rolyhudson, LGTM, I think my previous review is still valid.

 `RoundCoordinates` is fixed but waiting for a final review and merging 😄 #2428

**Comment by rolyhudson** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
Adding myself to hit merge once checks pass per discussion in sprint coordination

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
image

Well this is fun @rolyhudson - are you happy to resolve this? Should be simple enough given it's all JSON related.

**Comment by rolyhudson** [comment]
@FraserGreenroyd yes I will have a look and see. Getting updated to master may well be enough I think.

**Comment by rolyhudson** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by rolyhudson** [comment]
@FraserGreenroyd looks good now. Unit-tests will fail because of tests added outside of this PR. (MapRegions and RoundCoordinates).

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
image
Alas not @rolyhudson - I suspect it needs a manual rebase or a redo.

**Comment by rolyhudson** [comment]
Closing this and will redo and re PR with identical JSON datasets

**Pull request closed without merging**
