### PR TITLE
Reflection_Engine: Fixes necessary for the RunCode component

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
Provide support for this UI PR: 

   
### Issues addressed by this PR

A few small fixes needed for the new RunCode component to work properly (see changelog).

### Changelog
- Fix hard-coded separator instead of using the one provided as input in the ToText method
- Make sure assemblies are collected only once even for BHoM dlls
- Allow to collect indirect references in UsedAssemblies

### CODE REVIEW

**Review by rolyhudson — APPROVED** [review]
See my notes [here](https://github.com/BHoM/BHoM_UI/pull/352#issuecomment-756271377) on the experience of using this handy prototype .

**Comment by adecler** [comment]
@BHoMBot check copyright

**Pull request merged**
