### PR TITLE
DataStructure&Geometry_Engine-Issues594,803,804-TypoInDiscretePoint&MigrateDBSCAN

### PR DESCRIPTION
**Pull request by pawelbaran**
**To be merged together with [#416](https://github.com/BHoM/BHoM/pull/416)!**

Closing #594 
Closing #803 
Closing #804 

A generic DBSCAN algorithm capable of taking any object type and any method as metric function has been implemented - no drop in performance was observed on PointClusters method. Test file located [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FGeometry_Engine%2FBHoM_Engine-Issue594-ExposeGenericDBSCAN).

In order to remove Geometry_Engine reference from DataStructure_Engine, a new `PMSquareDistance` method has been implemented. It is a bit lame as it is exactly same method as `Point.SquareDistance`.

As far as I understand, the DataStructure_oM and Engine should not be limited to 3 dimensions (as they might work on abstract data, not only geometry), therefore I would recommend:
- replacing the geometrical `Point` in `LocalData.Position` with a generic, n-dimensional `DataPoint` with coordinates stored in an array of doubles
- making `DiscretePoint` n-dimensional with coordinates stored in an array of integers
- declaring the number of dimensions when creating an instance of `PointMatrix`
- adjusting all methods to work on n dimensions instead of 3 (X, Y, Z)

This would be an elegant way to keep the PointMatrix generic and completely independent of Geometry_oM & Engine. I could raise an issue in the BHoM and implement it in the next PR. What do you guys think? @epignatelli @al-fisher @IsakNaslundBh

### CODE REVIEW

**Comment by pawelbaran** [comment]
Good points, @epignatelli. I thought that DataStructure_Engine is, by definition, a generic, data-specific engine - the one in which one would keep general matrix/sorting/clustering-related stuff. Am I wrong? If so, where should all that go?

Concerning the code structure, I have seen the private helper classes in other places (even the header is copied), so assumed that in certain cases it is allowed. Exposing DBSCAN in chunks seems to be quite pointless to me (it works as one entity). An alternative could be rewriting the code to have everything clustered in one method - not sure if it makes any sense either.

**Comment by epignatelli** [comment]
I think the DataStructure refers specifically to computational constructs. The limit with math is quite thin.
I see this pr more related to a Mathematics Engine, it is actually pure math. 
It is great to have a generic clustering method!!

For the code itself, yes there are other places where we have private classes. They exist either because there was no other way to achieve the goal, or they're incorrect, and should be targeted by a compliance issue. The general guideline is something like "always public, if you can't, go private", but not the opposite. In this case I think we can avoid doing that. It does work as one entity, but it's also true that the smaller function may serve other purposes: mean-shift, hierarchical, and so on. I'd keep the modular structure we're used to.

**Comment by pawelbaran** [comment]
@epignatelli maybe I am ignorant, but do we have Mathematics Engine? And which part of this PR would you relate to it? I would say DBSCAN in its generic form is not pure mathematics, but more algorithm/data structure stuff.

Concerning the code structure, would you recommend making the classes public and moving them to the BHoM? I am good with that, what do you think @al-fisher @adecler?

**Comment by epignatelli** [comment]
No, sorry - there is no Math namespace at the moment, I meant to create it. I would related just #594 to that.

My proposal for the code is:
- Move `DBScanObject<T>` to the oM, make it public
- Move it's constructor the the `Create` class of the engine
- Make `ComputeClusters` public static in the `Compute` class
- Make `ExpandCluster` public static in the `Compute` class
- Make `RegionQuery` public static in the `Query` class
- Move `PointClusters` to the Geometry_Engine and maybe call it `DBPointClusters`?
- We might remove the redundancy in the names as well and make them more specific to DBScan operations

Now, in what namespace/project, I think it's another issue and I am up for discussion about it!

If we isolate #594 from the other issues, you should be able to solve the others in this pr quite quickly.

In general, as you suggested I'd wait for @adecler and @al-fisher 's inputs before doing anything.

**Comment by pawelbaran** [comment]
Oke, let's wait for the others to comment. In general I agree with everything you proposed.

**Comment by pawelbaran** [comment]
Further changes made with regard to this issue:
- `PointClusters` had been deprecated, `PointClustersDBSCAN` method added
- `DBSCANAlgorithm` and `DBSCANObject` classes have been added in the [BHoM](https://github.com/BHoM/BHoM/pull/416) together with Create methods in BHoM_Engine
- DBSCAN-related method `ComputeClusters` has been refactored to comply with BHoM

I would say let's merge this PR together with [#416](https://github.com/BHoM/BHoM/pull/416) and raise an issue concerning a duplicated `SquareDistance` method in DataStructure_Engine.

Would be nice if @al-fisher @rwemay @adecler gave their opinion - this one is blocking the Geometry_Engine, which is starting to be an obstacle. Thanks!

**Comment by epignatelli** [comment]
Nice, thanks @pawelbaran for addressing those! Having a generic `Func<T, T, bool>` potentially allows also to specify a custom function, and compile it on the fly. Looks great!

Still need to check the reference issue, but happy for the changes to the DBScan!

**Comment by al-fisher** [comment]
Previously raised Maths engine issue: https://github.com/BHoM/BHoM_Engine/issues/562

**Comment by pawelbaran** [comment]
@al-fisher thanks for merging. I let myself reopen the discussion concerning the Maths engine & oM - please see #562. Concerning public/private, so far it was not an issue for me at all.

**Pull request merged**
