### PR TITLE
Environment_Engine: Update PanelsContainingPoint to also return the panels not containing the point

### LINKED ISSUE #3156: Environment_Engine: Panels containing point to return panels not containing the point
Similar to other filters implemented around the Environment Engine, it's helpful for users if they can also get back the list of panels which don't contain the point when using `PanelsContainingPoint`.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #3156

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by jamesramsden-bh — APPROVED** [review]
Tested through and works as expected

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Pull request merged**
