### PR TITLE
BHoM_Engine: Set up CI

### LINKED ISSUE #1315: BHoM_Engine: Prepare for CI
Prepare this repo for CI checks.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #1315

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@al-fisher this is ready for review now :smile:

@IsakNaslundBh be advised, I fixed some references in `Structure_Engine` for CI, please feel free to check you're happy with them

@alelom be advised, I fixed some references in `Diffing_Engine` for CI, please feel free to check you're happy with them

@tg359 be advised, I fixed some references in `Environment_Engine` for CI - I am already happy with them but feel free to check yourself as well

**Comment by IsakNaslundBh** [comment]
Happy with the correction of the Reference for Structures_Engine. Surprised that had not been flagged and fixed before. Thanks 👍

**Comment by alelom** [comment]
Thanks for the fix in the Diffing_Engine @FraserGreenroyd

**Pull request merged**
