### PR TITLE
Architecture_Engine: Compliance Update

### LINKED ISSUE #1507: Architecture_Engine - Compliance issues
This report has been generated as part of a close out for the 3.1 milestone compliance and outlines all of the compliance issues currently highlighted by the CI team. I will be undertaking this issue to resolve all compliance issues which do not impact scripts or versioning, with the remainder being moved to the 3.2 milestone for further discussion and resolution.

The following compliance issues have been found for this project. Please see the checklist below.
##### Copyright message is invalid
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\SeatingBlock.cs at line 20, column 0 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\TierProfile.cs at line 20, column 0 

##### Create file  must match the create method(s) return type. Either part of the path or the filename must be an exact match of the return type of the method. If the file name does not match the return type file name must match the method name.
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\CircularStadiaPlan.cs at line 36, column 35 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\EightArcStadiaPlan.cs at line 36, column 35 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\FourArcStadiaPlan.cs at line 35, column 35 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\NoCornersStadiaPlan.cs at line 36, column 35 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\OrthogonalStadiaPlan.cs at line 36, column 35 

##### Input attribute is not unique
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\ActivityArea.cs at line 57, column 9 

##### Method name should start with an upper case character
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\CircularStadiaPlan.cs at line 45, column 28 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\EightArcStadiaPlan.cs at line 47, column 28 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\EightArcStadiaPlan.cs at line 179, column 43 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\EightArcStadiaPlan.cs at line 226, column 29 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\NoCornersStadiaPlan.cs at line 46, column 28 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\OrthogonalStadiaPlan.cs at line 46, column 28 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\TheatronPlan.cs at line 94, column 28 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\TheatronPlan.cs at line 102, column 43 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\TheatronPlan.cs at line 132, column 43 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\TheatronPlan.cs at line 144, column 28 
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\TheatronPlan.cs at line 169, column 32 

##### Input attribute does not match any of the given parameters
 - [x] in BHoM_Engine\Architecture_Engine\Create\Theatron\TheatronFullProfile.cs at line 69, column 15

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #1507 

### Test files
N/A

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
The compliance report has failed on punctuation which is deemed as acceptable for this current work and this PR can be merged, following successful review, with that problem on the report.

**Comment by IsakNaslundBh** [comment]
@rolyhudson As this is more or less only impacting your methods, do you mind reviewing this?

**Pull request merged**
