### PR TITLE
MEP_Engine: Changes from refactor

### LINKED ISSUE #2255: MEP_Engine: Changes to match linear elements refactor
#### Description:

See oM issue https://github.com/BHoM/BHoM/issues/1139 for proposed functionality changes.

### PR DESCRIPTION
**Pull request by michaelhoehn**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1193
   
### Issues addressed by this PR

Closes #2255 

### Test files

[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/MEP_oM/%231139-MEPRefactor.gh?csf=1&web=1&e=agBeMY)

### CODE REVIEW

**Comment by michaelhoehn** [comment]
Placing DNM until Revit_TK PR is up.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
This PR has been deemed stale owing to the length of time it has been open resulting in it being behind several major changes since being opened. There has been no activity since April 2021, and no visible linkage to a priority workflow item.

Though the PR will be closed, the code will be visible and is forever recorded here. If at any point the code changes proposed by this PR are required in the future, we can revisit them with minimal effort.

If there are any concerns, please reach out :smile:

**Pull request closed without merging**
