### PR TITLE
Search_Engine: Update unit tests for ExtractAll, ExtractTop, ExtractSorted and MatchScore

### LINKED ISSUE #3376: Search_Engine: Extract methods failing unit tests
#### Description:

https://github.com/BHoM/BHoM_Engine/pull/3375/checks?check_run_id=27334488723

#### Steps to reproduce:

See test file.

#### Expected behaviour:

Pass unit tests.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1628
   
### Issues addressed by this PR

Closes #3376 

### Test files

[#3376-SearchEngineUTFailure](https://burohappold.sharepoint.com/:u:/s/BHoM/EQzznzpXDXBJo2pN_2sQB64BEjTLBiLoysn7RLHbf_wDGw?e=oTCArY)

### Changelog

- Updated `UnitTest`s for `ExtractAll`, `ExtractTop`, `ExtractSorted` and `MatchScore` to reflect the changes made in `Search_oM`.

### Additional comments

One issue with unit tests was caused because it included a `CustomObject` that could not be serialised.

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Review by pawelbaran — APPROVED** [review]
Changes make sense, happy to approve.

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
Dispensating on the basis of a fact that this PR lowers the number of failing UTs and does not introduce any new ones.

**Comment by pawelbaran** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 27369815469

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check dataset-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check dataset-compliance

**Pull request merged**
