### PR TITLE
BHoM_Engine: Upgrade Mongo Bson package and centralise dependencies

### LINKED ISSUE #1875: BHoM_Engine: Upgrade Mongo Bson package and remove as many dependencies to it as possible
We need to upgrade Mongo Bson to fix BHoM/BHoM_Engine#1760

It is important to also remove the direct dependency to Bson for most engines other than Serialisation and versioning. Here's the engines currently referencing Mongo.Bson:

Serialiser_Engine
Diffing_Engine
Environment_Engine

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #1875 

As mentioned in the issue this upgrades the Bson package to fix the remaining issue we had with serialisation. 
This also centralise better the functionality related to conversions to and from Bson for consistency of behaviour and for simplicity purposes.

### Test files
There's a few things you can do to test this PR:
- Make sure everything still compile
- Test that the diffing engine is still working fine (@alelom)
- Serialise a few objects by using ToBytes-> FromBytes and makes sure they are still teh same. Personally, I have used the [serialisation test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Serializer_Engine/serialisationTest.gh?csf=1&web=1&e=nyVLwI) that check that all files serialise properly

### Changelog
- Removing reference to Bson package in Environment engine
- Adding functionality for serialisation with Streams and byte arrays
- Removing reference to Mongo Bson in Diffing Engine
- Ugrading Bson package to 2.10.4

### Additional comments
I will now do the PRs on Versioning and Mong to upgrade their Bson package as well and on Sockets and File_Adapter to remove the reference to Bson by using the new functionality provided here. The only PR that will need to be merge at the same time is the Versioning_Toolkit one though (just in case 2.4 is not compatible with 2.10, which I doubt but better be safe).

### CODE REVIEW

**Comment by adecler** [comment]
@IsakNaslundBh , nice catch!. 
Weird that it was not showing on the GitHub search nor on the VS search. Didn't help that it was not telling us in the build output either !

On a separate note, I noticed two things while looking atteh build output:
- Physical_Engine still has a reference to `Common_oM` (@kThorsager , @IsakNaslundBh  ?)
- It would be great to get rid of the Newtonsoft json package in the Diffing engine and use our own solution for Json instead (@alelom ).

**Comment by adecler** [comment]
Switched to using Mongo 2.9.3 instead of 2.10.4 for compatibility reasons with VS2015. 
See https://github.com/BHoM/Mongo_Toolkit/pull/118#issuecomment-652761838 for more details.

**Comment by kThorsager** [comment]
> * Physical_Engine still has a reference to `Common_oM` (@kThorsager , @IsakNaslundBh  ?)

Not intended, and is not needed, just overlooked among all the other reference removals. (or looks to have been added just days before the removal of the oM, which might be why we missed it, but still)

**Comment by adecler** [comment]
The installer check seems to complain about the versioning toolkit. Unfortunately,  I cannot get more information than this:

image

This needs reaproving anyway thanks to [that PR](https://github.com/BHoM/BHoM_Engine/pull/1883) being created and merged while this one was waiting review.

**Comment by FraserGreenroyd** [comment]
image


So it looks like Versioning toolkit can't find the Mongo file correctly. It's odd and makes no sense from what I could see for how the Mongo reference is set up within the Versioning Toolkit, but I was able to replicate the CI failure on my local machine (using this PR branch, and `master` for Versioning TK).

However, what I'm not understanding is how this PR has brought it about. I've tried rebuilding locally on this branch and `master` and sure enough this PR is resulting in the breakage. It's evidently something to do with the Mongo version (which I know, is obvious but, just in case it wasn't...).

Testing this PR in conjunction with the [Versioning PR](https://github.com/BHoM/Versioning_Toolkit/pull/85) however did not cause any issues. Similarly, testing the Versioning PR while on `master` for BHoM Engine also did not reveal any compilation problems.

**Therefore, I advise the issue be resolved by merging the Versioning Toolkit PR (linked above) and rerun the check on this PR.** Alternatively, branch from the Versioning PR branch onto a branch name matching this one to allow the CI checks to detect it and evaluate that way. However, that would then require juggling the Versioning PRs to merge the correct one. Given the Versioning PR has no issues against `master` of BHoM Engine, it seems to pose no risk to merge that ahead of this one. But I shall allow final decision to rest with @adecler for how best to handle this.

As an aside, I am happy to approve this PR again following the testing done to understand this particular CI problem, which I will do momentarily so that if @adecler opts to go for the merge and rerun option, then this can all be done within his time zone without needing to further wait for review here :smile:

**Comment by adecler** [comment]
Thanks @FraserGreenroyd , The Versioning PR has to be merged at teh same time as this one as being on different versions of Bson would break the Versioning (they would not understand each other).

**Comment by FraserGreenroyd** [comment]
Ok no worries @adecler :smile: I think my theory will hold (that merging Versioning will fix the check on this PR), however, to do this safely (and thus properly) we should get this PR on the same branch as the Versioning one (or vice versa) to allow the CI checks to pick up both sets of changes at once and evaluate them together. At the moment the CI on this PR is checking the `master` branch of Versioning Toolkit because the Versioning PR is on a different branch (which is the bit that I'm still not quite sure I understand because I haven't investigated, because the Versioning PR is checking the `master` branch of BHoM_Engine and is working fine, but I'm sure there's a good reason for it if I went looking).

Anyhow, to recap a summary then of needed actions:

Either:

 - Close this PR and reraise using the same branch name as the Versioning Toolkit PR
OR
 - Close the Versioning PR and reraise using the same branch name as this PR

And see where we go from there :smile:

**Comment by adecler** [comment]
Hahaha, so  I created a separate PR from a branch that has the same name as the versioning branch. It did solve the problem as you predicted @FraserGreenroyd . The funny thing is that running the checks on that branch also reran the checks on this one :smile:. So we could even merge this one (which is probably better given that we have a trace of all the comments).

Now I just need to figure out who else has merged code that clashes with this PR and fix it.

**Comment by adecler** [comment]
Alright, the conflict is resolved so now the only thing left is to approve once more

**Pull request merged**
