### PR TITLE
Aligning to IResult interface reformulation

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1279
   
### Issues addressed by this PR

Closes https://github.com/BHoM/BHoM_Engine/issues/2603

Aligns to https://github.com/BHoM/BHoM/pull/1279, updating the bare minimum of methods in order to support the changes.

Methods that operated on the previous version of `IResult` that can now rely on more basics implementations of the new `IResult` interface. For example, [`GroupByObjectId()`](https://github.com/BHoM/BHoM_Engine/pull/2604/commits/557e8c5c58336d2bde269a9951ee104dc9b0de83#diff-c1af917ae24d685e82f66723bee09560eefe1308c03a5c7f77f90dfe84164f39R45-R48) and [`GroupByTimeStep()`](https://github.com/BHoM/BHoM_Engine/pull/2604/commits/557e8c5c58336d2bde269a9951ee104dc9b0de83#diff-c1af917ae24d685e82f66723bee09560eefe1308c03a5c7f77f90dfe84164f39R52-R55) now operate respectively on `IObjectIdResult` and `ITimeStepResult`, because that's all they need. Similarly, [`MapResults()` did not actually need to require the property `ResultCase`](https://github.com/BHoM/BHoM_Engine/commit/686216b3de335b07f6f7730a487664451ce65334), as it is optional.

This allows for more flexibility, because they can be applied to objects that implement the bare minimum required to make the engine method work, instead of operating only on objects that had all the properties required by the previous version of `IResult` (namely `ObjectId`, `ResultCase`, `TimeStep`).

### CODE REVIEW

**Review by IsakNaslundBh — APPROVED** [review]
All looking good to me!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check required

**Review by IsakNaslundBh — APPROVED** [review]
Re-approving! Looks good to me!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
