### PR TITLE
Humans_Engine: Cvalue analysis improvements

### PR DESCRIPTION
**Pull request by rolyhudson**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1203

   
### Issues addressed by this PR

Closes
#951
#1073
BHoM/BHoM_Engine#2137

### Test files

Validation and demonstration [test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Humans_Engine/%232334_c_valueexplorer.gh?csf=1&web=1&e=tBd4Wu)

### CODE REVIEW

**Comment by jdarcyBHE** [comment]
A couple of things from running the test script.
Minor - The CvalueAnalysis component needs to be recreated, I tested on the latest alpha not sure why the versioning wasn't able to find the component.
image
****

More Major - The display shows the direction of the audience to the focus point, something seems to throw some of the lines off, it appears to happen by bay hence the bands of lines at the same angle.
image

**Comment by rolyhudson** [comment]
@jdarcyBHE I think your build has not worked. Did you build the dependent PR? 
Based on the images I can see that the updates from this PR are not visible:
`CvalueAnalysis` component has a focalPoint input 
'CvalueSettings` now includes `FarClippingPlaneDistance` and `ViewConeAngle`
Let me know if you need help building.

**Comment by jdarcyBHE** [comment]
Hmm I used the latest Alpha, I will try again and let you know if I still have the same errors.

**Comment by rolyhudson** [comment]
> Hmm I used the latest Alpha, I will try again and let you know if I still have the same errors.

@jdarcyBHE changes are in the PR branches not the alpha. You will need to build BHoM and BHoM_Engine locally to test. These changes are up for merging into the alpha if approved. Let me know if that does not make sense.

**Comment by jdarcyBHE** [comment]
Test file works, as discussed with @rolyhudson some seats experience Cvalues below the specified however this is due to method of calculation and requires conversations and statement of how we believe this best represents this metric.

**Review by jdarcyBHE — APPROVED** [review]

**Review by al-fisher — APPROVED** [review]
@rolyhudson happy to approve this based on @jdarcyBHE functionality review and a code review and discussion about future documentation. 
Capturing here comments regarding further work to document the inner logic of the algorithm and base assumptions. Will be good to be link back to the source code itself the work being done to illustrate this principles in diagram form - as wells as providing references to sources as appropriate etc. here - perhaps in first instance as simple hyperlinks in the method descriptions etc. 
But equally good to think about similar principles to the `Source` in the `Datasets` to formalise in the long term.
Let's raise a `documentation` issue now to revisit documentation attributes on these methods with explanations are complete.
Also as mentioned - in the context of this work - the structure of a number of private methods exposed through limited public methods makes sense

Approving (but you do need check installer to pass also! :smile:) @rolyhudson @FraserGreenroyd

**Comment by rolyhudson** [comment]
Thanks for the review @al-fisher. Issue has been raised for documentation https://github.com/BHoM/BHoM_Engine/issues/2384. 
Also could you please provide approval on the dependent PR https://github.com/BHoM/BHoM/pull/1203
check installer now passing (here and the dependent PR) after updating to master 👍

**Comment by rolyhudson** [comment]
Created issue for required versioning: https://github.com/BHoM/BHoM_Engine/issues/2391

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2090684896

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Pull request merged**
