### PR TITLE
Serialiser_Engine: Remove old serialiser code

### LINKED ISSUE #3088: Serialiser_Engine: Remove the old serialisation code
#### Broken rules:
The legacy serialiser code is still present even though it shouldn't be used anymore

#### Suggestions to restore compliance:
delete the old serialiser code that uses class maps

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #3088

Now that we had a decent period of time for testing the new serialiser, we should remove the old code before the beta is created.

### Test files
I am only removing code that shouldn't be used anymore but it is good to run the usual set of tests to make sure the serialiser is still working as expected.

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check serialisation

**Comment by adecler** [comment]
@BHomBot check compliance

**Comment by adecler** [comment]
@BHoMBot check versioning

**Comment by adecler** [comment]
@BHoMBot check versioning

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by adecler** [comment]
@BHoMBot check serialisation

**Comment by adecler** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check unit-tests
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
Reapproving following addition of versioning file

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 14297044500

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
