### PR TITLE
Structure_Engine: Fix bug for the Mass method (for Panels)

### LINKED ISSUE #2854: Structure_Engine: MassPerArea() to align with Mass(IElementM)
#### Description:

Mass(Panel) and Mass(IElementM) don't return the same number for panels with ReinforcementDensity. This is a result of MassPerArea(Panel) not considering the Reinforcement Density.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #2854 

### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Structure_Engine/%232854-MassPerAreaNotAccountingForReinforcementDensity/%232854.gh?csf=1&web=1&e=umvd2d

### Changelog

- Fixed bug in the `Structure.Query.Mass(Panel)` method that was not accounting for `ReinforcementDensity`.

### Additional comments

The two `Mass` methods are quite old, is there an argument they are redundant now we have the `Mass` methods for `IElementM` and `IElement1D`?

### CODE REVIEW

**Review by MayaAroraJonsson — DISMISSED** [review]
Checked using test script.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
Last commit was only to unit tests, @MayaAroraJonsson previous review for functionality is still valid, so approving for merge based on that.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: dataset-compliance, unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
