### PR TITLE
Data_Engine: Remove redundant filter query

### LINKED ISSUE #1438: Data_Engine: Deprecate BH.Engine.Data.Query.Filter
#### Broken rules:
The method is merely calling with same inputs `Compute.FilterData` plus seemingly it is not used anywhere (needs to be cross-checked with all dependent projects).

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #1438

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Review by Tom-Kingstone — APPROVED** [review]
On code review, looks good, and it versions correctly.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
