### PR TITLE
8.0 Deployment

### PR DESCRIPTION
**Pull request by BHoMBot**
#### Feature
 - [BHoM_Engine: TryRunExtensionMethod made more sensitive to inputs](https://github.com/BHoM/BHoM_Engine/pull/3425)
 - [Diffing_Engine: Do not include static properties and fields in differences](https://github.com/BHoM/BHoM_Engine/pull/3410)
 - [Diffing_Engine: Performance of IsEqual improved](https://github.com/BHoM/BHoM_Engine/pull/3428)
 - [Facade_Engine: Added continuous UValue Calc to SAM method and Overarching UValue Methode for Collections of Elements](https://github.com/BHoM/BHoM_Engine/pull/3435)
 - [Geometry_Enigne: Full refactor of polyline offset](https://github.com/BHoM/BHoM_Engine/pull/3394)
 - [Verification_Engine added](https://github.com/BHoM/BHoM_Engine/pull/3431)
#### Bug
 - [BHoM_Engine: rounding issues fixed](https://github.com/BHoM/BHoM_Engine/pull/3430)
 - [Verification_Engine - Report Message null checks added](https://github.com/BHoM/BHoM_Engine/pull/3433)
#### Compliance
 - [Start of milestone changes for 8.0](https://github.com/BHoM/BHoM_Engine/pull/3417)

### CODE REVIEW

**Comment by vgreen-BH** [comment]
@BeatrixRossi Review Requested

**Review by chrismcoulter — APPROVED** [review]
Lighting_Engine testing passed 13DEC24

**Review by peterjamesnugent — APPROVED** [review]
No changes relating to Structure_Engine this milestone, and beta installer test scripts are working as intended. Happy to approve from a structures perspective.

**Review by pawelbaran — APPROVED** [review]
Happy to approve from the side of Verification

**Review by vgreen-BH — APPROVED** [review]
Facade_Engine passed using 12/17/2024 install

**Review by jamesramsden-bh — COMMENTED** [review]
Environment Engine approved as per any comments in test report document

**Pull request merged**
