### PR TITLE
Geometry_Engine: Add initial unit tests

### LINKED ISSUE #2272: Geometry_Engine: Add unit tests
#### Definition of the test :
Based on the [discussion](https://github.com/BHoM/BHoM/discussions/1148) add unit tests for the following:
 `Query.IsContaining`
 `Query.Bounds`
 `Query.LineIntersections`
 `Query.Normal`
 `Compute.BooleanUnion`
 `Query.Distance`
 `Query.Area`
 `Compute.BooleanIntersection`
 `Query.PointAtParameter`
 `Query.DiscontinuityPoints`
 `Compute.CurveProximity`
 `Query.ClosestPoint`
 `Query.Centroid`
List is prioritised by count of file changes in github.

### PR DESCRIPTION
**Pull request by rolyhudson**
### Issues addressed by this PR
Initial Geometry_Engine unit tests determined by file change frequency.
`Query.IsContaining`
 `Query.Bounds`
 `Query.Normal`
 `Compute.BooleanUnion`
 `Query.Distance`
 `Query.Area`
 `Query.PointAtParameter`
 `Query.DiscontinuityPoints`
 `Compute.CurveProximity`
 `Query.ClosestPoint`
 `Query.Centroid`
`Modify.Transform`

Also now with the possibility of test for null returns:
`Compute.BooleanIntersection`
`Query.LineIntersections`
Closes #2272 

### Test files
Files used to create tests:
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Geometry_Engine/%232276-InitialUnitTests?csf=1&web=1&e=EyCiGC

### CODE REVIEW

**Comment by rolyhudson** [comment]
@BHoMBot check unit tests

**Comment by LMarkowski** [comment]
@BHoMBot check unit tests

**Review by LMarkowski — CHANGES_REQUESTED** [review]
Did quite an insightful review. Generally all looks good but I've found few flaws in the .gh scripts:
- BooleanUnion:
  - UT for `List<Polycurve>` is created with output data instead of input.
- CurveProximity:
  - While running `CheckTests` in gh all tests return `Running of the method returned a different number of results compared to the expected output` errors. However BHoMBot announced success.
- ClosestPoint:
  - UT for `Vector` returns `Failed to run the comparison` error. 
-  DiscontinuityPoints:
   - UT for `Circle` is not included in the dataset.
- IsContaining:
   - UT for `IGeometry` is not included in the dataset.

Lot of UTs  (e.g. `BooleanUnion(List<Line>)` or all tests for `Normal()`) when plugged into `Run(test)` method log `Index out of range` errors which are absent while computing methods itself. Probably an issue with the test_engine. @IsakNaslundBh, are familiar with that?

PS.
Answering to a comment in LineIntersections.gh - you can re-convert ```System.Collections.Generic.List`1[BH.oM.Geometry.Point]` ``` back into gh tree with a C# component like this:
image

**Comment by rolyhudson** [comment]
Thanks @LMarkowski especially the PS very handy. 
Updated BooleanUnion, DiscontinuityPoints and IsContaining.
I think the problem with CurveProximity is the multi output of the method:
Screenshot 2021-01-26 142217
The ClosestPoint with a vector returns a valid null - upcoming PR on Test_TK should fix to allow this as valid output in a test.
Maybe we should remove all CurveProximity tests and ClosestPoint with a vector for now so we can merge these? What do you think?

**Comment by LMarkowski** [comment]
@rolyhudson 
> Maybe we should remove all CurveProximity tests and ClosestPoint with a vector for now so we can merge these

Yes, that sounds good to me. I can approve it when they'll be removed. Or we can wait a bit until the Test_TK PR will be merged. Also if you could update .gh files (changed in last commit) on sharepoint?

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit tests

**Comment by rolyhudson** [comment]
@LMarkowski updated the linked gh files. I think we should hold with this until the Test_TK pr is merged before moving this forward.

**Comment by rolyhudson** [comment]
@LMarkowski updated unit tests and creation files on SP. I have now rationalised the number of test data sets. So this is ready for a second review pass.

**Comment by rolyhudson** [comment]
@BHoMBot check unit tests

**Review by LMarkowski — CHANGES_REQUESTED** [review]
Most of the tests look perfect. I've found just one more flaw. Oh my, some of those scripts are massive.. 🙈 
- IsContaining:
  - UT for `Circle` and `ICurve` is not included in the UT (5th from the bottom)

One more thing has came up to my mind. I did not cross check if the .gh scripts cover all of the overloaded versions of the methods present in the code. But I guess coverage scripts will eventually pick up any possible misses (if there will be any).

**Comment by rolyhudson** [comment]
@LMarkowski 
> Most of the tests look perfect. I've found just one more flaw. Oh my, some of those scripts are massive.. 🙈
Sorry about the scripts - believe me I understand the pain!
> * IsContaining:
>   
>   * UT for `Circle` and `ICurve` is not included in the UT (5th from the bottom)
Added that 👍 
> One more thing has came up to my mind. I did not cross check if the .gh scripts cover all of the overloaded versions of the methods present in the code. But I guess coverage scripts will eventually pick up any possible misses (if there will be any).
Yes right we need improved coverage to check all paths through the code are covered. Some of those methods have so many paths that I think we may go insane trying to figure out all routes without some kind of tools to help.

**Comment by rolyhudson** [comment]
@BHoMBot check unit tests

**Review by LMarkowski — APPROVED** [review]
All LGTM now!

**Comment by FraserGreenroyd** [comment]
Will review/merge today if all is well, sorry for the delay @rolyhudson

**Review by FraserGreenroyd — APPROVED** [review]
I am terribly sorry for the delay @rolyhudson - this all LGTM with the framework set up. Merging now.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Pull request merged**
