### PR TITLE
Physical_Engine: BulkSolids required IElementM extension methods

### LINKED ISSUE #2112: Physical_Engine: Volume Query Method for BulkMaterials
#### Description:

For use in other toolkits making use of BulkMaterials.

### PR DESCRIPTION
**Pull request by michaelhoehn**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1050
   
### Issues addressed by this PR

Closes #2112 

### Test files

[Here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Physical_oM-Issue1017-BulkMaterials/201029_BulkMaterials.gh?csf=1&web=1&e=OvFmej)

### CODE REVIEW

**Comment by michaelhoehn** [comment]
Proving links to the original draft PR for documentation purposes. 
https://github.com/BHoM/BHoM_Engine/pull/2113

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Review by al-fisher — APPROVED** [review]
LGTM @michaelhoehn 
Think this works well now leveraging the material composition as you have.

**Pull request merged**
