### PR TITLE
Structure_Engine: null checks for description method

### LINKED ISSUE #2101: Structure_Engine: Description methods requires null checks
#### Description

The automatic description methods for the property type objects need null checks to ensure they never crash out. Starting with the interface methods, but the inner methods themselves should also be checked for any nulls.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2101 

Adding null checks for description method, returning a "null _type_" string if a null is provided.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check documentation compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Review by IsakLarbornBH — APPROVED** [review]
Seems to do everything that it should, and I have not been able to break it though I have tried. I approve.

**Comment by FraserGreenroyd** [comment]
> I have not been able to break it though I have tried

I had the same issue, BHoMBot could not find anything wrong either 😆

**Comment by IsakLarbornBH** [comment]
> I had the same issue, BHoMBot could not find anything wrong either 😆

Yeah, isn't it annoying when the code just works? I'm trying to be all nitpicky here

**Comment by IsakNaslundBh** [comment]
Haha, thanks both

**Pull request merged**
