### PR TITLE
Geometry_Engine: point on plane projection fixed

### LINKED ISSUE #2430: Geometry_Engine: Projection of point on plane fails if plane normal is not unit
#### Description:

As in the title, if normal of the plane is not unit, point projection does not work correctly - see the test file.

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?originalPath=aHR0cHM6Ly9idXJvaGFwcG9sZC5zaGFyZXBvaW50LmNvbS86Zjovcy9CSG9NL0V0VDBRWTZTdWwxTXZ0ZGEzcElxTE9jQnotUS1OeWtxMXlPSnF4dEFxcHI2S0E%5FcnRpbWU9Y0VrU1hhYnkyRWc&sortField=LinkFilename&isAscending=true&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%232430%2DProjectOnPlaneBug%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine)

### PR DESCRIPTION
**Pull request by michal-pekacki**
### Issues addressed by this PR

Closes #2430

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%232432%2DProjectOnPlaneBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

### Additional comments

My first PR, please be patient 👼

### CODE REVIEW

**Review by LMarkowski — COMMENTED** [review]
Generally looks very good. One thing that bothers me is if we shouldn't expect from a `Plane` object to have normalised normals? I remember having a similar discussion regarding coordinate systems and their vectors.
Maybe this line should be added to `BH.Engine.Geometry.Create.Plane` instead of here to avoid this issue from re-occurring?

@pawelbaran @IsakNaslundBh @al-fisher

**Comment by IsakNaslundBh** [comment]
>Generally looks very good. One thing that bothers me is if we shouldn't expect from a Plane object to have normalised normals? I remember having a similar discussion regarding coordinate systems and their vectors.
Maybe this line should be added to BH.Engine.Geometry.Create.Plane instead of here to avoid this issue from re-occurring?

The planes are not immutable, while to coordinate systems are though, so even if we add a check in the create method, a simple property assignment or similar would invalidate it. Think it is probably safer to fix the methods in this case actually (although a bit more annoying).

**Comment by pawelbaran** [comment]
I agree with @IsakNaslundBh. In long term I would consider making `Plane` immutable, but I think this will (again) lead to the conclusion that we could make most geometry types immutable.

**Review by LMarkowski — APPROVED** [review]
> The planes are not immutable,

@IsakNaslundBh, fair enough 🙄 

Approving then. Good job!

**Comment by LMarkowski** [comment]
@BHoMBot check all

**Comment by LMarkowski** [comment]
@BHoMBot check installer

**Comment by LMarkowski** [comment]
@BHoMBot check compliance

**Comment by LMarkowski** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check serialisation

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check serialisation

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
