### PR TITLE
MEP_Engine: Remove unnecessary Create methods

### LINKED ISSUE #2037: MEP_Engine: Removal of unnecessary Create methods simply exposing only the Public Defining properties
#### Broken rules:
As per parent issue https://github.com/BHoM/BHoM_Engine/issues/1155 - to be tackled after close out of https://github.com/BHoM/Versioning_Toolkit/issues/96

FYI @FraserGreenroyd @kayleighhoude  - please assign as makes sense 😄

### PR DESCRIPTION
**Pull request by michaelhoehn**
### Issues addressed by this PR

Closes #2037 

### Test files

[Here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/MEP_Engine/MEP_Engine-Issue2037-RemoveUnnecessaryCreates.gh?csf=1&web=1&e=ocs7sb)

### CODE REVIEW

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
LGTM

**Pull request merged**
