### PR TITLE
Serialiser_Engine: Protect against BSON having no values in list deserialisation

### LINKED ISSUE #3168: Serialiser_Engine: Protect Bson not having an index
While testing https://github.com/BHoM/Versioning_Toolkit/pull/231 locally with @albinber we found a `TargetInvocation` error being thrown https://github.com/BHoM/BHoM_Engine/blob/develop/Serialiser_Engine/Compute/Deserialise/List.cs#L88 here - where the bson object was an array according to bson, but had no elements so `[0]` was throwing an error.

Add a protection to that just in case.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #3168 

Running tests used on the Versioning PR should be sufficient.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by albinber — DISMISSED** [review]
Ran versioning tests locally, check is happy.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Review by adecler — COMMENTED** [review]
Why the try-catch instead of a simple check on the array here ?

**Review by adecler — COMMENTED** [review]
That looks better. 
@albinber, can you re-run the test to make sure everything checks out ?

**Review by albinber — APPROVED** [review]
Re-did versioning locally, all good :)

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Pull request merged**
