### PR TITLE
BHoM_Engine: Add methods to query the current event log suppression state

### LINKED ISSUE #3306: Base_Engine: Add ability to query suppression state of events
Now we can suppress event recording, it would be helpful to be able to query the suppression state.

This will be helpful in resolving https://github.com/BHoM/BHoM_UI/issues/485 - knowing if the events were already suppressed by the user in a UI prior to running the method will help ensure the UX for the user does not change suppression state.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #3306

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check installer

**Review by Tom-Kingstone — APPROVED** [review]
Updated make sense for querying whether errors etc. are suppressed. Approved.

**Review by albinber — APPROVED** [review]
Changes make sense and code looks good, happy to approve.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Pull request merged**
