### PR TITLE
Spatial_Engine: Update failing UTs in Spatial engine

### LINKED ISSUE #3345: Update failing spatial UTs
#### Definition of the test :

Spatial engine tests failing due to changes to fit plane and IsPlanar.

For FitPlane a mixture of smae results and results with flipped normals is seen. The direction of the normal is arbitrary, why a simple regeneration is fine.

For RoundCoordinates the two failure cases are due to the new panel no longer seen as planar. As the new system is more mathematically exact, I think it is ok to simply regenerate this test as well.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #3345

Both updated by simple regeneration.

FitPlane was not really failing. A completely flipped normal of the plane is still the same semantic plane, why a simple regeneration is acceptable.

The two failing cases for round coordinates were due to some of the resulting planes no longer being treated as planar. As the new method for IsPlanar is more exact, I think it is acceptable to regenerate these as well.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
Not really sure why this is hanging. Runs on my machine, with passing results. @FraserGreenroyd are you able to see what is going on on the bot?

**Comment by FraserGreenroyd** [comment]
> Not really sure why this is hanging. Runs on my machine, with passing results. @FraserGreenroyd are you able to see what is going on on the bot?

Had a look, couldn't see any issue. I recommend rerunning.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by pawelbaran — APPROVED** [review]
Approving on the basis of a discussion with @IsakNaslundBh

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 24768146530

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
