### PR TITLE
Aligning with Grid and Level migration to Spatial

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1347
   
### Changelog

- Migrating all methods to do with Grids and Levels in Geometry_Engine to Spatial_Engine
- Aligning all other Engines to changes made

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

Using the Bot to identify the toolkits affected by this change. I do not expect this check to pass.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

Using the Bot to identify the toolkits affected by this change. I do not expect this check to pass.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
I have reviewed the files changed and am happy that the changes match those required from the dependant PR.
I am happy with the changes made specifically to the Environment_Engine as well.
The bot is happy with the installer and versioning, so I'm happy with this being merged into `main`.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, code-compliance, copyright-compliance, documentation-compliance, project-compliance, serialisation, ready-to-merge, null-handling, dataset-compliance

**Pull request merged**
