### PR TITLE
Environment_Engine: Floor geometry method fix

### LINKED ISSUE #871: Environment_Engine: Fix Floor Geometry method
The `FloorGeometry` method does not return the full floor geometry in the event where multiple `BuildingElement`s make up the space.

May be rewritten as part of ongoing oM/Engine changes with @IsakNaslundBh later in the month - capturing here to be considered.

Related to https://github.com/BHoM/XML_Toolkit/issues/103

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #871 

### Test files
Existing test files

#### Fixed
 - Fixed Floor Geometry method

### CODE REVIEW

**Comment by rwemay** [comment]
Is it a good idea to hardcode this tolerance?

**Comment by michaldengusiak** [comment]
it is exposed, just default


image

**Comment by rwemay** [comment]
Ok cool. For some reason I thought we also had a global default tolerance setting/system which methods can use - a bit like the default tolerance in Rhino/Dynamo etc. Maybe one for later if now. 

@IsakNaslundBh

**Comment by al-fisher** [comment]
Hey @rwemay - you are right - we do. https://github.com/BHoM/BHoM/blob/master/Geometry_oM/Misc/Tolerance.cs
@michaldengusiak good to reference tolerance from here to keep consistent. Although, still should also only be a default and still exposed as you have implemented.

Consider ``` double tolerance = BH.oM.Geometry.Tolerance.Distance ```

**Pull request merged**
