### PR TITLE
Serialiser_Engine: RegisterClassMaps added for entire assemblies

### LINKED ISSUE #2451: Serialiser_Engine: add a public method to register class maps for an assembly not loaded on startup
#### Description:

As in the title.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #2451

### Test files

Very minimalistic test on [SharePoint](http://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F02_Pull%20Request%2FBHoM%2FBHoM_Engine%2FSerialiser_Engine%2F%232453-RegisterClassMaps&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### CODE REVIEW

**Comment by pawelbaran** [comment]
@adecler I have refactored the branch to make it a bit more sensible - I hope the changes will make sense to you. I have also added a very basic test file, please see the PR description (not sure how to build an automated test for that).

**Comment by pawelbaran** [comment]
@BHoMBot check serialisation

**Comment by pawelbaran** [comment]
Ahh, one important thing @adecler: I have not added locks on the private field, not sure if it is worth doing tbh. Could you please reflect on that while reviewing?

**Comment by adecler** [comment]
@BHoMBot check project-compliance

**Comment by adecler** [comment]
@BHoMBot check documentation-compliance

**Comment by adecler** [comment]
@BHoMBot check dataset-compliance

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@BHoMBot check null-handling

**Comment by adecler** [comment]
@BHoMBot check core

**Comment by adecler** [comment]
@BHoMBot check versioning

**Comment by adecler** [comment]
@BHoMBot check installer

**Review by adecler — APPROVED** [review]
Thanks @pawelbaran , this version looks better 👍 . 
From my tests, it seems that everything is working exactly like before. Glad to see that the CI/CD test on serialisation is also passing 😄 .
I wouldn't worry about the lock in this case since your private field is a `MethodInfo`, not a data structure.

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null handling

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
I'm happy with the code-compliance to receive dispensation, but not the `null-handling`. The report is saying this PR makes the situation worse, it would be nice if it didn't please :smile:

**Comment by pawelbaran** [comment]
@FraserGreenroyd from what I know, I have added 1 method that starts from `if(assembly != null)`, all other changes were only simple code reshuffling, should not be worse?

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2305210255

**Comment by FraserGreenroyd** [comment]
I did an investigation @pawelbaran and it turns out this PR made things worse by existing 😝 the PR @adecler and I merged this morning improved the state of play, this PR being raised before that means it thought it was then going worse again.

I have dispensated the check, this is good to merge, I'll merge it now.

**Pull request merged**
