### PR TITLE
Environment_Engine: Fix typo in method name + versioning for method as appropriate

### LINKED ISSUE #2474: Environment_Engine: Fix typo for SetAdjacentSpaces method
#### Description:
Currently spelt "SetAdja**n**centSpaces"

image

Please fix :)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2474 

### Additional comments
Have versioned as well for the change so this should be good to go if the checks come back green.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by linaeriksson — APPROVED** [review]

**Pull request merged**
