### PR TITLE
Matter_Engine: Add material mapping methods

### LINKED ISSUE #2900: Matter_Engine: Add method to map Materials and MaterialCompositions to pre-defined Transdiciplinary materials
#### Description:

To allow for simpler transdisciplinary workflows going from a single discipline to preform analysis from another discipline, for example structure -> LCA, BIM MEP -> LCA, BIM -> Embodied Suffering, a simplified methodology to get fully set transdisciplinary materials matching the IElementM being used is to be implemented.

Support for a workflow were the Engineers pre-define a set of Physical materials, containing all relevant discipline data across all disciplines relevant to the project and analysis is first set up, and then used as the basis map for all Matter operations is to be added. See diagram:

image

With this, the link between a particular material name, and all of its parts can be defined once for each project, and then used across all elements that needs to be evaluated.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2900 

- Add method for mapping properties from a set of pre-defined material maps on a set of Materials
- Add methods for mapping onto MaterialCompositiona and Takeoffs
- Add methods for getting mapped Takeoffs and Compositions from a list of IElementM

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/ElafUY8_5_dOs1UN37qQ1kQBFOo2qUahCMBTEbp2g7uEag?e=rRgCke

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Review by kayleighhoude — COMMENTED** [review]
Finally got a chance to review this one- love the template, really simple to use. One issue on my end, when assigning a material from a traditional EPD dataset vs the concatenated one you provided, I received the following errors:
image

Is this because those datasets are missing the new material attribute?

**Review by michaelhoehn — APPROVED** [review]
I'm happy with these additions. I've tested pushing and pulling my own data created from the templates and have not experienced any issues. 

We should totally formalise the templated data creation layout at some point.

**Comment by michaelhoehn** [comment]
Please see the comment here https://github.com/BHoM/LifeCycleAssessment_Toolkit/pull/288#pullrequestreview-1199895883

**Comment by michaelhoehn** [comment]
Branch naming inconsistencies have required me to fork this branch for compliance purposes FYI @FraserGreenroyd

**Comment by michaelhoehn** [comment]
@BHoMBot check core

**Comment by michaelhoehn** [comment]
@BHoMBot check required

**Comment by michaelhoehn** [comment]
@BHoMBot check documentation-compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
See [here](https://github.com/BHoM/BHoM/pull/1449#pullrequestreview-1201746392).

**Pull request merged**
