### PR TITLE
Structure_Engine: Add metal deck surface property methods

### PR DESCRIPTION
**Pull request by JosefTaylor**
### NOTE: Depends on 

[BHoM PR#1386](https://github.com/BHoM/BHoM/pull/1388)
   
### Issues addressed by this PR

Closes #

### CODE REVIEW

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
Generally looks good.

Some changes are needed before this is merged:

- SolidVolume calculation need to be ensured to be correct for Panels with any of these types. It might be the case that the current solution of using AverageThickness is not enough any longer, ad it might need to be rewritten.
- MaterialComposition for IAreaElement need to be retwritten now that we have SurfaceProperties with more than one material.

Think both these two needs to be handled before this is merged.

**Comment by JosefTaylor** [comment]
@IsakNaslundBh checking MaterialComposition and Mass(IElementM) these are both issues which also affect the Layered property. I'm going to have a try at re-writing those so they take account that these include multiple materials.

**Comment by JosefTaylor** [comment]
Since this touched the method Geometry3D(Panel) method by renaming AverageThickness, I notice it's using the wrong thickness method (or, it's making an assumption about what it is being used for that may not be accurate, and is not communicated to the user). In the future, I would love for this to properly extrude ribbed, waffle, and slabondeck properties, but for now maybe it should just extrude TotalThickness and tell the user the geometry is not suitable for volume takeoff.

**Comment by JosefTaylor** [comment]
@BHoMBot check documentation-compliance
@BHoMBot check code-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning

**Review by IsakNaslundBh — DISMISSED** [review]
Happy with this now. Good changes, and general improvements for the methods.

Happy for this to be merged as soon as all bot checks are passing

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
