### PR TITLE
Base_Engine: Fix issues initialising some Random objects

### LINKED ISSUE #2983: Base_Engine: Random object do not fully instantiate all object types
#### Description:

Two issues:

- Does not instantiate objects implementing the `IFragment` interface
- Does not fully populate properties not in the constructor of `IImutable` objects (only populates parameters in the constructor)

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2983 

Closes https://github.com/BHoM/BHoM_Engine/issues/2962

- Fully populate immutable objects
- Try instantiating Fragments

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EqZaPA5q69xGjXoY1xOrVMYB22zHLHgksKnhNYF5drTCog?e=n1tgyg

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check documentation compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check documentation-compliance

**Review by alelom — DISMISSED** [review]
Approving (see my previous comment for details)

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests

**Comment by alelom** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
