### PR TITLE
Diffing_Engine: Performance of IsEqual improved

### LINKED ISSUE #3427: Diffing_Engine: IsEqual could avoid comparing all properties in case of same object being provided on both hand sides
#### Description:

Simple implementation, add `if (obj1 == obj2)` before getting into type and property comparison.

@alelom

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #3427

### Test files

DiffingTests_Prototypes

### CODE REVIEW

**Review by alelom — APPROVED** [review]
Tested with DiffingTests_Prototypes, and reviewed code. Agreed with @pawelbaran  on a call that this is an improvement and doesn't affect the `BaseComparisonConfig` functionality.

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
