### PR TITLE
MEP_Engine: Fix project reference to Matter Engine

### LINKED ISSUE #2531: MEP_Engine: Dependency on Matter_Engine is not set to a project reference
Causing some issues on CI builds.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2531

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check dataset-compliance

**Review by michaelhoehn — APPROVED** [review]
Good catch @FraserGreenroyd .... and sorry I'm pretty sure this was my bad 🚀

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
