### PR TITLE
Structure_Engine: Add warping constants for tapered flange and angle sections

### LINKED ISSUE #2706: Structure_Engine: Add warping constant calculation for TaperedFlange sections
#### Description:

Expanding on the work done in https://github.com/BHoM/BHoM_Engine/pull/2676 .

Warping constants to be added for both section types.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2706 

- Adding warping constant calculations for TaperedFlange sections
- Adding Angle sections to list of sections that return 0 value without raising warning for WapringConstant

### CODE REVIEW

**Review by JosefTaylor — APPROVED** [review]
Works great, thank you for doing this instead of making me do it!

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
