### PR TITLE
Structure_Engine: Add layered shell methods

### LINKED ISSUE #2799: Structure_Engine: AverageThickness and TotalThickness to support LayeredShell
#### Description:

Add methods to Structure Engine:

- [x] AverageThickness()
- [x] TotalThickness()
- [x] Description()
- [x] MassPerArea()

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #2799 

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Structure_Engine/%232800-Add-LayeredShell-Methods?csf=1&web=1&e=w99257

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check installer
@BHoMBot check versioning

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@BHoMBot check null-handling

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Review by IsakNaslundBh — APPROVED** [review]
Test file works as expected, descriptions look great.

Approved!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 6188841153

dispensing due to the known issues with this check

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 6188841153

**Pull request merged**
