### PR TITLE
Serialiser_Engine: Fix serialisation of Dictionary as top level object

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes https://github.com/BHoM/Excel_Toolkit/issues/279

Excel internalised its data by saving the dictionary of internalised objects as json into an hidden sheet.
Unfortunately, some code added to the ToJson method to tackle serialisation of arrays and lists (by checking for `IEnumerable`) modified the serialisation result of Dictionaries. Fortunately, this only affected the serialisation of Dictionaries as top object, not as properties. 

This PR makes sure that dictionaries are not treated as arrays when serialised. Thankfully, the change required was such that it doesn't risk to break anything else.

### Test files
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Serialiser_Engine/Excel%23279-FixSerialisationOfDictionaries?csf=1&web=1&e=J4KAgY

There's two test files in there:
- One Grasshopper file to make sure that top-level dictionaries are always serialising as they should.
- One Excel file to make sure that internalisation is working fine. The two explode tables should give the result below

image

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@BHoMBot check versioning

**Comment by adecler** [comment]
@BHoMBot check serialisation

**Comment by adecler** [comment]
@BHoMBot check project-compliance

**Comment by adecler** [comment]
@BHoMBot check core

**Comment by adecler** [comment]
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
### Test Report

I downloaded and ran today's alpha (1st April 2021) and then compiled this PR on top of that.

I downloaded and ran the Grasshopper script provided in the test assets location, and verified the result of the panels provided.

I downloaded the Excel file provided but could not get it to work, it had errors and did not look like the attached image. It appeared to have some Socket Adapter stuff in it, so possibly not the right file?

I therefore created my own file, which I have added to the test assets folder as the file `DictionaryTestFG.xlsx`. In this test file I created a dictionary of values (`<string, int>` key value pair) and exploded it, serialised it `ToJson` and then deserialised with `FromJson`. `ToJson` provided a JSON dictionary string, `FromJson` returned a `CustomObject`. I feel this is expected behaviour.

I then saved the file and reopened it, and the reopened file opened without error with everything looking as it had when it was originally saved moments prior. I feel this is expected behaviour.

As a result, I believe this PR is solving the issue it is claiming to resolve based on the above test.

I have not tested Dynamo as the third UI, nor have I run any specific serialisation tests. However, I do note the successful `check serialisation` result from BHoMBot and take that to indicate successful serialisation of BHoM Objects and Methods.

**Comment by adecler** [comment]
Thanks @FraserGreenroyd , I uploaded the correct file. 

The Grasshopper file was the key one in term of testing to make sure the serialised version of a Dictionary as top object was produced correctly. So, in a way, that's all we need to make sure the fix was applied correctly. 

The Excel file, however, is meant to check that internalisation of BHoM objects is working properly after this change (as it stores internalised data as a serialised version of a dictionary). So I would recommend you try that as well before we merge this PR. The Excel file linked is containing already internalised data and therefore makes sure that this data can be recovered correctly. If you want to test the internalisation process itself here's what I recommend to do:

- Create a few BHoM objects in a new Excel file
- Internalise them (you will notice the formula is replaced by a string)
- Save the file, close and reopen
- use those objects in another method (I find the simplest is to use explode) to make sure the internalised BHoM objects are still exposed.

I hope that all makes sense. Let me know if you need further explanation 😄

**Review by FraserGreenroyd — APPROVED** [review]
I ran the alpha from today and compiled this PR on top of it again to run through your notes @adecler .

I ran the GH file from the folder and verified the panel outputs, that still looked ok.

I opened the Excel file you added @adecler and that loaded ok and the data looked ok.

I then followed your steps on creating my own, with a simple set of points with some random XYZ values, internalised (noting the change of `=oM.Point?by_Properties(C7,D7,E7)` to `Point [sUuitbie]` when clicking the internalise button which was quite cool), saved the file, reopened the file, ran the points through `Explode` and everything worked as expected :smile:

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by adecler** [comment]
@BHoMBot check versioning

**Comment by adecler** [comment]
@BHoMBot check versioning

**Comment by adecler** [comment]
@BHoMBot check null-handling

**Comment by adecler** [comment]
@BHoMBot check core

**Comment by adecler** [comment]
@BHoMBot check installer

**Pull request merged**
