### PR TITLE
BHoM_Engine_Tests: Align with Test_Toolkit changes

### LINKED ISSUE #3014: BHoM_Engine_Tests: Align with the Test_Toolkit changes
#### Broken rules:

The tests classes in BHoM_Engine_Tests should now inherit the base `NUnitTest` abstract class, which provides for recording of events and Loading of Assemblies.

#### Suggestions to restore compliance:

As above.

### LINKED ISSUE #3059: Serializer_Engine_Tests: missing copy local for FluentAssertions
#### Description:

Need to add copy local for BHoMBot to run tests.

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

https://github.com/BHoM/Test_Toolkit/pull/422 (already merged)
https://github.com/BHoM/Test_Toolkit/pull/445 (already merged)
   
### Issues addressed by this PR

Closes #3014
Closes #3059

Existing unit test now have their class inheriting from the Test_Toolkit `NUnitTest` abstract class, which provides them with dynamic assembly loading and reporting of event log into the results of the test.

Additionally, a new Structure_Engine_Test project was added with a specific test on a method that requires dynamic assembly loading in order to work (it uses an extension method). This was added mainly to verify that the functionality added via the `NUnitTest` class works, but it is also a useful test in itself which justifies keeping it in. @FraserGreenroyd 

### Test files

Unit tests must all pass, both from Test Explorer in Visual Studio and from an NUnit TestRunner environment (BHoMBot).

### CODE REVIEW

**Comment by alelom** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@alelom I see no more reason to hold up this PR so I'm going to go for merge - the failures are from Data Driven unit tests, and we've previously tested this heavily - so I think we're good to go for merging this one and continuing developments of tests.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@alelom I've removed that this PR takes care of #3018 because this PR isn't doing that anymore so we'll need to tackle #3018 later 😄

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed over time with @alelom - some things to resolve later but this PR is in a good enough state to close out and merge in for future testing work.

**Pull request merged**
