### PR TITLE
Verifiaction: Add reference to Diffing_Engine to properly access the IsEqual method

### LINKED ISSUE #3413: VerificationSolution does not build after removal of IsEqual method from Test_Toolkit
#### Description:

After https://github.com/BHoM/Test_Toolkit/pull/474 the Verification solution does no longer build. Needs to be updated to point at the new IsEqual method.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #3413 

Fixes references to the verification solution that broke after https://github.com/BHoM/Test_Toolkit/pull/474

### Test files

Make sure compiles, and checks should be actually running on this PR.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required
@BHoMBot check compliance

**Review by pawelbaran — APPROVED** [review]
Approving on the basis of a discussion with @IsakNaslundBh

**Comment by IsakNaslundBh** [comment]
Will dispensate null handling on this PR, as the fact that it is failing now is a clear indication that it is now running, while before it was silently just being skipped due to the build errors on the verification solution.

For code compliance, I will also dispensate, as this is a project sitting outside the general Engine.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 29712010796

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
