### PR TITLE
Fix output label for BarDifferentialTemperatureLoad

### LINKED ISSUE #2911: Structure_Engine: Output label for BarDifferentialTemperatureLoad is incorrectly showing areaDiffTemp
#### Description:

Output label for `BarDifferentialTemperatureLoad` is incorrectly showing areaDiffTemp

#### Steps to reproduce:

https://github.com/BHoM/BHoM_Engine/blob/79d04831ac3922716a8d8bac1a2df0166cd8bee8/Structure_Engine/Create/Loads/BarDifferentialTemperatureLoad.cs#L109

#### Expected behaviour:

Output should be barDiffTemp

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #2911

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by IsakNaslundBh — APPROVED** [review]
Only fixing typo in description. change looks good!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
