### PR TITLE
Geometry_Engine: Using explicit casting in Offset to avoid losing cPts while passing arguments to Polyline method

### LINKED ISSUE #2021: Geometry_Engine: Offset(PolyCurve) misses controlPoints while passsing arguments to Offset(Polyline)
#### Description:

Offset passes PolyCurves with only lines segments to the Polyline method which is a bit faster and more reliable. Some control points are lost during that operation

### PR DESCRIPTION
**Pull request by LMarkowski**
### Issues addressed by this PR

Closes #2021 

Replaced former solution with explicit casting to avoid missing control points (especially for closed curves).

### Test files

[Issue specific](https://burohappold.sharepoint.com/:f:/s/BHoM/EoUweCi8HYVBsS42hfgiDq4BwcSR1vzY7mbYByRTZM7mkA?e=MhFHHx)
[General offset test](https://burohappold.sharepoint.com/:f:/s/BHoM/EtBlmGmRgQNFrZn2dLnm0EUBD5LFSAt13Lz7uL01kJxpFg?e=du27WM)

### Changelog

- Modified `Offset(Polyline)` method in the `Geometry_Engine`

### CODE REVIEW

**Review by pawelbaran — COMMENTED** [review]
The code changes look LGTM, functionality wise everything seems fine (all offsets make sense), but there is a few nulls as well as fails in the test file:

image

Happy to approve once the above is sorted.

**Comment by LMarkowski** [comment]
@pawelbaran errors were caused by outdated components in the verifying clusters. Should be alright now.

**Review by pawelbaran — APPROVED** [review]
LGTM now 👍

**Comment by alelom** [comment]
Code-wise this looks good to me!

**Pull request merged**
